//! The modern renderer's fidelity pass (renderer plan §4 "(i) Fidelity
//! pass"): the forward shading of M1-M5 and M9 re-aligned to the modern
//! client's shader maths. The WGSL is translated, not copied. Where the
//! modern client takes a value from its host code rather than its shaders,
//! this crate keeps its own value and the constant below says so.
//!
//! # What changes against the reconstruction (the modern client wins over the classic one)
//!
//! - **Sun specular, RT5 materials** (the classic materials: every floor and
//!   model): the classic Phong of the reflected sun, added untinted,
//!   becomes Schlick fresnel `F0 = 0.65`, power 5, times the normalised
//!   Blinn-Phong `(p + 2) / 8 * N.H^p`, times the shadowed sun; the sum
//!   `ambient + diffuse + specular * D` is multiplied by the albedo, so the
//!   highlight takes the surface colour. A specular-map material (texture
//!   alpha as the mask, classic effects 1/7) scales the specular by
//!   `D = 1 + 4 * alpha`, not by the alpha. The exponent is still the
//!   classic material's (the modern client reads it from a material settings
//!   atlas that its host code fills).
//! - **RT7 materials**: the compound map is metalness (red) and roughness
//!   (green; alpha in the ETC copies), default metal 0 and roughness 0.9
//!   without one; the albedo mixes to the bare texel with metalness; the sun
//!   specular is a Cook-Torrance (GGX of roughness² with a `1e-4` floor,
//!   Schlick-Smith visibility of the power `8192^(1 - roughness)`), the
//!   diffuse and ambient scaled by the energy conservation factor of the
//!   roughness-aware Schlick fresnel, and the normal map's red (alpha in ETC)
//!   is the emissive mask. The material's non-metal specular, fresnel
//!   exponent, roughness multiplier and emissive colour, source and scale
//!   are settings-atlas values the host code writes: chosen here
//!   ([`RT7_NON_METAL_SPECULAR`], [`RT7_FRESNEL_EXPONENT`],
//!   [`RT7_ROUGHNESS_MULTIPLIER`]; emissive colour source 0 and scale 0, the
//!   atlas's zero). The data agree with the roles
//!   (`models::materials` test `compound_maps_hold_metalness_and_roughness`).
//! - **Normal maps**: the compressed-normal unpack is `c * 255 / 127 - 1.00787`
//!   (was `2c - 1`), Y negated, Z rebuilt with `min(1, x² + y²)`.
//! - **Point lights**: one law for floors and models (the classic renderer
//!   had two), `pow(1 - min(1 - 1/65535, d²/r²), falloff)`, times the
//!   wrapped `N.L`, times the clamped colour times the intensity (the
//!   shader's `0.2 * 5`): the classic model law `r²/d²` is gone, and the
//!   clamp moves from `colour * intensity` to the colour. The per-light
//!   falloff exponent and wrap are host-code values ([`POINT_LIGHT_FALLOFF`]
//!   = 1 and wrap 0 reproduce the classic terrain law); the intensity
//!   packing is host code, so the M4 [`crate::lighting::point_lights::STRENGTH`]
//!   stays. Diffuse only (the specular term is a host-code switch; the
//!   classic renderer had none).
//! - **Fog**: the distance fog of the Euclidean eye distance, computed per
//!   vertex and interpolated (the model, billboard and particle vertex
//!   programs alike), applied as `c * out + in` (in- and out-scattering),
//!   instead of the per-fragment view depth. The fog start and range stay
//!   the classic fog's (the host code sets them).
//! - **Sun shadows**: the position offset along the normal by the shadow
//!   normal bias before the lookup (the value is host code; the modern
//!   client's shader defines 32.0, used here, see the constant in
//!   `crate::shadows`); the modern client's cascade selection per quality
//!   (low and medium by the cascades' bounding spheres, high and ultra by
//!   the best map, `crate::shadows::cascade_selection`; the classic renderer
//!   chose by split for low/medium); nothing past the last split; the 2x2
//!   box filter shifted half a texel with a 1.5-texel border and the
//!   approximate 4x4 box shifted likewise (its tap offsets are generated by
//!   host code; here the 4x4 box's integer offsets); past the low-quality
//!   shadow depth the 2x2 box, not one tap.
//! - **Model billboards**: the coverage squared always (M8 squared it only
//!   with the post chain on) and the alpha test on the squared value.
//! - **Particles**: premultiplied output `(rgb * a, a * alphaOutput)` into a
//!   `ONE, ONE_MINUS_SRC_ALPHA` blend, discarded at `a <= 0.01`; the alpha
//!   output is 0 for additive particles and 1 otherwise, and the classic
//!   particle set has no additive mode (the faithful toolkit blends every
//!   particle with `SRC_ALPHA`), so it is 1. Blended billboards take the same
//!   premultiplied pipeline (the same result as their `SRC_ALPHA` blend).
//!
//! # Kept, with the reason (see the plan's table)
//!
//! Hemisphere ambient (the modern client multiplies the ambient colour by
//! the SH irradiance or the map-square probes, M6); the environment's
//! sun/ambient balance (host-code values;
//! `crate::lighting::environment::look`); the 2.2 display transfer (the
//! modern client's sRGB-to-linear is a square under a host-code switch, else
//! `pow 2.2`, with `sqrt` out; the pair is a host-code choice and water
//! shares it); the sky (the modern client samples a cubemap with angle fog;
//! the classic sky layers stay); the tonemap and grading (M8, already the
//! modern client's); HDR scale (unchanged); the faithful alpha tests; the
//! point-light tile rule of models (the classic selection).
//!
use crate::lighting::point_lights::Light;

/// The constant `F0` of the RT5 sun and point-light specular.
pub const RT5_F0: f32 = 0.65;
/// The RT5 fresnel power.
pub const RT5_FRESNEL_POWER: f32 = 5.0;
/// A specular map's scale: `D = 1 + 4 * alpha`.
pub const SPEC_MAP_SCALE: f32 = 4.0;
/// The point lights' falloff exponent (the modern client reads it per light
/// from its index texture, host code; 1 is the classic terrain law).
pub const POINT_LIGHT_FALLOFF: f32 = 1.0;
/// RT7 `nonMetalSpecular` (a settings-atlas byte the host code writes): the usual
/// dielectric reflectance, chosen.
pub const RT7_NON_METAL_SPECULAR: f32 = 0.04;
/// RT7 `fresnelExponent` (settings atlas, host code): Schlick's 5, the RT5 path's
/// constant, chosen.
pub const RT7_FRESNEL_EXPONENT: f32 = 5.0;
/// RT7 `roughnessMultiplier` (settings atlas, host code): neutral, chosen.
pub const RT7_ROUGHNESS_MULTIPLIER: f32 = 1.0;
/// The modern client's compound defaults without a compound map: metal 0,
/// roughness 0.9.
pub const RT7_DEFAULT_COMPOUND: [f32; 2] = [0.0, 0.9];
/// A particle fragment at or below this alpha is discarded.
pub const PARTICLE_ALPHA_MIN: f32 = 0.01;

/// The blend of the blended sprite pipeline (group 2): premultiplied
/// (as the modern client's particle shader does).
#[must_use]
pub fn sprite_blend() -> wgpu::BlendState {
    wgpu::BlendState::PREMULTIPLIED_ALPHA_BLENDING
}

pub fn constants_wgsl() -> String {
    format!(
        "
// models::shading's constants (see its docs).
const RT5_F0: f32 = {RT5_F0:?};
const RT5_FRESNEL_POWER: f32 = {RT5_FRESNEL_POWER:?};
const SPEC_MAP_SCALE: f32 = {SPEC_MAP_SCALE:?};
const POINT_LIGHT_FALLOFF: f32 = {POINT_LIGHT_FALLOFF:?};
const RT7_NON_METAL_SPECULAR: f32 = {RT7_NON_METAL_SPECULAR:?};
const RT7_FRESNEL_EXPONENT: f32 = {RT7_FRESNEL_EXPONENT:?};
const RT7_ROUGHNESS_MULTIPLIER: f32 = {RT7_ROUGHNESS_MULTIPLIER:?};
const RT7_DEFAULT_METAL: f32 = {:?};
const RT7_DEFAULT_ROUGHNESS: f32 = {:?};
const PARTICLE_ALPHA_MIN: f32 = {PARTICLE_ALPHA_MIN:?};
",
        RT7_DEFAULT_COMPOUND[0], RT7_DEFAULT_COMPOUND[1]
    )
}

/// The frame's point lights as the modern client lights them: the colour
/// clamped, then times the intensity (the classic renderer clamped the
/// product).
#[must_use]
pub fn frame_lights(lights: &rs910_scene::model_lights::ModelLights) -> Vec<Light> {
    lights
        .lights
        .iter()
        .enumerate()
        .map(|(id, l)| {
            let intensity = lights.intensities.get(id).copied().unwrap_or(1.0);
            let rgb = lights.colour(id).unwrap_or(l.colour);
            Light {
                pos: [l.x as f32, l.y as f32, l.z as f32],
                radius: l.radius as f32,
                colour: colour_term(rgb, intensity),
                intensity,
                casts_shadows: true,
            }
        })
        .collect()
}

/// The point-light colour term: `clamp(c / 255, 0, 1) * intensity`
/// (the shader's `q * 0.2 * 5` is the intensity).
#[must_use]
pub fn colour_term(rgb: i32, intensity: f32) -> [f32; 3] {
    [16, 8, 0].map(|s| (((rgb >> s) & 0xFF) as f32 / 255.0).clamp(0.0, 1.0) * intensity)
}

/// The point-light attenuation at distance `d`
/// of a light of radius `r`, with [`POINT_LIGHT_FALLOFF`].
#[must_use]
pub fn point_attenuation(d: f32, r: f32) -> f32 {
    (1.0 - (d * d / (r * r)).min(1.0 - 1.0 / 65535.0)).powf(POINT_LIGHT_FALLOFF)
}

/// The RT5 sun specular per unit of shadowed sun light: Schlick fresnel of `L.H` times the normalised
/// Blinn-Phong of `N.H` at `power`.
#[must_use]
pub fn rt5_specular(power: f32, n_dot_h: f32, l_dot_h: f32) -> f32 {
    let fresnel = RT5_F0 + (1.0 - RT5_F0) * (1.0 - l_dot_h.clamp(0.0, 1.0)).powf(RT5_FRESNEL_POWER);
    fresnel * (power + 2.0) * 0.125 * n_dot_h.max(0.0).powf(power)
}

/// The distance fog amount at eye distance
/// `distance` of a fog starting at `start` with `inv_range` = 1 / (end -
/// start).
#[must_use]
pub fn fog_amount(distance: f32, start: f32, inv_range: f32) -> f32 {
    ((distance - start) * inv_range).clamp(0.0, 1.0)
}
