//! Immutable GPU encoding inputs. Preparation-only model/config owners
//! never enter a worker borrow; Rust checks that these inputs are Sync.

use crate::frame::*;

const COLOUR_CHANNELS: usize = 3;

pub(crate) struct EncodeInputs<'a> {
    pub(crate) frame_buffer: &'a wgpu::Buffer,
    pub(crate) shadow_frame: &'a Option<ShadowFrame>,
    pub(crate) sky_texture_layout: &'a wgpu::BindGroupLayout,
    pub(crate) sky_layer_layout: &'a wgpu::BindGroupLayout,
    pub(crate) pipeline_inputs: &'a crate::frame::pipelines::PipelineInputs,
    pub(crate) shaders: &'a crate::shaders::Library,
    pub(crate) samples: u32,
    pub(crate) textures: &'a Textures,
    pub(crate) ambient: &'a crate::frame::gpu::ambient::AmbientGpu,
    pub(crate) arena: &'a Arena,
    pub(crate) atmos: &'a crate::frame::gpu::atmosphere::AtmosGpu,
    pub(crate) clear: [f32; COLOUR_CHANNELS],
    pub(crate) draws: &'a [Draw],
    pub(crate) far: &'a crate::frame::gpu::far::FarGpu,
    pub(crate) floors: &'a [Option<FloorGpu>],
    pub(crate) frame_bind: &'a wgpu::BindGroup,
    pub(crate) instance_buffer: &'a Option<(wgpu::Buffer, u64)>,
    pub(crate) interior: &'a crate::frame::gpu::interior::InteriorGpu,
    pub(crate) jobs: &'a crate::frame::jobs::Jobs,
    pub(crate) lights: &'a LightGpu,
    pub(crate) loc_arena: &'a crate::frame::arenas::LocArena,
    pub(crate) packets: &'a crate::frame::submit::FramePackets,
    pub(crate) pass_order: &'a crate::frame::passes::Order,
    pub(crate) pipelines:
        &'a crate::frame::pipelines::Variants<u32, crate::frame::pipelines::SamplePipelines>,
    pub(crate) post: &'a PostGpu,
    pub(crate) probes: &'a ProbeGpu,
    pub(crate) scaled: &'a Option<crate::frame::scale::Scaled>,
    pub(crate) settings: crate::settings::ModernSettings,
    pub(crate) shadow: &'a ShadowGpu,
    pub(crate) shadow_only: &'a [(Draw, u8)],
    pub(crate) sky: &'a [SkyDraw],
    pub(crate) sky_cubes: &'a crate::frame::gpu::sky_cube::SkyCubes,
    pub(crate) sky_layer_buffer: &'a Option<(wgpu::Buffer, wgpu::BindGroup, u64)>,
    pub(crate) sky_textures: &'a HashMap<SkyTextureKey, SkyTextureGpu>,
    pub(crate) sky_white: &'a wgpu::BindGroup,
    pub(crate) sprites: &'a SpriteGpu,
    pub(crate) targets: &'a Option<Targets>,
    pub(crate) terrain: &'a crate::frame::gpu::terrain::TerrainGpu,
    pub(crate) water: &'a crate::frame::gpu::water::WaterGpu,
}

impl ModernRenderer {
    pub(crate) fn encoding_inputs(&self) -> EncodeInputs<'_> {
        EncodeInputs {
            frame_buffer: &self.device_resources.frame_buffer,
            shadow_frame: &self.frame_resources.shadow_frame,
            sky_texture_layout: &self.device_resources.sky_texture_layout,
            sky_layer_layout: &self.device_resources.sky_layer_layout,
            pipeline_inputs: &self.device_resources.pipeline_inputs,
            shaders: &self.device_resources.shaders,
            samples: self.device_resources.samples,
            textures: &self.device_resources.textures,
            ambient: &self.history.ambient,
            arena: &self.frame_resources.arena,
            atmos: &self.frame_resources.atmos,
            clear: self.frame_resources.clear,
            draws: &self.frame_resources.draws,
            far: &self.scene_resources.far,
            floors: &self.scene_resources.floors,
            frame_bind: &self.device_resources.frame_bind,
            instance_buffer: &self.frame_resources.instance_buffer,
            interior: &self.scene_resources.interior,
            jobs: &self.jobs,
            lights: &self.scene_resources.lights,
            loc_arena: &self.scene_resources.loc_arena,
            packets: &self.frame_resources.packets,
            pass_order: &self.preparation.pass_order,
            pipelines: &self.device_resources.pipelines,
            post: &self.history.post,
            probes: &self.history.probes,
            scaled: &self.frame_resources.scaled,
            settings: self.preparation.settings,
            shadow: &self.history.shadow,
            shadow_only: &self.frame_resources.shadow_only,
            sky: &self.frame_resources.sky,
            sky_cubes: &self.scene_resources.sky_cubes,
            sky_layer_buffer: &self.frame_resources.sky_layer_buffer,
            sky_textures: &self.scene_resources.sky_textures,
            sky_white: &self.device_resources.sky_white,
            sprites: &self.frame_resources.sprites,
            targets: &self.frame_resources.targets,
            terrain: &self.scene_resources.terrain,
            water: &self.frame_resources.water,
        }
    }
}
