//! Scalar fields of an interface component and their defaults.
//!
//! `Fields` is the plain per-component state: layout, colours, graphics,
//! model view, text, drag/target behaviour and the per-frame redraw stamps.
//! [`FIELD_NAMES`] lists the fields in declaration order for the oracle
//! snapshots.
#![allow(non_snake_case)]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Fields {
    pub name: Option<Vec<u16>>,
    pub serverTriggers: i32,
    pub parentlayer: i32,
    pub id: i32,
    pub r#type: i32,
    pub clientcode: i32,
    pub xmode: i8,
    pub ymode: i8,
    pub widthSizeMode: i8,
    pub heightSizeMode: i8,
    pub xpos: i32,
    pub ypos: i32,
    pub wsize: i32,
    pub hsize: i32,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub aspectwidth: i32,
    pub aspectheight: i32,
    pub layer: i32,
    pub hide: bool,
    pub targetCursor: i32,
    pub targetDefaultCursor: i32,
    pub mouseovercursor: i32,
    pub noclickthrough: bool,
    pub scrollx: i32,
    pub scrolly: i32,
    pub scrollwidth: i32,
    pub scrollheight: i32,
    pub colour: i32,
    pub fill: bool,
    pub trans: i32,
    pub linewid: i32,
    pub linedirection: bool,
    pub graphic: i32,
    pub angle2d: i32,
    pub tiling: bool,
    pub outline: i32,
    pub graphicshadow: i32,
    pub vflip: bool,
    pub hflip: bool,
    pub alpha: bool,
    pub clickmask: bool,
    pub modelkind: i32,
    pub model: i32,
    pub modelNameHash: i32,
    pub useExtendedModelTransform: bool,
    pub modelxof: i32,
    pub modelyof: i32,
    pub modelangle_x: i32,
    pub modelangle_y: i32,
    pub modelangle_z: i32,
    pub modelorigin_x: i32,
    pub modelorigin_y: i32,
    pub modelorigin_z: i32,
    pub modelzoom: i32,
    pub modelobjwidth: i32,
    pub modelobjheight: i32,
    pub modelorthog: bool,
    pub disableDepthTest: bool,
    /// When an inventory-object icon shows its stack count: 0 never, 1 always,
    /// 2 only for stacks above one.
    pub obj_count_display: i32,
    pub tint_hue: i32,
    pub tint_saturation: i32,
    pub tint_luminence: i32,
    pub tint_weight: i32,
    pub customlighting: bool,
    pub lightExtraA: i32,
    pub lightExtraB: i32,
    pub lightExtraC: i32,
    pub lightDirY: i32,
    pub lightDirZ: i32,
    pub lightDirX: i32,
    pub lightColour: i32,
    pub lightExtraD: i32,
    pub textfont: i32,
    pub fontmono: bool,
    pub text: Option<Vec<u16>>,
    pub textLineHeight: i32,
    pub textHAlign: i32,
    pub textVAlign: i32,
    pub textshadow: bool,
    pub maxlines: i32,
    pub textantimacro: bool,
    pub hasKeybinds: bool,
    pub opbase: Option<Vec<u16>>,
    pub pausetext: Option<Vec<u16>>,
    pub targetopcursor: i32,
    pub dragdeadzone: i32,
    pub dragdeadtime: i32,
    pub dragrenderbehaviour: i32,
    pub targetverb: Option<Vec<u16>>,
    pub hashook: bool,
    pub invobject: i32,
    pub invcount: i32,
    pub link: Option<Vec<u16>>,
    pub usePlayerModel: bool,
    pub skyboxId: i32,
    /// Skybox view offsets: pitch and yaw in eighths of an angle unit, then
    /// the viewer position used to place sky decorations.
    pub skybox_pitch: i32,
    pub skybox_yaw: i32,
    pub skybox_view_x: i32,
    pub skybox_view_y: i32,
    pub skybox_view_z: i32,
    pub httpImageId: i32,
    pub modelanim: i32,
    pub hovered: bool,
    pub held: bool,
    pub lastRedrawCycle: i32,
    pub lastVarTransmit: i32,
    pub lastInvTransmit: i32,
    pub lastStatTransmit: i32,
    pub lastVarcTransmit: i32,
    pub lastVarcstrTransmit: i32,
    pub lastVarclanTransmit: i32,
    pub topLevelIndex: i32,
    pub lastDrawCycle: i32,
}
/// Recorded text-constructor state carried by an imported creation use.
/// Layout, paint and text fields are projected; other class constructors are
/// separate resources and cannot acquire these defaults implicitly.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TextChildTemplate {
    pub source_kind: u8,
    pub component_type: i32,
    pub colour: i32,
    pub transparency: u8,
    pub aspect: [i32; 2],
    pub font: i32,
    pub monochrome: bool,
    pub line_height: i32,
    pub horizontal_align: i32,
    pub vertical_align: i32,
    pub max_lines: i32,
    pub shadow: bool,
    pub antimacro: bool,
}
impl TextChildTemplate {
    const FORMAT: &'static [u8] = b"ALTO-TEXT-CHILD\x01";
    pub fn fields(self) -> Fields {
        Fields {
            r#type: self.component_type,
            colour: self.colour,
            trans: i32::from(self.transparency),
            aspectwidth: self.aspect[0],
            aspectheight: self.aspect[1],
            textfont: self.font,
            fontmono: self.monochrome,
            text: Some(Vec::new()),
            textLineHeight: self.line_height,
            textHAlign: self.horizontal_align,
            textVAlign: self.vertical_align,
            maxlines: self.max_lines,
            textshadow: self.shadow,
            textantimacro: self.antimacro,
            ..Fields::default()
        }
    }
    pub fn encode_resource(self) -> Vec<u8> {
        let mut writer = native910::packet::ByteWriter::default();
        writer.pdata(Self::FORMAT);
        writer.p1(self.source_kind);
        writer.p4s(self.component_type);
        writer.p4s(self.colour);
        writer.p1(self.transparency);
        for value in self.aspect {
            writer.p4s(value);
        }
        writer.p4s(self.font);
        writer.p1(u8::from(self.monochrome));
        writer.p4s(self.line_height);
        writer.p4s(self.horizontal_align);
        writer.p4s(self.vertical_align);
        writer.p4s(self.max_lines);
        writer.p1(u8::from(self.shadow));
        writer.p1(u8::from(self.antimacro));
        writer.data
    }
    pub fn decode_resource(bytes: &[u8]) -> anyhow::Result<Self> {
        let mut packet = native910::packet::Packet::new(bytes);
        anyhow::ensure!(
            packet.gdata(Self::FORMAT.len(), "text constructor header")? == Self::FORMAT,
            "unknown text constructor resource"
        );
        let boolean = |packet: &mut native910::packet::Packet<'_>| -> anyhow::Result<bool> {
            let value = packet.g1()?;
            anyhow::ensure!(value <= u8::from(true), "invalid text constructor flag");
            Ok(value != u8::default())
        };
        let template = Self {
            source_kind: packet.g1()?,
            component_type: packet.g4s()?,
            colour: packet.g4s()?,
            transparency: packet.g1()?,
            aspect: [packet.g4s()?, packet.g4s()?],
            font: packet.g4s()?,
            monochrome: boolean(&mut packet)?,
            line_height: packet.g4s()?,
            horizontal_align: packet.g4s()?,
            vertical_align: packet.g4s()?,
            max_lines: packet.g4s()?,
            shadow: boolean(&mut packet)?,
            antimacro: boolean(&mut packet)?,
        };
        anyhow::ensure!(
            packet.remaining() == usize::default(),
            "trailing text constructor bytes"
        );
        Ok(template)
    }
}

impl Default for Fields {
    fn default() -> Self {
        Self {
            name: None,
            serverTriggers: 0,
            parentlayer: -1,
            id: -1,
            r#type: 0,
            clientcode: 0,
            xmode: 0,
            ymode: 0,
            widthSizeMode: 0,
            heightSizeMode: 0,
            xpos: 0,
            ypos: 0,
            wsize: 0,
            hsize: 0,
            x: 0,
            y: 0,
            width: 0,
            height: 0,
            aspectwidth: 1,
            aspectheight: 1,
            layer: -1,
            hide: false,
            targetCursor: -1,
            targetDefaultCursor: -1,
            mouseovercursor: -1,
            noclickthrough: false,
            scrollx: 0,
            scrolly: 0,
            scrollwidth: 0,
            scrollheight: 0,
            colour: 0,
            fill: false,
            trans: 0,
            linewid: 1,
            linedirection: false,
            graphic: -1,
            angle2d: 0,
            tiling: false,
            outline: 0,
            graphicshadow: 0,
            vflip: false,
            hflip: false,
            alpha: false,
            clickmask: true,
            modelkind: 1,
            model: 0,
            modelNameHash: -1,
            useExtendedModelTransform: false,
            modelxof: 0,
            modelyof: 0,
            modelangle_x: 0,
            modelangle_y: 0,
            modelangle_z: 0,
            modelorigin_x: 0,
            modelorigin_y: 0,
            modelorigin_z: 0,
            modelzoom: 100,
            modelobjwidth: 0,
            modelobjheight: 0,
            modelorthog: false,
            disableDepthTest: false,
            obj_count_display: 2,
            tint_hue: 0,
            tint_saturation: 0,
            tint_luminence: 0,
            tint_weight: 0,
            customlighting: false,
            lightExtraA: 0,
            lightExtraB: 0,
            lightExtraC: 0,
            lightDirY: 0,
            lightDirZ: 0,
            lightDirX: 0,
            lightColour: 0,
            lightExtraD: 0,
            textfont: -1,
            fontmono: true,
            text: Some(Vec::new()),
            textLineHeight: 0,
            textHAlign: 0,
            textVAlign: 0,
            textshadow: false,
            maxlines: 0,
            textantimacro: false,
            hasKeybinds: false,
            opbase: Some(Vec::new()),
            pausetext: None,
            targetopcursor: -1,
            dragdeadzone: 0,
            dragdeadtime: 0,
            dragrenderbehaviour: 0,
            targetverb: Some(Vec::new()),
            hashook: false,
            invobject: -1,
            invcount: 0,
            link: None,
            usePlayerModel: false,
            skyboxId: -1,
            skybox_pitch: 0,
            skybox_yaw: 0,
            skybox_view_x: 0,
            skybox_view_y: 0,
            skybox_view_z: 0,
            httpImageId: -1,
            modelanim: -1,
            hovered: false,
            held: false,
            lastRedrawCycle: -1,
            lastVarTransmit: 0,
            lastInvTransmit: 0,
            lastStatTransmit: 0,
            lastVarcTransmit: 0,
            lastVarcstrTransmit: 0,
            lastVarclanTransmit: 0,
            topLevelIndex: -1,
            lastDrawCycle: -1,
        }
    }
}
#[cfg(any(test, feature = "test-hooks"))]
pub const FIELD_NAMES: &[&str] = &[
    "name",
    "serverTriggers",
    "parentlayer",
    "id",
    "type",
    "clientcode",
    "xmode",
    "ymode",
    "widthSizeMode",
    "heightSizeMode",
    "xpos",
    "ypos",
    "wsize",
    "hsize",
    "x",
    "y",
    "width",
    "height",
    "aspectwidth",
    "aspectheight",
    "layer",
    "hide",
    "targetCursor",
    "targetDefaultCursor",
    "mouseovercursor",
    "noclickthrough",
    "scrollx",
    "scrolly",
    "scrollwidth",
    "scrollheight",
    "colour",
    "fill",
    "trans",
    "linewid",
    "linedirection",
    "graphic",
    "angle2d",
    "tiling",
    "outline",
    "graphicshadow",
    "vflip",
    "hflip",
    "alpha",
    "clickmask",
    "modelkind",
    "model",
    "modelNameHash",
    "useExtendedModelTransform",
    "modelxof",
    "modelyof",
    "modelangle_x",
    "modelangle_y",
    "modelangle_z",
    "modelorigin_x",
    "modelorigin_y",
    "modelorigin_z",
    "modelzoom",
    "modelobjwidth",
    "modelobjheight",
    "modelorthog",
    "disableDepthTest",
    "obj_count_display",
    "tint_hue",
    "tint_saturation",
    "tint_luminence",
    "tint_weight",
    "customlighting",
    "lightExtraA",
    "lightExtraB",
    "lightExtraC",
    "lightDirY",
    "lightDirZ",
    "lightDirX",
    "lightColour",
    "lightExtraD",
    "textfont",
    "fontmono",
    "text",
    "textLineHeight",
    "textHAlign",
    "textVAlign",
    "textshadow",
    "maxlines",
    "textantimacro",
    "hasKeybinds",
    "opbase",
    "pausetext",
    "targetopcursor",
    "dragdeadzone",
    "dragdeadtime",
    "dragrenderbehaviour",
    "targetverb",
    "hashook",
    "invobject",
    "invcount",
    "link",
    "usePlayerModel",
    "skyboxId",
    "skybox_pitch",
    "skybox_yaw",
    "skybox_view_x",
    "skybox_view_y",
    "skybox_view_z",
    "httpImageId",
    "modelanim",
    "hovered",
    "held",
    "lastRedrawCycle",
    "lastVarTransmit",
    "lastInvTransmit",
    "lastStatTransmit",
    "lastVarcTransmit",
    "lastVarcstrTransmit",
    "lastVarclanTransmit",
    "topLevelIndex",
    "lastDrawCycle",
];
