//! Symbol registry: curated script names over mined structural facts.
//!
//! Measured corpus truth (not assumptions): 910 scripts carry no name tags,
//! every scripts-pack group holds exactly one file, and every `gosub` operand
//! in the corpus names a group id. So a callee's identity IS its group id, and
//! human names can only be curated — the Ghidra-naming workflow, not mined
//! magic. `names.txt` (tracked, hand-edited) holds those; the registry joins
//! them with per-script argument counts mined from headers at dump time, which
//! is what the signature-aware `~name(args)` call syntax validates against,
//! plus inferred return counts, which is what calls-as-values (`x = ~f()`)
//! validate against. Unknown returns (`- - -`) and known-void (`0 0 0`) are
//! distinct: the former rejects value use as unknowable, the latter as arity.
//!
//! File shapes (both line-oriented, `#` comments, blank lines ignored):
//!
//! ```text
//! # names.txt — curated: `script <id> <name>`.
//! script 5690 bank_build_init
//! ```
//!
//! ```text
//! # symbols.txt — generated by `dump`; do not hand-edit.
//! script <id> <name|-> <args-int> <args-obj> <args-long> <ret-int|-> <ret-obj|-> <ret-long|->
//! script 0 - 3 0 0 - - -
//! script 5690 bank_build_init 1 0 0 1 0 0
//! ```
//!
//! Legacy six-column `symbols.txt` rows (no returns section) still read, as
//! all-unknown.

use crate::error::{NativeError, Result};
use crate::script::Counts;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

/// One script's registry entry: curated name (if any) over mined facts.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ScriptSymbol {
    /// Gosub operand value (the group id).
    pub id: i32,
    /// Curated name, if anyone has named it yet.
    pub name: Option<String>,
    /// Declared argument counts, mined from the script header.
    pub args: Counts,
    /// Inferred return counts (`None` = statically unknowable). Populated at
    /// dump time by return-arity inference; hand-written registries leave it
    /// empty unless they carry a generated returns section.
    pub returns: Option<Counts>,
}

/// Name → callee resolution plus the generated-file round-trip.
#[derive(Clone, Debug, Default)]
pub struct SymbolRegistry {
    by_id: BTreeMap<i32, ScriptSymbol>,
    by_name: BTreeMap<String, i32>,
    call_context: Option<std::sync::Arc<CallContext>>,
}

/// Local analysis inputs are separate from serialized, universal signatures.
#[derive(Clone, Debug)]
struct CallContext {
    scripts: BTreeMap<i32, crate::script::CompiledScript>,
    configs: crate::config::ConfigTypes,
    summaries: crate::dataflow::Summaries,
}

impl SymbolRegistry {
    /// Empty registry: every callee renders numeric.
    #[must_use]
    pub fn empty() -> Self {
        Self::default()
    }

    /// Whether any names are curated.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.by_name.is_empty()
    }

    /// Count of named scripts.
    #[must_use]
    pub fn named_count(&self) -> usize {
        self.by_name.len()
    }

    /// Count of known scripts (named or not).
    #[must_use]
    pub fn len(&self) -> usize {
        self.by_id.len()
    }

    /// Build from curated `(id, name)` pairs over the mined `id → arg counts`
    /// map. Names must be valid idents, unique, and point at known scripts —
    /// anything else is a typo worth failing loudly over.
    pub fn build(curated: Vec<(i32, String)>, known: &BTreeMap<i32, Counts>) -> Result<Self> {
        let mut by_id = BTreeMap::new();
        for (id, args) in known {
            by_id.insert(
                *id,
                ScriptSymbol {
                    id: *id,
                    name: None,
                    args: *args,
                    returns: None,
                },
            );
        }
        let mut by_name = BTreeMap::new();
        for (id, name) in curated {
            if !crate::source::is_valid_name(&name) {
                return Err(NativeError::Invalid(format!(
                    "bad script name '{name}' for id {id}"
                )));
            }
            let entry = by_id.get_mut(&id).ok_or_else(|| {
                NativeError::Invalid(format!(
                    "named script id {id} ('{name}') is not a known script"
                ))
            })?;
            if entry.name.is_some() {
                return Err(NativeError::Invalid(format!(
                    "duplicate name entry for script id {id}"
                )));
            }
            if by_name.contains_key(&name) {
                return Err(NativeError::Invalid(format!(
                    "script name '{name}' already names id {}",
                    by_name[&name]
                )));
            }
            entry.name = Some(name.clone());
            by_name.insert(name, id);
        }
        Ok(Self {
            by_id,
            by_name,
            call_context: None,
        })
    }

    /// Resolve a `~name` call to its callee id.
    #[must_use]
    pub fn resolve_call(&self, name: &str) -> Option<i32> {
        self.by_name.get(name).copied()
    }

    /// Curated name for a callee id, if anyone has named it.
    #[must_use]
    pub fn name_for_call(&self, id: i32) -> Option<&str> {
        self.by_id.get(&id).and_then(|entry| entry.name.as_deref())
    }

    /// Mined argument counts for a script id.
    #[must_use]
    pub fn args_of(&self, id: i32) -> Option<Counts> {
        self.by_id.get(&id).map(|entry| entry.args)
    }

    /// Attach inferred return counts (only entries for known ids take).
    /// Unknown ids are ignored: inference output is keyed by the same pack
    /// walk that built the registry, so extras cannot occur in practice.
    #[must_use]
    pub fn with_returns(mut self, returns: &BTreeMap<i32, Counts>) -> Self {
        for (id, counts) in returns {
            if let Some(entry) = self.by_id.get_mut(id) {
                entry.returns = Some(*counts);
            }
        }
        self
    }

    /// Attach call-site analysis inputs. Only unresolved named scripts and
    /// their dependencies are retained; facts never enter `symbols.txt`.
    #[must_use]
    pub fn with_call_context(
        mut self,
        scripts: &BTreeMap<i32, crate::script::CompiledScript>,
        configs: &crate::config::ConfigTypes,
        summaries: &crate::dataflow::Summaries,
    ) -> Self {
        // Loaded corpus facts supersede stale generated return columns. A
        // header mismatch cannot establish a usable call contract.
        for (id, entry) in &mut self.by_id {
            if let Some(script) = scripts.get(id) {
                entry.returns = if script.args == entry.args {
                    match summaries.0.get(id) {
                        Some(crate::returns::ReturnArity::Known { int, obj, long }) => {
                            Some(Counts {
                                int: *int,
                                obj: *obj,
                                long: *long,
                            })
                        }
                        _ => None,
                    }
                } else {
                    None
                };
            }
        }
        let roots = self
            .by_name
            .values()
            .copied()
            .filter(|id| self.returns_of(*id).is_none());
        let selected = crate::dataflow::dependency_closure(scripts, roots);
        self.call_context = (!selected.is_empty()).then(|| {
            let arities = selected
                .keys()
                .filter_map(|id| summaries.0.get(id).map(|arity| (*id, *arity)))
                .collect();
            let values = selected
                .keys()
                .filter_map(|id| summaries.1.get(id).map(|values| (*id, values.clone())))
                .collect();
            std::sync::Arc::new(CallContext {
                scripts: selected,
                configs: configs.clone(),
                summaries: (arities, values),
            })
        });
        self
    }

    /// Resolve this call's shape without changing the script's generic row.
    #[must_use]
    pub fn returns_for_call(
        &self,
        id: i32,
        arguments: &crate::dataflow::EntryArguments,
    ) -> Option<Counts> {
        if let Some(counts) = self.returns_of(id) {
            return Some(counts);
        }
        let context = self.call_context.as_ref()?;
        let script = context.scripts.get(&id)?;
        if self.args_of(id) != Some(script.args) {
            return None;
        }
        let analysis = crate::dataflow::analyze_in_context(
            script,
            &context.scripts,
            &context.summaries.0,
            &context.summaries.1,
            &context.configs,
            arguments,
        );
        match analysis.arity {
            crate::returns::ReturnArity::Known { int, obj, long } => {
                Some(Counts { int, obj, long })
            }
            crate::returns::ReturnArity::Unknown | crate::returns::ReturnArity::Never => None,
        }
    }

    /// Inferred return counts for a script id (`None` = unknowable or absent).
    #[must_use]
    pub fn returns_of(&self, id: i32) -> Option<Counts> {
        self.by_id.get(&id).and_then(|entry| entry.returns)
    }

    /// Render the generated `symbols.txt`. Returns ride as three trailing
    /// columns (`- - -` when unknown); every row carries all nine so the
    /// format stays greppable and single-shaped.
    #[must_use]
    pub fn emit_symbols_txt(&self) -> String {
        let mut out = String::from(
            "# native910 symbols — generated from client.scripts.js5; do not hand-edit.\n\
             # Curate names in names.txt and re-run dump.\n\
             # script <id> <name|-> <args-int> <args-obj> <args-long> <ret-int|-> <ret-obj|-> <ret-long|->\n",
        );
        for entry in self.by_id.values() {
            // Unknown returns render as dashes; known (even all-zero) as numbers.
            let ret = |value: Option<u16>| {
                value.map_or_else(|| "-".to_string(), |count| count.to_string())
            };
            let returns = entry.returns;
            let _ = writeln!(
                out,
                "script {} {} {} {} {} {} {} {}",
                entry.id,
                entry.name.as_deref().unwrap_or("-"),
                entry.args.int,
                entry.args.obj,
                entry.args.long,
                ret(returns.map(|counts| counts.int)),
                ret(returns.map(|counts| counts.obj)),
                ret(returns.map(|counts| counts.long))
            );
        }
        out
    }

    /// Parse a generated `symbols.txt` back (what `assemble --symbols` reads).
    /// Accepts the current nine-column rows and legacy six-column rows
    /// (which carry no returns section: all unknown).
    pub fn parse_symbols_txt(text: &str) -> Result<Self> {
        let mut entries: BTreeMap<i32, (Option<String>, Counts, Option<Counts>)> = BTreeMap::new();
        for (position, raw) in text.lines().enumerate() {
            let line_no = position + 1;
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let parts: Vec<&str> = line.split_whitespace().collect();
            let err =
                |what: &str| NativeError::Invalid(format!("symbols.txt line {line_no}: {what}"));
            if parts.len() != 6 && parts.len() != 9 || parts[0] != "script" {
                return Err(err(
                    "expected 'script <id> <name|-> <ai> <ao> <al> [<ri> <ro> <rl>]'",
                ));
            }
            let id: i32 = parts[1].parse().map_err(|_| err("bad script id"))?;
            let name = if parts[2] == "-" {
                None
            } else {
                if !crate::source::is_valid_name(parts[2]) {
                    return Err(err("bad script name"));
                }
                Some(parts[2].to_string())
            };
            let counts = Counts {
                int: parts[3].parse().map_err(|_| err("bad args-int"))?,
                obj: parts[4].parse().map_err(|_| err("bad args-obj"))?,
                long: parts[5].parse().map_err(|_| err("bad args-long"))?,
            };
            let returns = if parts.len() == 9 {
                let cell = |text: &str, what: &str| {
                    if text == "-" {
                        Ok(None)
                    } else {
                        text.parse().map(Some).map_err(|_| err(what))
                    }
                };
                match (
                    cell(parts[6], "bad ret-int")?,
                    cell(parts[7], "bad ret-obj")?,
                    cell(parts[8], "bad ret-long")?,
                ) {
                    (None, None, None) => None,
                    (Some(int), Some(obj), Some(long)) => Some(Counts { int, obj, long }),
                    _ => return Err(err("mixed known/unknown return counts")),
                }
            } else {
                None
            };
            if entries.contains_key(&id) {
                return Err(err("duplicate script id"));
            }
            entries.insert(id, (name, counts, returns));
        }
        let mut by_id = BTreeMap::new();
        let mut by_name = BTreeMap::new();
        for (id, (name, args, returns)) in entries {
            if let Some(name) = &name {
                if by_name.contains_key(name) {
                    return Err(NativeError::Invalid(format!(
                        "symbols.txt: name '{name}' used twice"
                    )));
                }
                by_name.insert(name.clone(), id);
            }
            by_id.insert(
                id,
                ScriptSymbol {
                    id,
                    name,
                    args,
                    returns,
                },
            );
        }
        Ok(Self {
            by_id,
            by_name,
            call_context: None,
        })
    }

    /// Parse a curated `names.txt` into `(id, name)` pairs.
    pub fn parse_names_txt(text: &str) -> Result<Vec<(i32, String)>> {
        let mut out = Vec::new();
        for (position, raw) in text.lines().enumerate() {
            let line_no = position + 1;
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let parts: Vec<&str> = line.split_whitespace().collect();
            let err =
                |what: &str| NativeError::Invalid(format!("names.txt line {line_no}: {what}"));
            if parts.len() != 3 || parts[0] != "script" {
                return Err(err("expected 'script <id> <name>'"));
            }
            let id: i32 = parts[1].parse().map_err(|_| err("bad script id"))?;
            if !crate::source::is_valid_name(parts[2]) {
                return Err(err("bad script name"));
            }
            out.push((id, parts[2].to_string()));
        }
        Ok(out)
    }

    /// Ids the registry knows (for gates over call targets).
    pub fn known_ids(&self) -> BTreeSet<i32> {
        self.by_id.keys().copied().collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn known() -> BTreeMap<i32, Counts> {
        BTreeMap::from([
            (
                5690,
                Counts {
                    int: 1,
                    obj: 0,
                    long: 0,
                },
            ),
            (5712, Counts::default()),
        ])
    }

    #[test]
    fn build_validates_names_loudly() {
        let registry =
            SymbolRegistry::build(vec![(5690, "bank_build_init".to_string())], &known()).unwrap();
        assert_eq!(registry.resolve_call("bank_build_init"), Some(5690));
        assert_eq!(registry.name_for_call(5690), Some("bank_build_init"));
        assert_eq!(registry.name_for_call(5712), None);
        assert_eq!(registry.named_count(), 1);

        // Unknown id, bad name, duplicate name, duplicate id entry.
        assert!(SymbolRegistry::build(vec![(9999, "ghost".to_string())], &known()).is_err());
        assert!(SymbolRegistry::build(vec![(5690, "has space".to_string())], &known()).is_err());
        assert!(
            SymbolRegistry::build(
                vec![(5690, "same".to_string()), (5712, "same".to_string())],
                &known()
            )
            .is_err()
        );
    }

    #[test]
    fn symbols_txt_roundtrips_names_and_counts() {
        let registry =
            SymbolRegistry::build(vec![(5690, "bank_build_init".to_string())], &known()).unwrap();
        let text = registry.emit_symbols_txt();
        assert!(text.contains("script 5690 bank_build_init 1 0 0 - - -\n"));
        assert!(text.contains("script 5712 - 0 0 0 - - -\n"));
        let back = SymbolRegistry::parse_symbols_txt(&text).unwrap();
        assert_eq!(back.resolve_call("bank_build_init"), Some(5690));
        assert_eq!(
            back.args_of(5690),
            Some(Counts {
                int: 1,
                obj: 0,
                long: 0
            })
        );
        assert_eq!(back.returns_of(5690), None);
        assert!(SymbolRegistry::parse_symbols_txt("script 1 a 0 0\n").is_err());
        assert!(SymbolRegistry::parse_symbols_txt("script 1 a 0 0 0\nscript 1 b 0 0 0\n").is_err());
    }

    #[test]
    fn symbols_txt_roundtrips_returns_and_reads_legacy_rows() {
        let registry = SymbolRegistry::build(vec![(5690, "bank_build_init".to_string())], &known())
            .unwrap()
            .with_returns(&BTreeMap::from([(
                5690,
                Counts {
                    int: 1,
                    obj: 0,
                    long: 0,
                },
            )]));
        assert_eq!(
            registry.returns_of(5690),
            Some(Counts {
                int: 1,
                obj: 0,
                long: 0
            })
        );
        assert_eq!(registry.returns_of(5712), None);
        let text = registry.emit_symbols_txt();
        assert!(text.contains("script 5690 bank_build_init 1 0 0 1 0 0\n"));
        assert!(text.contains("script 5712 - 0 0 0 - - -\n"));
        let back = SymbolRegistry::parse_symbols_txt(&text).unwrap();
        assert_eq!(
            back.returns_of(5690),
            Some(Counts {
                int: 1,
                obj: 0,
                long: 0
            })
        );
        // Legacy six-column rows read as all-unknown.
        let legacy = SymbolRegistry::parse_symbols_txt("script 7 named 2 0 0\n").unwrap();
        assert_eq!(legacy.resolve_call("named"), Some(7));
        assert_eq!(legacy.returns_of(7), None);
        // Known-void (0 0 0) and unknown (- - -) stay distinct.
        let voided = SymbolRegistry::parse_symbols_txt("script 7 named 2 0 0 0 0 0\n").unwrap();
        assert_eq!(voided.returns_of(7), Some(Counts::default()));
        // Mixed known/unknown cells are rejected, not guessed.
        assert!(SymbolRegistry::parse_symbols_txt("script 7 named 2 0 0 1 - -\n").is_err());
        // with_returns ignores ids outside the registry.
        let registry = SymbolRegistry::build(Vec::new(), &known())
            .unwrap()
            .with_returns(&BTreeMap::from([(
                9999,
                Counts {
                    int: 1,
                    obj: 0,
                    long: 0,
                },
            )]));
        assert_eq!(registry.returns_of(9999), None);
    }

    #[test]
    fn names_txt_parses_curated_lines() {
        let entries = SymbolRegistry::parse_names_txt(
            "# comment\n\nscript 5690 bank_build_init\nscript 5712 shop_draw\n",
        )
        .unwrap();
        assert_eq!(
            entries,
            vec![
                (5690, "bank_build_init".to_string()),
                (5712, "shop_draw".to_string())
            ]
        );
        assert!(SymbolRegistry::parse_names_txt("script x bad\n").is_err());
        assert!(SymbolRegistry::parse_names_txt("proc 1 x\n").is_err());
    }
}
