//! `magic-ids <dir|file>...` (used by `magic-id-ratchet.py`): integer
//! literals standing where a content id goes in client Rust, the Rust half of
//! the server's `alto/no-magic-id` rule (docs/symbols.md).
//!
//! The scan reads syntax only, so it finds an id by where a number stands;
//! the nearest name decides:
//!
//! - the value of a name that says it holds an id: a `const`, `static` or
//!   `let` named after a content type (`CHOP_SEQ = 21191`; not a `usize`), a
//!   struct field (`Spot { spot: 155, .. }`), an assignment
//!   (`self.interface = 1477`), a `for` binding (`for iface in [1473, 1477]`);
//!   only a const or static named just `ID` counts by that name;
//! - the first argument, a plain number, of a call whose name says what it
//!   takes (`remove_interface_options(883)`, `obj_type(1511)`);
//! - a comparison, an `assert_eq!` or a `match` arm against something named
//!   after a content type (`seq_id == 897`, `match interface { 1477 => .. }`);
//! - an interface packed into a component, and the component
//!   (`(1477 << 16) | 14`); a shift by 16 alone is not one.
//!
//! A file-local `const NAME: i32 = 1511;` used in such a position counts
//! once, at its definition. Arithmetic, other bit operations and indexing
//! are never ids, nor is the value of a name ending in a quantity word
//! (`SEQ_FRAMES`, `LOC_TYPE`), nor 0 and -1 (the "none" values). Arrays,
//! tuples, casts, references and parentheses are see-through; a call decides
//! by its own name. Generated files (a `Generated by` header) are skipped.
//!
//! A line whose comment says `not a content id` is skipped (for what the
//! syntax cannot tell).
//!
//! Output: `file\tline\tvalue\tname` per literal (`name` is the const for a
//! counted const), then `files\t<count>`.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use syn::punctuated::Punctuated;
use syn::spanned::Spanned;
use syn::visit::{self, Visit};
use syn::{BinOp, Expr, Lit, Pat, Token, UnOp};

/// Words of a name that say it holds a content id.
const TYPE_WORDS: &[&str] = &[
    "obj",
    "objs",
    "item",
    "npc",
    "npcs",
    "loc",
    "locs",
    "seq",
    "seqs",
    "sequence",
    "anim",
    "spot",
    "spotanim",
    "enum",
    "param",
    "struct",
    "inv",
    "invs",
    "varp",
    "varps",
    "varbit",
    "varbits",
    "varc",
    "varcs",
    "interface",
    "interfaces",
    "iface",
    "component",
    "script",
    "clientscript",
    "dbtable",
    "dbrow",
];

/// Last words that make a name a quantity or a part, not an id.
const QUANTITY_TAILS: &[&str] = &[
    "events",
    "mask",
    "flags",
    "form",
    "shape",
    "direction",
    "count",
    "size",
    "len",
    "length",
    "delay",
    "ticks",
    "chance",
    "frame",
    "frames",
    "cycle",
    "cycles",
    "index",
    "idx",
    "slot",
    "slots",
    "offset",
    "x",
    "y",
    "z",
    "width",
    "height",
    "bits",
    "bytes",
    "speed",
    "time",
    "duration",
    "timer",
    "max",
    "min",
    "total",
    "depth",
    "pos",
    "level",
    "state",
    "op",
    "ops",
    "type",
    "types",
    "angle",
    "rotation",
    "detail",
    "scale",
    "layer",
    "kind",
    "mode",
    "step",
    "priority",
    "colour",
    "color",
    "volume",
    "rate",
    "radius",
    "distance",
    "range",
    "opcode",
    "opcodes",
    "version",
    "key",
    "hash",
    "weight",
    "stack",
    "tint",
    "hue",
    "n",
    "code",
    "codes",
    "file",
    "files",
    "age",
    "chat",
    "timeout",
    "clip",
    "slot",
    "bas",
];

/// A comment on a line that holds a number the scan takes for an id but is
/// not one (a transform slot named `component_id`, say).
pub const NOT_AN_ID: &str = "not a content id";

/// Names that are an id by themselves (`id: 1511`), only as the whole name.
const WHOLE_ID_NAMES: &[&str] = &["id", "ids"];

fn words(name: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut prev_lower = false;
    for ch in name.trim_start_matches("r#").chars() {
        if ch == '_' {
            if !cur.is_empty() {
                out.push(std::mem::take(&mut cur));
            }
            prev_lower = false;
            continue;
        }
        if ch.is_uppercase() && prev_lower && !cur.is_empty() {
            out.push(std::mem::take(&mut cur));
        }
        prev_lower = ch.is_lowercase() || ch.is_ascii_digit();
        cur.extend(ch.to_lowercase());
    }
    if !cur.is_empty() {
        out.push(cur);
    }
    out
}

fn names_an_id(name: &str) -> bool {
    let parts = words(name);
    if let Some(last) = parts.last() {
        if parts.len() > 1 && QUANTITY_TAILS.contains(&last.as_str()) {
            return false;
        }
    }
    parts.iter().any(|w| TYPE_WORDS.contains(&w.as_str()))
}

/// The last name of an expression: `self.interface` is `interface`, `a.obj_id()` is `obj_id`.
fn last_name(e: &Expr) -> Option<String> {
    match e {
        Expr::Path(p) => p.path.segments.last().map(|s| s.ident.to_string()),
        Expr::Field(f) => match &f.member {
            syn::Member::Named(i) => Some(i.to_string()),
            syn::Member::Unnamed(_) => None,
        },
        Expr::MethodCall(m) => Some(m.method.to_string()),
        Expr::Call(c) => last_name(&c.func),
        Expr::Paren(p) => last_name(&p.expr),
        Expr::Reference(r) => last_name(&r.expr),
        Expr::Unary(u) if matches!(u.op, UnOp::Deref(_)) => last_name(&u.expr),
        Expr::Cast(c) => last_name(&c.expr),
        _ => None,
    }
}

/// Whether `other`, compared with a number, is named after a content type (`seq_id`, `obj.id`).
fn compared_with_id(other: &Expr) -> bool {
    let Some(name) = last_name(other) else {
        return false;
    };
    if WHOLE_ID_NAMES.contains(&name.to_lowercase().as_str()) {
        // `x.id`: the owner decides.
        let owner = match other {
            Expr::Field(f) => last_name(&f.base),
            Expr::MethodCall(m) => last_name(&m.receiver),
            _ => None,
        };
        return owner.is_some_and(|o| names_an_id(&o));
    }
    names_an_id(&name)
}

fn int_value(e: &Expr) -> Option<i128> {
    match e {
        Expr::Lit(l) => match &l.lit {
            Lit::Int(i) => i.base10_parse::<i128>().ok(),
            _ => None,
        },
        Expr::Paren(p) => int_value(&p.expr),
        _ => None,
    }
}

fn strip_paren(e: &Expr) -> &Expr {
    match e {
        Expr::Paren(p) => strip_paren(&p.expr),
        _ => e,
    }
}

/// An integer literal through parentheses and casts.
fn strip(e: &Expr) -> Option<i128> {
    match e {
        Expr::Cast(c) => strip(&c.expr),
        _ => int_value(e),
    }
}

/// A number or a single name, through casts, parentheses and a minus sign.
fn plain_number(e: &Expr) -> bool {
    match e {
        Expr::Lit(l) => matches!(l.lit, Lit::Int(_)),
        Expr::Path(p) => p.path.segments.len() == 1,
        Expr::Paren(p) => plain_number(&p.expr),
        Expr::Cast(c) => plain_number(&c.expr),
        Expr::Unary(u) if matches!(u.op, UnOp::Neg(_)) => plain_number(&u.expr),
        _ => false,
    }
}

/// A const or static named only `ID` holds an id; a bare `id` field,
/// binding or argument belongs to too many things that are not content
/// (fonts, sprites, components' own slots).
fn const_names_an_id(name: &str) -> bool {
    WHOLE_ID_NAMES.contains(&name.to_lowercase().as_str()) || names_an_id(name)
}

/// Integer types that hold counts and sizes, never ids.
fn quantity_type(ty: &syn::Type) -> bool {
    match ty {
        syn::Type::Path(p) => {
            p.path.is_ident("usize") || p.path.is_ident("f32") || p.path.is_ident("f64")
        }
        _ => false,
    }
}

/// `(<number> << 16) | <number or name>`: an interface and its component
/// (not a colour or a key, whose other part is another shift or a call).
fn is_component(left: &Expr, right: &Expr) -> bool {
    (is_interface_shift(left) && plain_number(right))
        || (is_interface_shift(right) && plain_number(left))
}

/// `<number> << 16`: the interface half of a packed component.
fn is_interface_shift(e: &Expr) -> bool {
    match e {
        Expr::Binary(b) if matches!(b.op, BinOp::Shl(_)) => {
            int_value(&b.right) == Some(16) && strip(&b.left).is_some()
        }
        Expr::Paren(p) => is_interface_shift(&p.expr),
        _ => false,
    }
}

fn pat_name(p: &Pat) -> Option<String> {
    match p {
        Pat::Ident(i) => Some(i.ident.to_string()),
        Pat::Type(t) => pat_name(&t.pat),
        _ => None,
    }
}

#[derive(Default)]
struct Scan {
    /// The current expression stands where an id goes.
    id: bool,
    /// File-local integer consts: name -> (line, value).
    consts: BTreeMap<String, (usize, i128)>,
    /// Consts used where an id goes.
    used: BTreeSet<String>,
    hits: Vec<(usize, i128, String)>,
}

impl Scan {
    fn with(&mut self, id: bool, e: &Expr) {
        let was = std::mem::replace(&mut self.id, id);
        self.visit_expr(e);
        self.id = was;
    }

    fn literal(&mut self, e: &Expr, value: i128) {
        if value != 0 {
            self.hits
                .push((e.span().start().line, value, String::new()));
        }
    }

    /// A call named after a content type takes the id first: only a plain
    /// number (or a const) in that position counts.
    fn arguments<'a>(&mut self, takes: bool, mut args: impl Iterator<Item = &'a Expr>) {
        if let Some(first) = args.next() {
            self.with(takes && plain_number(first), first);
        }
        args.for_each(|a| self.with(false, a));
    }

    fn pattern_literals(&mut self, p: &Pat) {
        match p {
            Pat::Lit(l) => {
                if let Lit::Int(i) = &l.lit {
                    if let Ok(v) = i.base10_parse::<i128>() {
                        if v != 0 {
                            self.hits.push((l.span().start().line, v, String::new()));
                        }
                    }
                }
            }
            Pat::Or(o) => o.cases.iter().for_each(|c| self.pattern_literals(c)),
            Pat::Paren(p) => self.pattern_literals(&p.pat),
            _ => {}
        }
    }

    fn macro_args(&mut self, mac: &syn::Macro, ctx: bool) {
        let name = mac
            .path
            .segments
            .last()
            .map(|s| s.ident.to_string())
            .unwrap_or_default();
        let parse = |m: &syn::Macro| {
            m.parse_body_with(Punctuated::<Expr, Token![,]>::parse_terminated)
                .ok()
                .map(|p| p.into_iter().collect::<Vec<_>>())
        };
        match name.as_str() {
            "assert_eq" | "assert_ne" | "debug_assert_eq" | "debug_assert_ne" => {
                if let Some(args) = parse(mac) {
                    if args.len() >= 2 {
                        let (a, b) = (&args[0], &args[1]);
                        self.with(compared_with_id(b), a);
                        self.with(compared_with_id(a), b);
                    }
                }
            }
            "vec" => {
                if let Some(args) = parse(mac) {
                    args.iter().for_each(|a| self.with(ctx, a));
                }
            }
            "assert" | "debug_assert" => {
                if let Some(args) = parse(mac) {
                    if let Some(first) = args.first() {
                        self.with(false, first);
                    }
                }
            }
            _ => {}
        }
    }
}

impl<'ast> Visit<'ast> for Scan {
    fn visit_expr(&mut self, e: &'ast Expr) {
        let ctx = std::mem::replace(&mut self.id, false);
        match e {
            Expr::Lit(l) => {
                if let (true, Lit::Int(i)) = (ctx, &l.lit) {
                    if let Ok(v) = i.base10_parse::<i128>() {
                        self.literal(e, v);
                    }
                }
            }
            Expr::Unary(u) if matches!(u.op, UnOp::Neg(_)) => {
                if int_value(&u.expr) == Some(1) {
                    return;
                }
                self.with(ctx, &u.expr);
            }
            Expr::Paren(p) => self.with(ctx, &p.expr),
            Expr::Group(g) => self.with(ctx, &g.expr),
            Expr::Cast(c) => self.with(ctx, &c.expr),
            Expr::Reference(r) => self.with(ctx, &r.expr),
            Expr::Array(a) => a.elems.iter().for_each(|x| self.with(ctx, x)),
            Expr::Tuple(t) => t.elems.iter().for_each(|x| self.with(ctx, x)),
            Expr::Path(p) => {
                if ctx && p.path.segments.len() == 1 {
                    let name = p.path.segments[0].ident.to_string();
                    if self.consts.contains_key(&name) {
                        self.used.insert(name);
                    }
                }
            }
            Expr::Call(c) => {
                let takes = last_name(&c.func).is_some_and(|n| names_an_id(&n));
                self.with(false, &c.func);
                self.arguments(takes, c.args.iter());
            }
            Expr::MethodCall(m) => {
                let takes = names_an_id(&m.method.to_string());
                self.with(false, &m.receiver);
                self.arguments(takes, m.args.iter());
            }
            Expr::Binary(b) => match b.op {
                BinOp::Eq(_) | BinOp::Ne(_) => {
                    self.with(compared_with_id(&b.right), &b.left);
                    self.with(compared_with_id(&b.left), &b.right);
                }
                BinOp::BitOr(_) if is_component(&b.left, &b.right) => {
                    let (shift, rest) = if is_interface_shift(&b.left) {
                        (&b.left, &b.right)
                    } else {
                        (&b.right, &b.left)
                    };
                    if let Expr::Binary(sb) = strip_paren(shift) {
                        self.with(true, &sb.left);
                    }
                    self.with(true, rest);
                }
                _ => {
                    self.with(false, &b.left);
                    self.with(false, &b.right);
                }
            },
            Expr::Assign(a) => {
                let named = last_name(&a.left).is_some_and(|n| names_an_id(&n));
                self.with(false, &a.left);
                self.with(named, &a.right);
            }
            Expr::Struct(s) => {
                for f in &s.fields {
                    let named = match &f.member {
                        syn::Member::Named(i) => names_an_id(&i.to_string()),
                        syn::Member::Unnamed(_) => false,
                    };
                    self.with(named, &f.expr);
                }
                if let Some(rest) = &s.rest {
                    self.with(false, rest);
                }
            }
            Expr::Match(m) => {
                let named = compared_with_id(&m.expr);
                self.with(false, &m.expr);
                for arm in &m.arms {
                    if named {
                        self.pattern_literals(&arm.pat);
                    }
                    if let Some((_, guard)) = &arm.guard {
                        self.with(false, guard);
                    }
                    self.with(false, &arm.body);
                }
            }
            Expr::ForLoop(f) => {
                let named = pat_name(&f.pat).is_some_and(|n| names_an_id(&n));
                self.with(named, &f.expr);
                self.visit_block(&f.body);
            }
            Expr::Macro(m) => self.macro_args(&m.mac, ctx),
            _ => visit::visit_expr(self, e),
        }
    }

    fn visit_stmt_macro(&mut self, m: &'ast syn::StmtMacro) {
        self.macro_args(&m.mac, false);
    }

    fn visit_local(&mut self, l: &'ast syn::Local) {
        let named = pat_name(&l.pat).is_some_and(|n| names_an_id(&n));
        if let Some(init) = &l.init {
            self.with(named, &init.expr);
            if let Some((_, diverge)) = &init.diverge {
                self.with(false, diverge);
            }
        }
    }

    fn visit_item_const(&mut self, c: &'ast syn::ItemConst) {
        self.with(
            !quantity_type(&c.ty) && const_names_an_id(&c.ident.to_string()),
            &c.expr,
        );
    }

    fn visit_item_static(&mut self, s: &'ast syn::ItemStatic) {
        self.with(
            !quantity_type(&s.ty) && const_names_an_id(&s.ident.to_string()),
            &s.expr,
        );
    }

    fn visit_impl_item_const(&mut self, c: &'ast syn::ImplItemConst) {
        self.with(
            !quantity_type(&c.ty) && const_names_an_id(&c.ident.to_string()),
            &c.expr,
        );
    }
}

/// Integer consts of a file (at any depth): `const NAME: <int> = <literal>;`.
#[derive(Default)]
struct Consts(BTreeMap<String, (usize, i128)>);

impl<'ast> Visit<'ast> for Consts {
    fn visit_item_const(&mut self, c: &'ast syn::ItemConst) {
        if let Some(v) = int_value(&c.expr) {
            self.0
                .insert(c.ident.to_string(), (c.ident.span().start().line, v));
        }
        visit::visit_item_const(self, c);
    }
}

fn rs_files(path: &Path, out: &mut Vec<PathBuf>) {
    if path.is_file() {
        out.push(path.to_path_buf());
        return;
    }
    let Ok(rd) = fs::read_dir(path) else { return };
    let mut entries: Vec<_> = rd.flatten().map(|e| e.path()).collect();
    entries.sort();
    for p in entries {
        if p.is_dir() {
            rs_files(&p, out);
        } else if p.extension().is_some_and(|x| x == "rs") {
            out.push(p);
        }
    }
}

/// The hits of one source text: (line, value, const name or empty).
pub fn scan_source(src: &str) -> Result<Vec<(usize, i128, String)>, syn::Error> {
    let file = syn::parse_file(src)?;
    let mut consts = Consts::default();
    consts.visit_file(&file);
    let mut scan = Scan {
        consts: consts.0,
        ..Scan::default()
    };
    scan.visit_file(&file);
    let mut hits = scan.hits;
    for name in &scan.used {
        let (line, value) = scan.consts[name];
        if value != 0 && value != -1 {
            hits.push((line, value, name.clone()));
        }
    }
    // An escape for what the syntax cannot tell: a line that says so.
    let lines: Vec<&str> = src.lines().collect();
    hits.retain(|h| !lines.get(h.0 - 1).is_some_and(|l| l.contains(NOT_AN_ID)));
    hits.sort();
    hits.dedup_by_key(|h| (h.0, h.1));
    Ok(hits)
}

pub fn cmd(args: &[String]) -> ExitCode {
    if args.is_empty() {
        eprintln!("usage: rsscan magic-ids <dir|file>...");
        return ExitCode::from(2);
    }
    let mut files = Vec::new();
    for a in args {
        rs_files(Path::new(a), &mut files);
    }
    let mut errors = 0;
    for f in &files {
        let Ok(src) = fs::read_to_string(f) else {
            continue;
        };
        if src.lines().take(3).any(|l| l.contains("Generated by")) {
            continue;
        }
        match scan_source(&src) {
            Ok(hits) => {
                for (line, value, name) in hits {
                    println!("{}\t{line}\t{value}\t{name}", f.display());
                }
            }
            Err(e) => {
                eprintln!("{}: {e}", f.display());
                errors += 1;
            }
        }
    }
    println!("files\t{}", files.len());
    if errors > 0 {
        return ExitCode::from(2);
    }
    ExitCode::SUCCESS
}

#[cfg(test)]
mod tests {
    use super::scan_source;

    fn values(src: &str) -> Vec<i128> {
        scan_source(src).unwrap().into_iter().map(|h| h.1).collect()
    }

    #[test]
    fn finds_ids_by_the_name_they_stand_under() {
        let src = r"
            const CHOP_SEQ: i32 = 21191;
            const SEQ_FRAMES: i32 = 12;
            const LOGS: i32 = 1511;
            fn f(m: &mut M, obj_id: i32) {
                m.remove_interface_options(883);
                for iface in [1473, 1477] {}
                for id in [1020, 1021] {}
                let size = 1 << 16;
                let colour = (238 << 16) | (238 << 8) | 238;
                let seq_id = 99; // not a content id
                let x = (1465 << 16) | 18;
                assert_eq!(obj_id, 995);
                m.set_obj(LOGS);
                let n = obj_id + 7;
                match obj_id { 4151 | 4152 => {}, _ => {} }
                let none = m.obj(-1);
                let s = Spot { spot: 155, x: 3 };
            }
        ";
        let mut v = values(src);
        v.sort_unstable();
        assert_eq!(
            v,
            vec![18, 155, 883, 995, 1465, 1473, 1477, 1511, 4151, 4152, 21191]
        );
    }
}
