// Generated by `npm --prefix server run sym -- gen` from revisions/910/symbols/component.sym. Do not edit: add symbols
// with `npm --prefix server run sym -- add` (docs/symbols.md).

//! The named component ids of revision 910, a module per interface.

pub mod action_bar {
    use crate::ComponentId;

    /// 1430:253, `kind=layer`
    pub const EXTRA_SELECTOR: ComponentId = ComponentId::new(1430, 253);
    /// 1430:69, `kind=layer`
    pub const ITEM_SLOT_1: ComponentId = ComponentId::new(1430, 69);
    /// 1430:186, `kind=layer`
    pub const ITEM_SLOT_10: ComponentId = ComponentId::new(1430, 186);
    /// 1430:199, `kind=layer`
    pub const ITEM_SLOT_11: ComponentId = ComponentId::new(1430, 199);
    /// 1430:212, `kind=layer`
    pub const ITEM_SLOT_12: ComponentId = ComponentId::new(1430, 212);
    /// 1430:225, `kind=layer`
    pub const ITEM_SLOT_13: ComponentId = ComponentId::new(1430, 225);
    /// 1430:238, `kind=layer`
    pub const ITEM_SLOT_14: ComponentId = ComponentId::new(1430, 238);
    /// 1430:82, `kind=layer`
    pub const ITEM_SLOT_2: ComponentId = ComponentId::new(1430, 82);
    /// 1430:95, `kind=layer`
    pub const ITEM_SLOT_3: ComponentId = ComponentId::new(1430, 95);
    /// 1430:108, `kind=layer`
    pub const ITEM_SLOT_4: ComponentId = ComponentId::new(1430, 108);
    /// 1430:121, `kind=layer`
    pub const ITEM_SLOT_5: ComponentId = ComponentId::new(1430, 121);
    /// 1430:134, `kind=layer`
    pub const ITEM_SLOT_6: ComponentId = ComponentId::new(1430, 134);
    /// 1430:147, `kind=layer`
    pub const ITEM_SLOT_7: ComponentId = ComponentId::new(1430, 147);
    /// 1430:160, `kind=layer`
    pub const ITEM_SLOT_8: ComponentId = ComponentId::new(1430, 160);
    /// 1430:173, `kind=layer`
    pub const ITEM_SLOT_9: ComponentId = ComponentId::new(1430, 173);
    /// 1430:262, `kind=graphic`
    pub const LOCK: ComponentId = ComponentId::new(1430, 262);
    /// 1430:259, `kind=graphic`
    pub const NEXT: ComponentId = ComponentId::new(1430, 259);
    /// 1430:77, `kind=graphic`
    pub const PIERCING_SHOT_SLOT: ComponentId = ComponentId::new(1430, 77);
    /// 1430:258, `kind=graphic`
    pub const PREVIOUS: ComponentId = ComponentId::new(1430, 258);
    /// 1430:254, `kind=graphic`
    pub const SELECTOR: ComponentId = ComponentId::new(1430, 254);
    /// 1430:264, `kind=graphic`
    pub const SETTINGS: ComponentId = ComponentId::new(1430, 264);
    /// 1430:64, `kind=graphic`
    pub const SLICE_SLOT: ComponentId = ComponentId::new(1430, 64);
    /// 1430:181, `kind=graphic`
    pub const SLOT_10: ComponentId = ComponentId::new(1430, 181);
    /// 1430:194, `kind=graphic`
    pub const SLOT_11: ComponentId = ComponentId::new(1430, 194);
    /// 1430:207, `kind=graphic`
    pub const SLOT_12: ComponentId = ComponentId::new(1430, 207);
    /// 1430:220, `kind=graphic`
    pub const SLOT_13: ComponentId = ComponentId::new(1430, 220);
    /// 1430:233, `kind=graphic`
    pub const SLOT_14: ComponentId = ComponentId::new(1430, 233);
    /// 1430:103, `kind=graphic`
    pub const SLOT_4: ComponentId = ComponentId::new(1430, 103);
    /// 1430:116, `kind=graphic`
    pub const SLOT_5: ComponentId = ComponentId::new(1430, 116);
    /// 1430:129, `kind=graphic`
    pub const SLOT_6: ComponentId = ComponentId::new(1430, 129);
    /// 1430:142, `kind=graphic`
    pub const SLOT_7: ComponentId = ComponentId::new(1430, 142);
    /// 1430:155, `kind=graphic`
    pub const SLOT_8: ComponentId = ComponentId::new(1430, 155);
    /// 1430:168, `kind=graphic`
    pub const SLOT_9: ComponentId = ComponentId::new(1430, 168);
    /// 1430:90, `kind=graphic`
    pub const WRACK_SLOT: ComponentId = ComponentId::new(1430, 90);
}

pub mod action_bar_quaternary {
    use crate::ComponentId;

    /// 1672:5, `kind=layer`
    pub const EXTRA_SELECTOR: ComponentId = ComponentId::new(1672, 5);
    /// 1672:18, `kind=layer`
    pub const ITEM_SLOT_1: ComponentId = ComponentId::new(1672, 18);
    /// 1672:135, `kind=layer`
    pub const ITEM_SLOT_10: ComponentId = ComponentId::new(1672, 135);
    /// 1672:148, `kind=layer`
    pub const ITEM_SLOT_11: ComponentId = ComponentId::new(1672, 148);
    /// 1672:161, `kind=layer`
    pub const ITEM_SLOT_12: ComponentId = ComponentId::new(1672, 161);
    /// 1672:174, `kind=layer`
    pub const ITEM_SLOT_13: ComponentId = ComponentId::new(1672, 174);
    /// 1672:187, `kind=layer`
    pub const ITEM_SLOT_14: ComponentId = ComponentId::new(1672, 187);
    /// 1672:31, `kind=layer`
    pub const ITEM_SLOT_2: ComponentId = ComponentId::new(1672, 31);
    /// 1672:44, `kind=layer`
    pub const ITEM_SLOT_3: ComponentId = ComponentId::new(1672, 44);
    /// 1672:57, `kind=layer`
    pub const ITEM_SLOT_4: ComponentId = ComponentId::new(1672, 57);
    /// 1672:70, `kind=layer`
    pub const ITEM_SLOT_5: ComponentId = ComponentId::new(1672, 70);
    /// 1672:83, `kind=layer`
    pub const ITEM_SLOT_6: ComponentId = ComponentId::new(1672, 83);
    /// 1672:96, `kind=layer`
    pub const ITEM_SLOT_7: ComponentId = ComponentId::new(1672, 96);
    /// 1672:109, `kind=layer`
    pub const ITEM_SLOT_8: ComponentId = ComponentId::new(1672, 109);
    /// 1672:122, `kind=layer`
    pub const ITEM_SLOT_9: ComponentId = ComponentId::new(1672, 122);
    /// 1672:6, `kind=graphic`
    pub const SELECTOR: ComponentId = ComponentId::new(1672, 6);
    /// 1672:3, `kind=graphic`
    pub const SETTINGS: ComponentId = ComponentId::new(1672, 3);
    /// 1672:13, `kind=graphic`
    pub const SLOT_1: ComponentId = ComponentId::new(1672, 13);
    /// 1672:130, `kind=graphic`
    pub const SLOT_10: ComponentId = ComponentId::new(1672, 130);
    /// 1672:143, `kind=graphic`
    pub const SLOT_11: ComponentId = ComponentId::new(1672, 143);
    /// 1672:156, `kind=graphic`
    pub const SLOT_12: ComponentId = ComponentId::new(1672, 156);
    /// 1672:169, `kind=graphic`
    pub const SLOT_13: ComponentId = ComponentId::new(1672, 169);
    /// 1672:182, `kind=graphic`
    pub const SLOT_14: ComponentId = ComponentId::new(1672, 182);
    /// 1672:26, `kind=graphic`
    pub const SLOT_2: ComponentId = ComponentId::new(1672, 26);
    /// 1672:39, `kind=graphic`
    pub const SLOT_3: ComponentId = ComponentId::new(1672, 39);
    /// 1672:52, `kind=graphic`
    pub const SLOT_4: ComponentId = ComponentId::new(1672, 52);
    /// 1672:65, `kind=graphic`
    pub const SLOT_5: ComponentId = ComponentId::new(1672, 65);
    /// 1672:78, `kind=graphic`
    pub const SLOT_6: ComponentId = ComponentId::new(1672, 78);
    /// 1672:91, `kind=graphic`
    pub const SLOT_7: ComponentId = ComponentId::new(1672, 91);
    /// 1672:104, `kind=graphic`
    pub const SLOT_8: ComponentId = ComponentId::new(1672, 104);
    /// 1672:117, `kind=graphic`
    pub const SLOT_9: ComponentId = ComponentId::new(1672, 117);
}

pub mod action_bar_quinary {
    use crate::ComponentId;

    /// 1673:5, `kind=layer`
    pub const EXTRA_SELECTOR: ComponentId = ComponentId::new(1673, 5);
    /// 1673:18, `kind=layer`
    pub const ITEM_SLOT_1: ComponentId = ComponentId::new(1673, 18);
    /// 1673:135, `kind=layer`
    pub const ITEM_SLOT_10: ComponentId = ComponentId::new(1673, 135);
    /// 1673:148, `kind=layer`
    pub const ITEM_SLOT_11: ComponentId = ComponentId::new(1673, 148);
    /// 1673:161, `kind=layer`
    pub const ITEM_SLOT_12: ComponentId = ComponentId::new(1673, 161);
    /// 1673:174, `kind=layer`
    pub const ITEM_SLOT_13: ComponentId = ComponentId::new(1673, 174);
    /// 1673:187, `kind=layer`
    pub const ITEM_SLOT_14: ComponentId = ComponentId::new(1673, 187);
    /// 1673:31, `kind=layer`
    pub const ITEM_SLOT_2: ComponentId = ComponentId::new(1673, 31);
    /// 1673:44, `kind=layer`
    pub const ITEM_SLOT_3: ComponentId = ComponentId::new(1673, 44);
    /// 1673:57, `kind=layer`
    pub const ITEM_SLOT_4: ComponentId = ComponentId::new(1673, 57);
    /// 1673:70, `kind=layer`
    pub const ITEM_SLOT_5: ComponentId = ComponentId::new(1673, 70);
    /// 1673:83, `kind=layer`
    pub const ITEM_SLOT_6: ComponentId = ComponentId::new(1673, 83);
    /// 1673:96, `kind=layer`
    pub const ITEM_SLOT_7: ComponentId = ComponentId::new(1673, 96);
    /// 1673:109, `kind=layer`
    pub const ITEM_SLOT_8: ComponentId = ComponentId::new(1673, 109);
    /// 1673:122, `kind=layer`
    pub const ITEM_SLOT_9: ComponentId = ComponentId::new(1673, 122);
    /// 1673:6, `kind=graphic`
    pub const SELECTOR: ComponentId = ComponentId::new(1673, 6);
    /// 1673:3, `kind=graphic`
    pub const SETTINGS: ComponentId = ComponentId::new(1673, 3);
    /// 1673:13, `kind=graphic`
    pub const SLOT_1: ComponentId = ComponentId::new(1673, 13);
    /// 1673:130, `kind=graphic`
    pub const SLOT_10: ComponentId = ComponentId::new(1673, 130);
    /// 1673:143, `kind=graphic`
    pub const SLOT_11: ComponentId = ComponentId::new(1673, 143);
    /// 1673:156, `kind=graphic`
    pub const SLOT_12: ComponentId = ComponentId::new(1673, 156);
    /// 1673:169, `kind=graphic`
    pub const SLOT_13: ComponentId = ComponentId::new(1673, 169);
    /// 1673:182, `kind=graphic`
    pub const SLOT_14: ComponentId = ComponentId::new(1673, 182);
    /// 1673:26, `kind=graphic`
    pub const SLOT_2: ComponentId = ComponentId::new(1673, 26);
    /// 1673:39, `kind=graphic`
    pub const SLOT_3: ComponentId = ComponentId::new(1673, 39);
    /// 1673:52, `kind=graphic`
    pub const SLOT_4: ComponentId = ComponentId::new(1673, 52);
    /// 1673:65, `kind=graphic`
    pub const SLOT_5: ComponentId = ComponentId::new(1673, 65);
    /// 1673:78, `kind=graphic`
    pub const SLOT_6: ComponentId = ComponentId::new(1673, 78);
    /// 1673:91, `kind=graphic`
    pub const SLOT_7: ComponentId = ComponentId::new(1673, 91);
    /// 1673:104, `kind=graphic`
    pub const SLOT_8: ComponentId = ComponentId::new(1673, 104);
    /// 1673:117, `kind=graphic`
    pub const SLOT_9: ComponentId = ComponentId::new(1673, 117);
}

pub mod action_bar_secondary {
    use crate::ComponentId;

    /// 1670:5, `kind=layer`
    pub const EXTRA_SELECTOR: ComponentId = ComponentId::new(1670, 5);
    /// 1670:23, `kind=layer`
    pub const ITEM_SLOT_1: ComponentId = ComponentId::new(1670, 23);
    /// 1670:140, `kind=layer`
    pub const ITEM_SLOT_10: ComponentId = ComponentId::new(1670, 140);
    /// 1670:153, `kind=layer`
    pub const ITEM_SLOT_11: ComponentId = ComponentId::new(1670, 153);
    /// 1670:166, `kind=layer`
    pub const ITEM_SLOT_12: ComponentId = ComponentId::new(1670, 166);
    /// 1670:179, `kind=layer`
    pub const ITEM_SLOT_13: ComponentId = ComponentId::new(1670, 179);
    /// 1670:192, `kind=layer`
    pub const ITEM_SLOT_14: ComponentId = ComponentId::new(1670, 192);
    /// 1670:36, `kind=layer`
    pub const ITEM_SLOT_2: ComponentId = ComponentId::new(1670, 36);
    /// 1670:49, `kind=layer`
    pub const ITEM_SLOT_3: ComponentId = ComponentId::new(1670, 49);
    /// 1670:62, `kind=layer`
    pub const ITEM_SLOT_4: ComponentId = ComponentId::new(1670, 62);
    /// 1670:75, `kind=layer`
    pub const ITEM_SLOT_5: ComponentId = ComponentId::new(1670, 75);
    /// 1670:88, `kind=layer`
    pub const ITEM_SLOT_6: ComponentId = ComponentId::new(1670, 88);
    /// 1670:101, `kind=layer`
    pub const ITEM_SLOT_7: ComponentId = ComponentId::new(1670, 101);
    /// 1670:114, `kind=layer`
    pub const ITEM_SLOT_8: ComponentId = ComponentId::new(1670, 114);
    /// 1670:127, `kind=layer`
    pub const ITEM_SLOT_9: ComponentId = ComponentId::new(1670, 127);
    /// 1670:12, `kind=graphic`
    pub const NEXT: ComponentId = ComponentId::new(1670, 12);
    /// 1670:11, `kind=graphic`
    pub const PREVIOUS: ComponentId = ComponentId::new(1670, 11);
    /// 1670:6, `kind=graphic`
    pub const SELECTOR: ComponentId = ComponentId::new(1670, 6);
    /// 1670:3, `kind=graphic`
    pub const SETTINGS: ComponentId = ComponentId::new(1670, 3);
    /// 1670:18, `kind=graphic`
    pub const SLOT_1: ComponentId = ComponentId::new(1670, 18);
    /// 1670:135, `kind=graphic`
    pub const SLOT_10: ComponentId = ComponentId::new(1670, 135);
    /// 1670:148, `kind=graphic`
    pub const SLOT_11: ComponentId = ComponentId::new(1670, 148);
    /// 1670:161, `kind=graphic`
    pub const SLOT_12: ComponentId = ComponentId::new(1670, 161);
    /// 1670:174, `kind=graphic`
    pub const SLOT_13: ComponentId = ComponentId::new(1670, 174);
    /// 1670:187, `kind=graphic`
    pub const SLOT_14: ComponentId = ComponentId::new(1670, 187);
    /// 1670:31, `kind=graphic`
    pub const SLOT_2: ComponentId = ComponentId::new(1670, 31);
    /// 1670:44, `kind=graphic`
    pub const SLOT_3: ComponentId = ComponentId::new(1670, 44);
    /// 1670:57, `kind=graphic`
    pub const SLOT_4: ComponentId = ComponentId::new(1670, 57);
    /// 1670:70, `kind=graphic`
    pub const SLOT_5: ComponentId = ComponentId::new(1670, 70);
    /// 1670:83, `kind=graphic`
    pub const SLOT_6: ComponentId = ComponentId::new(1670, 83);
    /// 1670:96, `kind=graphic`
    pub const SLOT_7: ComponentId = ComponentId::new(1670, 96);
    /// 1670:109, `kind=graphic`
    pub const SLOT_8: ComponentId = ComponentId::new(1670, 109);
    /// 1670:122, `kind=graphic`
    pub const SLOT_9: ComponentId = ComponentId::new(1670, 122);
}

pub mod action_bar_setup {
    use crate::ComponentId;

    /// 1436:5, `kind=graphic`
    pub const CLEAR: ComponentId = ComponentId::new(1436, 5);
    /// 1436:7, `kind=layer`
    pub const EXTRA_SELECTOR: ComponentId = ComponentId::new(1436, 7);
    /// 1436:22, `kind=layer`
    pub const ITEM_SLOT_1: ComponentId = ComponentId::new(1436, 22);
    /// 1436:139, `kind=layer`
    pub const ITEM_SLOT_10: ComponentId = ComponentId::new(1436, 139);
    /// 1436:152, `kind=layer`
    pub const ITEM_SLOT_11: ComponentId = ComponentId::new(1436, 152);
    /// 1436:165, `kind=layer`
    pub const ITEM_SLOT_12: ComponentId = ComponentId::new(1436, 165);
    /// 1436:178, `kind=layer`
    pub const ITEM_SLOT_13: ComponentId = ComponentId::new(1436, 178);
    /// 1436:191, `kind=layer`
    pub const ITEM_SLOT_14: ComponentId = ComponentId::new(1436, 191);
    /// 1436:35, `kind=layer`
    pub const ITEM_SLOT_2: ComponentId = ComponentId::new(1436, 35);
    /// 1436:48, `kind=layer`
    pub const ITEM_SLOT_3: ComponentId = ComponentId::new(1436, 48);
    /// 1436:61, `kind=layer`
    pub const ITEM_SLOT_4: ComponentId = ComponentId::new(1436, 61);
    /// 1436:74, `kind=layer`
    pub const ITEM_SLOT_5: ComponentId = ComponentId::new(1436, 74);
    /// 1436:87, `kind=layer`
    pub const ITEM_SLOT_6: ComponentId = ComponentId::new(1436, 87);
    /// 1436:100, `kind=layer`
    pub const ITEM_SLOT_7: ComponentId = ComponentId::new(1436, 100);
    /// 1436:113, `kind=layer`
    pub const ITEM_SLOT_8: ComponentId = ComponentId::new(1436, 113);
    /// 1436:126, `kind=layer`
    pub const ITEM_SLOT_9: ComponentId = ComponentId::new(1436, 126);
    /// 1436:11, `kind=graphic`
    pub const NEXT: ComponentId = ComponentId::new(1436, 11);
    /// 1436:10, `kind=graphic`
    pub const PREVIOUS: ComponentId = ComponentId::new(1436, 10);
    /// 1436:8, `kind=graphic`
    pub const SELECTOR: ComponentId = ComponentId::new(1436, 8);
    /// 1436:17, `kind=graphic`
    pub const SLOT_1: ComponentId = ComponentId::new(1436, 17);
    /// 1436:134, `kind=graphic`
    pub const SLOT_10: ComponentId = ComponentId::new(1436, 134);
    /// 1436:147, `kind=graphic`
    pub const SLOT_11: ComponentId = ComponentId::new(1436, 147);
    /// 1436:160, `kind=graphic`
    pub const SLOT_12: ComponentId = ComponentId::new(1436, 160);
    /// 1436:173, `kind=graphic`
    pub const SLOT_13: ComponentId = ComponentId::new(1436, 173);
    /// 1436:186, `kind=graphic`
    pub const SLOT_14: ComponentId = ComponentId::new(1436, 186);
    /// 1436:30, `kind=graphic`
    pub const SLOT_2: ComponentId = ComponentId::new(1436, 30);
    /// 1436:43, `kind=graphic`
    pub const SLOT_3: ComponentId = ComponentId::new(1436, 43);
    /// 1436:56, `kind=graphic`
    pub const SLOT_4: ComponentId = ComponentId::new(1436, 56);
    /// 1436:69, `kind=graphic`
    pub const SLOT_5: ComponentId = ComponentId::new(1436, 69);
    /// 1436:82, `kind=graphic`
    pub const SLOT_6: ComponentId = ComponentId::new(1436, 82);
    /// 1436:95, `kind=graphic`
    pub const SLOT_7: ComponentId = ComponentId::new(1436, 95);
    /// 1436:108, `kind=graphic`
    pub const SLOT_8: ComponentId = ComponentId::new(1436, 108);
    /// 1436:121, `kind=graphic`
    pub const SLOT_9: ComponentId = ComponentId::new(1436, 121);
}

pub mod action_bar_tertiary {
    use crate::ComponentId;

    /// 1671:5, `kind=layer`
    pub const EXTRA_SELECTOR: ComponentId = ComponentId::new(1671, 5);
    /// 1671:18, `kind=layer`
    pub const ITEM_SLOT_1: ComponentId = ComponentId::new(1671, 18);
    /// 1671:135, `kind=layer`
    pub const ITEM_SLOT_10: ComponentId = ComponentId::new(1671, 135);
    /// 1671:148, `kind=layer`
    pub const ITEM_SLOT_11: ComponentId = ComponentId::new(1671, 148);
    /// 1671:161, `kind=layer`
    pub const ITEM_SLOT_12: ComponentId = ComponentId::new(1671, 161);
    /// 1671:174, `kind=layer`
    pub const ITEM_SLOT_13: ComponentId = ComponentId::new(1671, 174);
    /// 1671:187, `kind=layer`
    pub const ITEM_SLOT_14: ComponentId = ComponentId::new(1671, 187);
    /// 1671:31, `kind=layer`
    pub const ITEM_SLOT_2: ComponentId = ComponentId::new(1671, 31);
    /// 1671:44, `kind=layer`
    pub const ITEM_SLOT_3: ComponentId = ComponentId::new(1671, 44);
    /// 1671:57, `kind=layer`
    pub const ITEM_SLOT_4: ComponentId = ComponentId::new(1671, 57);
    /// 1671:70, `kind=layer`
    pub const ITEM_SLOT_5: ComponentId = ComponentId::new(1671, 70);
    /// 1671:83, `kind=layer`
    pub const ITEM_SLOT_6: ComponentId = ComponentId::new(1671, 83);
    /// 1671:96, `kind=layer`
    pub const ITEM_SLOT_7: ComponentId = ComponentId::new(1671, 96);
    /// 1671:109, `kind=layer`
    pub const ITEM_SLOT_8: ComponentId = ComponentId::new(1671, 109);
    /// 1671:122, `kind=layer`
    pub const ITEM_SLOT_9: ComponentId = ComponentId::new(1671, 122);
    /// 1671:6, `kind=graphic`
    pub const SELECTOR: ComponentId = ComponentId::new(1671, 6);
    /// 1671:3, `kind=graphic`
    pub const SETTINGS: ComponentId = ComponentId::new(1671, 3);
    /// 1671:13, `kind=graphic`
    pub const SLOT_1: ComponentId = ComponentId::new(1671, 13);
    /// 1671:130, `kind=graphic`
    pub const SLOT_10: ComponentId = ComponentId::new(1671, 130);
    /// 1671:143, `kind=graphic`
    pub const SLOT_11: ComponentId = ComponentId::new(1671, 143);
    /// 1671:156, `kind=graphic`
    pub const SLOT_12: ComponentId = ComponentId::new(1671, 156);
    /// 1671:169, `kind=graphic`
    pub const SLOT_13: ComponentId = ComponentId::new(1671, 169);
    /// 1671:182, `kind=graphic`
    pub const SLOT_14: ComponentId = ComponentId::new(1671, 182);
    /// 1671:26, `kind=graphic`
    pub const SLOT_2: ComponentId = ComponentId::new(1671, 26);
    /// 1671:39, `kind=graphic`
    pub const SLOT_3: ComponentId = ComponentId::new(1671, 39);
    /// 1671:52, `kind=graphic`
    pub const SLOT_4: ComponentId = ComponentId::new(1671, 52);
    /// 1671:65, `kind=graphic`
    pub const SLOT_5: ComponentId = ComponentId::new(1671, 65);
    /// 1671:78, `kind=graphic`
    pub const SLOT_6: ComponentId = ComponentId::new(1671, 78);
    /// 1671:91, `kind=graphic`
    pub const SLOT_7: ComponentId = ComponentId::new(1671, 91);
    /// 1671:104, `kind=graphic`
    pub const SLOT_8: ComponentId = ComponentId::new(1671, 104);
    /// 1671:117, `kind=graphic`
    pub const SLOT_9: ComponentId = ComponentId::new(1671, 117);
}

pub mod audio_settings {
    use crate::ComponentId;

    /// 429:53, `kind=layer`
    pub const AMBIENT_MUTE: ComponentId = ComponentId::new(429, 53);
    /// 429:57, `kind=layer`
    pub const AMBIENT_VOLUME_TRACK: ComponentId = ComponentId::new(429, 57);
    /// 429:5, `kind=layer`
    pub const MASTER_MUTE: ComponentId = ComponentId::new(429, 5);
    /// 429:6, `kind=layer`
    pub const MASTER_MUTE_INNER: ComponentId = ComponentId::new(429, 6);
    /// 429:4, `kind=text`
    pub const MASTER_MUTE_LABEL: ComponentId = ComponentId::new(429, 4);
    /// 429:15, `kind=layer`
    pub const MUSIC_MUTE: ComponentId = ComponentId::new(429, 15);
    /// 429:19, `kind=layer`
    pub const MUSIC_VOLUME_TRACK: ComponentId = ComponentId::new(429, 19);
    /// 429:34, `kind=layer`
    pub const SOUND_EFFECTS_MUTE: ComponentId = ComponentId::new(429, 34);
    /// 429:38, `kind=layer`
    pub const SOUND_EFFECTS_VOLUME_TRACK: ComponentId = ComponentId::new(429, 38);
    /// 429:72, `kind=layer`
    pub const VOICE_MUTE: ComponentId = ComponentId::new(429, 72);
    /// 429:76, `kind=layer`
    pub const VOICE_VOLUME_TRACK: ComponentId = ComponentId::new(429, 76);
}

pub mod backpack {
    use crate::ComponentId;

    /// 1473:1, `kind=layer`
    pub const ACTION_BUTTONS: ComponentId = ComponentId::new(1473, 1);
    /// 1473:6, `kind=layer`
    pub const SLOT_BACKGROUNDS: ComponentId = ComponentId::new(1473, 6);
    /// 1473:7, `kind=layer`
    pub const SLOTS: ComponentId = ComponentId::new(1473, 7);
}

pub mod bank_window {
    use crate::ComponentId;

    /// 517:14, `kind=layer`
    pub const BACKPACK_SLOTS: ComponentId = ComponentId::new(517, 14);
    /// 517:108, `kind=text`
    pub const CHANGE_X: ComponentId = ComponentId::new(517, 108);
    /// 517:37, `kind=graphic`
    pub const DEPOSIT_CARRIED: ComponentId = ComponentId::new(517, 37);
    /// 517:46, `kind=graphic`
    pub const DEPOSIT_COIN_WALLET: ComponentId = ComponentId::new(517, 46);
    /// 517:40, `kind=graphic`
    pub const DEPOSIT_WORN: ComponentId = ComponentId::new(517, 40);
    /// 517:120, `kind=graphic`
    pub const NOTE_BUTTON: ComponentId = ComponentId::new(517, 120);
    /// 517:116, `kind=graphic`
    pub const PLACEHOLDER_BUTTON: ComponentId = ComponentId::new(517, 116);
    /// 517:97, `kind=layer`
    pub const QUANTITY_ALL: ComponentId = ComponentId::new(517, 97);
    /// 517:90, `kind=layer`
    pub const QUANTITY_FIVE: ComponentId = ComponentId::new(517, 90);
    /// 517:87, `kind=layer`
    pub const QUANTITY_ONE: ComponentId = ComponentId::new(517, 87);
    /// 517:93, `kind=layer`
    pub const QUANTITY_TEN: ComponentId = ComponentId::new(517, 93);
    /// 517:100, `kind=layer`
    pub const QUANTITY_X: ComponentId = ComponentId::new(517, 100);
    /// 517:147, `kind=layer`
    pub const RESET_TABS: ComponentId = ComponentId::new(517, 147);
    /// 517:184, `kind=layer`
    pub const SLOTS: ComponentId = ComponentId::new(517, 184);
    /// 517:151, `kind=layer`
    pub const TAB_STRIP: ComponentId = ComponentId::new(517, 151);
    /// 517:51, `kind=layer`
    pub const TO_BACKPACK: ComponentId = ComponentId::new(517, 51);
    /// 517:59, `kind=layer`
    pub const TO_BEAST_OF_BURDEN: ComponentId = ComponentId::new(517, 59);
    /// 517:55, `kind=layer`
    pub const TO_WORN: ComponentId = ComponentId::new(517, 55);
}

pub mod barrows_pattern_choices {
    use crate::ComponentId;

    /// 25:3, `kind=model`
    pub const ANSWER_FIRST: ComponentId = ComponentId::new(25, 3);
    /// 25:4, `kind=model`
    pub const ANSWER_SECOND: ComponentId = ComponentId::new(25, 4);
    /// 25:6, `kind=model`
    pub const ANSWER_THIRD: ComponentId = ComponentId::new(25, 6);
    /// 25:7, `kind=model`
    pub const SEQUENCE_FIRST: ComponentId = ComponentId::new(25, 7);
    /// 25:8, `kind=model`
    pub const SEQUENCE_SECOND: ComponentId = ComponentId::new(25, 8);
    /// 25:9, `kind=model`
    pub const SEQUENCE_THIRD: ComponentId = ComponentId::new(25, 9);
}

pub mod canoe_destinations {
    use crate::ComponentId;

    /// 53:3, `kind=text`
    pub const BARBARIAN_VILLAGE_BUTTON: ComponentId = ComponentId::new(53, 3);
    /// 53:23, `kind=layer`
    pub const BARBARIAN_VILLAGE_HERE: ComponentId = ComponentId::new(53, 23);
    /// 53:12, `kind=layer`
    pub const BARBARIAN_VILLAGE_STATION: ComponentId = ComponentId::new(53, 12);
    /// 53:45, `kind=text`
    pub const CHAMPIONS_GUILD_BUTTON: ComponentId = ComponentId::new(53, 45);
    /// 53:24, `kind=layer`
    pub const CHAMPIONS_GUILD_HERE: ComponentId = ComponentId::new(53, 24);
    /// 53:11, `kind=layer`
    pub const CHAMPIONS_GUILD_STATION: ComponentId = ComponentId::new(53, 11);
    /// 53:6, `kind=text`
    pub const EDGEVILLE_BUTTON: ComponentId = ComponentId::new(53, 6);
    /// 53:19, `kind=layer`
    pub const EDGEVILLE_HERE: ComponentId = ComponentId::new(53, 19);
    /// 53:20, `kind=layer`
    pub const EDGEVILLE_STATION: ComponentId = ComponentId::new(53, 20);
    /// 53:44, `kind=text`
    pub const LUMBRIDGE_BUTTON: ComponentId = ComponentId::new(53, 44);
    /// 53:25, `kind=layer`
    pub const LUMBRIDGE_HERE: ComponentId = ComponentId::new(53, 25);
    /// 53:10, `kind=layer`
    pub const LUMBRIDGE_STATION: ComponentId = ComponentId::new(53, 10);
    /// 53:46, `kind=text`
    pub const WILDERNESS_BUTTON: ComponentId = ComponentId::new(53, 46);
    /// 53:18, `kind=layer`
    pub const WILDERNESS_STATION: ComponentId = ComponentId::new(53, 18);
}

pub mod canoe_shaping {
    use crate::ComponentId;

    /// 52:31, `kind=text`
    pub const DUGOUT_BUTTON: ComponentId = ComponentId::new(52, 31);
    /// 52:4, `kind=layer`
    pub const DUGOUT_CHOICE: ComponentId = ComponentId::new(52, 4);
    /// 52:9, `kind=layer`
    pub const DUGOUT_LOCKED: ComponentId = ComponentId::new(52, 9);
    /// 52:30, `kind=text`
    pub const LOG_BUTTON: ComponentId = ComponentId::new(52, 30);
    /// 52:32, `kind=text`
    pub const STABLE_DUGOUT_BUTTON: ComponentId = ComponentId::new(52, 32);
    /// 52:3, `kind=layer`
    pub const STABLE_DUGOUT_CHOICE: ComponentId = ComponentId::new(52, 3);
    /// 52:10, `kind=layer`
    pub const STABLE_DUGOUT_LOCKED: ComponentId = ComponentId::new(52, 10);
    /// 52:33, `kind=text`
    pub const WAKA_BUTTON: ComponentId = ComponentId::new(52, 33);
    /// 52:6, `kind=layer`
    pub const WAKA_CHOICE: ComponentId = ComponentId::new(52, 6);
    /// 52:8, `kind=layer`
    pub const WAKA_LOCKED: ComponentId = ComponentId::new(52, 8);
}

pub mod charter_map {
    use crate::ComponentId;

    /// 95:28, `kind=layer`
    pub const BRIMHAVEN_BUTTON: ComponentId = ComponentId::new(95, 28);
    /// 95:25, `kind=layer`
    pub const CATHERBY_BUTTON: ComponentId = ComponentId::new(95, 25);
    /// 95:35, `kind=graphic`
    pub const CLOSE_MAP_BUTTON: ComponentId = ComponentId::new(95, 35);
    /// 95:32, `kind=layer`
    pub const CRANDOR_BUTTON: ComponentId = ComponentId::new(95, 32);
    /// 95:34, `kind=layer`
    pub const MENAPHOS_BUTTON: ComponentId = ComponentId::new(95, 34);
    /// 95:31, `kind=layer`
    pub const MOS_LE_HARMLESS_BUTTON: ComponentId = ComponentId::new(95, 31);
    /// 95:27, `kind=layer`
    pub const MUSA_POINT_BUTTON: ComponentId = ComponentId::new(95, 27);
    /// 95:33, `kind=layer`
    pub const OOGLOG_BUTTON: ComponentId = ComponentId::new(95, 33);
    /// 95:29, `kind=layer`
    pub const PORT_KHAZARD_BUTTON: ComponentId = ComponentId::new(95, 29);
    /// 95:24, `kind=layer`
    pub const PORT_PHASMATYS_BUTTON: ComponentId = ComponentId::new(95, 24);
    /// 95:30, `kind=layer`
    pub const PORT_SARIM_BUTTON: ComponentId = ComponentId::new(95, 30);
    /// 95:23, `kind=layer`
    pub const PORT_TYRAS_BUTTON: ComponentId = ComponentId::new(95, 23);
    /// 95:26, `kind=layer`
    pub const SHIPYARD_BUTTON: ComponentId = ComponentId::new(95, 26);
}

pub mod clue_reward_window {
    use crate::ComponentId;

    /// 364:30, `kind=layer`
    pub const CLOSE_BUTTON: ComponentId = ComponentId::new(364, 30);
    /// 364:1, `kind=layer`
    pub const ITEMS: ComponentId = ComponentId::new(364, 1);
    /// 364:2, `kind=layer`
    pub const REROLL_BUTTON: ComponentId = ComponentId::new(364, 2);
    /// 364:15, `kind=text`
    pub const REROLLS_LINE: ComponentId = ComponentId::new(364, 15);
    /// 364:16, `kind=text`
    pub const VALUE_LINE: ComponentId = ComponentId::new(364, 16);
}

pub mod clue_scroll {
    use crate::ComponentId;

    /// 345:1, `kind=text`
    pub const FIRST_LINE: ComponentId = ComponentId::new(345, 1);
}

pub mod confirm_popup {
    use crate::ComponentId;

    /// 1476:10, `kind=layer`
    pub const CONFIRM_BUTTON: ComponentId = ComponentId::new(1476, 10);
}

pub mod controls_settings {
    use crate::ComponentId;

    /// 1444:375, `kind=layer`
    pub const ACTION_BAR_KEYBIND: ComponentId = ComponentId::new(1444, 375);
    /// 1444:26, `kind=layer`
    pub const CAMERA_DOWN_KEYBIND: ComponentId = ComponentId::new(1444, 26);
    /// 1444:37, `kind=layer`
    pub const CAMERA_LEFT_KEYBIND: ComponentId = ComponentId::new(1444, 37);
    /// 1444:48, `kind=layer`
    pub const CAMERA_RIGHT_KEYBIND: ComponentId = ComponentId::new(1444, 48);
    /// 1444:15, `kind=layer`
    pub const CAMERA_UP_KEYBIND: ComponentId = ComponentId::new(1444, 15);
    /// 1444:283, `kind=layer`
    pub const CHAT_KEYBIND: ComponentId = ComponentId::new(1444, 283);
    /// 1444:885, `kind=layer`
    pub const COMBAT_KEYBIND: ComponentId = ComponentId::new(1444, 885);
    /// 1444:958, `kind=layer`
    pub const GLOBAL_MUTE_KEYBIND: ComponentId = ComponentId::new(1444, 958);
    /// 1444:133, `kind=layer`
    pub const HOME_TELEPORT_KEYBIND: ComponentId = ComponentId::new(1444, 133);
    /// 1444:145, `kind=layer`
    pub const INTERFACE_TABS_KEYBIND: ComponentId = ComponentId::new(1444, 145);
    /// 1444:115, `kind=layer`
    pub const LOCK_INTERFACE_KEYBIND: ComponentId = ComponentId::new(1444, 115);
    /// 1444:964, `kind=layer`
    pub const MUSIC_MUTE_KEYBIND: ComponentId = ComponentId::new(1444, 964);
    /// 1444:990, `kind=layer`
    pub const RESET_KEYBINDS_BUTTON: ComponentId = ComponentId::new(1444, 990);
    /// 1444:121, `kind=layer`
    pub const TOGGLE_RUN_KEYBIND: ComponentId = ComponentId::new(1444, 121);
    /// 1444:73, `kind=layer`
    pub const WINDOWS_NAVIGATION_KEYBIND: ComponentId = ComponentId::new(1444, 73);
    /// 1444:127, `kind=layer`
    pub const WORLD_MAP_KEYBIND: ComponentId = ComponentId::new(1444, 127);
}

pub mod death_reclaim {
    use crate::ComponentId;

    /// 1626:46, `kind=layer`
    pub const CLOSE: ComponentId = ComponentId::new(1626, 46);
    /// 1626:50, `kind=layer`
    pub const CONFIRM: ComponentId = ComponentId::new(1626, 50);
    /// 1626:7, `kind=layer`
    pub const LOST_ITEMS: ComponentId = ComponentId::new(1626, 7);
    /// 1626:19, `kind=layer`
    pub const PROTECTED_ITEMS: ComponentId = ComponentId::new(1626, 19);
    /// 1626:55, `kind=layer`
    pub const SAVED_ITEMS: ComponentId = ComponentId::new(1626, 55);
}

pub mod defensive_book {
    use crate::ComponentId;

    /// 1880:1, `kind=layer`
    pub const ABILITIES: ComponentId = ComponentId::new(1880, 1);
    /// 1880:7, `kind=layer`
    pub const TABS: ComponentId = ComponentId::new(1880, 7);
}

pub mod dialogue_frame {
    use crate::ComponentId;

    /// 1418:2, `kind=layer`
    pub const ENTRY_SLOT: ComponentId = ComponentId::new(1418, 2);
}

pub mod dialogue_options {
    use crate::ComponentId;

    /// 1188:8, `kind=layer`
    pub const FIRST_OPTION: ComponentId = ComponentId::new(1188, 8);
}

pub mod emotes {
    use crate::ComponentId;

    /// 590:8, `kind=layer`
    pub const LIST: ComponentId = ComponentId::new(590, 8);
}

pub mod encounter_setup {
    use crate::ComponentId;

    /// 1591:55, `kind=layer`
    pub const CLOSE: ComponentId = ComponentId::new(1591, 55);
    /// 1591:28, `kind=graphic`
    pub const COMBAT_DOWN: ComponentId = ComponentId::new(1591, 28);
    /// 1591:81, `kind=layer`
    pub const COMBAT_ENTRY: ComponentId = ComponentId::new(1591, 81);
    /// 1591:29, `kind=graphic`
    pub const COMBAT_UP: ComponentId = ComponentId::new(1591, 29);
    /// 1591:4, `kind=layer`
    pub const HARD_TOGGLE: ComponentId = ComponentId::new(1591, 4);
    /// 1591:108, `kind=layer`
    pub const JOIN: ComponentId = ComponentId::new(1591, 108);
    /// 1591:24, `kind=graphic`
    pub const LIMIT_DOWN: ComponentId = ComponentId::new(1591, 24);
    /// 1591:72, `kind=layer`
    pub const LIMIT_ENTRY: ComponentId = ComponentId::new(1591, 72);
    /// 1591:25, `kind=graphic`
    pub const LIMIT_UP: ComponentId = ComponentId::new(1591, 25);
    /// 1591:75, `kind=text`
    pub const LIMIT_VALUE: ComponentId = ComponentId::new(1591, 75);
    /// 1591:113, `kind=layer`
    pub const PRACTICE_TOGGLE: ComponentId = ComponentId::new(1591, 113);
    /// 1591:36, `kind=graphic`
    pub const PROTECTION_DOWN: ComponentId = ComponentId::new(1591, 36);
    /// 1591:100, `kind=layer`
    pub const PROTECTION_ENTRY: ComponentId = ComponentId::new(1591, 100);
    /// 1591:37, `kind=graphic`
    pub const PROTECTION_UP: ComponentId = ComponentId::new(1591, 37);
    /// 1591:122, `kind=layer`
    pub const REJOIN: ComponentId = ComponentId::new(1591, 122);
    /// 1591:32, `kind=graphic`
    pub const SPEED_DOWN: ComponentId = ComponentId::new(1591, 32);
    /// 1591:92, `kind=layer`
    pub const SPEED_ENTRY: ComponentId = ComponentId::new(1591, 92);
    /// 1591:33, `kind=graphic`
    pub const SPEED_UP: ComponentId = ComponentId::new(1591, 33);
    /// 1591:60, `kind=layer`
    pub const START: ComponentId = ComponentId::new(1591, 60);
}

pub mod exchange {
    use crate::ComponentId;

    /// 105:279, `kind=graphic`
    pub const ABORT: ComponentId = ComponentId::new(105, 279);
    /// 105:171, `kind=graphic`
    pub const BACK: ComponentId = ComponentId::new(105, 171);
    /// 105:31, `kind=layer`
    pub const BUY_SLOT_0: ComponentId = ComponentId::new(105, 31);
    /// 105:46, `kind=layer`
    pub const BUY_SLOT_1: ComponentId = ComponentId::new(105, 46);
    /// 105:61, `kind=layer`
    pub const BUY_SLOT_2: ComponentId = ComponentId::new(105, 61);
    /// 105:76, `kind=layer`
    pub const BUY_SLOT_3: ComponentId = ComponentId::new(105, 76);
    /// 105:94, `kind=layer`
    pub const BUY_SLOT_4: ComponentId = ComponentId::new(105, 94);
    /// 105:112, `kind=layer`
    pub const BUY_SLOT_5: ComponentId = ComponentId::new(105, 112);
    /// 105:130, `kind=layer`
    pub const BUY_SLOT_6: ComponentId = ComponentId::new(105, 130);
    /// 105:148, `kind=layer`
    pub const BUY_SLOT_7: ComponentId = ComponentId::new(105, 148);
    /// 105:284, `kind=graphic`
    pub const COLLECT_COINS: ComponentId = ComponentId::new(105, 284);
    /// 105:282, `kind=graphic`
    pub const COLLECT_ITEM: ComponentId = ComponentId::new(105, 282);
    /// 105:280, `kind=graphic`
    pub const COLLECT_REPEAT: ComponentId = ComponentId::new(105, 280);
    /// 105:302, `kind=layer`
    pub const CONFIRM: ComponentId = ComponentId::new(105, 302);
    /// 105:1, `kind=layer`
    pub const OFFER_HOOKS: ComponentId = ComponentId::new(105, 1);
    /// 105:247, `kind=graphic`
    pub const PRICE_DOWN: ComponentId = ComponentId::new(105, 247);
    /// 105:259, `kind=layer`
    pub const PRICE_GUIDE: ComponentId = ComponentId::new(105, 259);
    /// 105:243, `kind=text`
    pub const PRICE_INPUT: ComponentId = ComponentId::new(105, 243);
    /// 105:252, `kind=layer`
    pub const PRICE_LESS: ComponentId = ComponentId::new(105, 252);
    /// 105:265, `kind=layer`
    pub const PRICE_MORE: ComponentId = ComponentId::new(105, 265);
    /// 105:246, `kind=graphic`
    pub const PRICE_UP: ComponentId = ComponentId::new(105, 246);
    /// 105:277, `kind=text`
    pub const PROGRESS_TEXT: ComponentId = ComponentId::new(105, 277);
    /// 105:233, `kind=layer`
    pub const QUANTITY_ALL: ComponentId = ComponentId::new(105, 233);
    /// 105:207, `kind=graphic`
    pub const QUANTITY_DOWN: ComponentId = ComponentId::new(105, 207);
    /// 105:226, `kind=layer`
    pub const QUANTITY_HUNDRED: ComponentId = ComponentId::new(105, 226);
    /// 105:203, `kind=text`
    pub const QUANTITY_INPUT: ComponentId = ComponentId::new(105, 203);
    /// 105:212, `kind=layer`
    pub const QUANTITY_ONE: ComponentId = ComponentId::new(105, 212);
    /// 105:219, `kind=layer`
    pub const QUANTITY_TEN: ComponentId = ComponentId::new(105, 219);
    /// 105:206, `kind=graphic`
    pub const QUANTITY_UP: ComponentId = ComponentId::new(105, 206);
    /// 105:37, `kind=layer`
    pub const SELL_SLOT_0: ComponentId = ComponentId::new(105, 37);
    /// 105:52, `kind=layer`
    pub const SELL_SLOT_1: ComponentId = ComponentId::new(105, 52);
    /// 105:67, `kind=layer`
    pub const SELL_SLOT_2: ComponentId = ComponentId::new(105, 67);
    /// 105:82, `kind=layer`
    pub const SELL_SLOT_3: ComponentId = ComponentId::new(105, 82);
    /// 105:100, `kind=layer`
    pub const SELL_SLOT_4: ComponentId = ComponentId::new(105, 100);
    /// 105:118, `kind=layer`
    pub const SELL_SLOT_5: ComponentId = ComponentId::new(105, 118);
    /// 105:136, `kind=layer`
    pub const SELL_SLOT_6: ComponentId = ComponentId::new(105, 136);
    /// 105:154, `kind=layer`
    pub const SELL_SLOT_7: ComponentId = ComponentId::new(105, 154);
    /// 105:0, `kind=layer`
    pub const STOCK_HOOKS: ComponentId = ComponentId::new(105, 0);
    /// 105:296, `kind=layer`
    pub const WARNING_DISMISS: ComponentId = ComponentId::new(105, 296);
}

pub mod exchange_collect_all {
    use crate::ComponentId;

    /// 651:6, `kind=layer`
    pub const TO_BACKPACK: ComponentId = ComponentId::new(651, 6);
    /// 651:14, `kind=layer`
    pub const TO_BANK: ComponentId = ComponentId::new(651, 14);
}

pub mod exchange_collection_box {
    use crate::ComponentId;

    /// 109:55, `kind=layer`
    pub const TO_BACKPACK: ComponentId = ComponentId::new(109, 55);
    /// 109:47, `kind=layer`
    pub const TO_BANK: ComponentId = ComponentId::new(109, 47);
}

pub mod exchange_side {
    use crate::ComponentId;

    /// 107:7, `kind=layer`
    pub const ITEMS: ComponentId = ComponentId::new(107, 7);
}

pub mod fairy_ring_window {
    use crate::ComponentId;

    /// 734:120, `kind=layer`
    pub const ALTERNATE_TELEPORT_BUTTON: ComponentId = ComponentId::new(734, 120);
    /// 734:114, `kind=layer`
    pub const CLOSE_BUTTON: ComponentId = ComponentId::new(734, 114);
    /// 734:85, `kind=layer`
    pub const DIAL_1_ANTICLOCKWISE: ComponentId = ComponentId::new(734, 85);
    /// 734:84, `kind=layer`
    pub const DIAL_1_CLOCKWISE: ComponentId = ComponentId::new(734, 84);
    /// 734:87, `kind=layer`
    pub const DIAL_2_ANTICLOCKWISE: ComponentId = ComponentId::new(734, 87);
    /// 734:86, `kind=layer`
    pub const DIAL_2_CLOCKWISE: ComponentId = ComponentId::new(734, 86);
    /// 734:89, `kind=layer`
    pub const DIAL_3_ANTICLOCKWISE: ComponentId = ComponentId::new(734, 89);
    /// 734:88, `kind=layer`
    pub const DIAL_3_CLOCKWISE: ComponentId = ComponentId::new(734, 88);
    /// 734:119, `kind=layer`
    pub const TELEPORT_BUTTON: ComponentId = ComponentId::new(734, 119);
}

pub mod found_document {
    use crate::ComponentId;

    /// 101:3, `kind=graphic`
    pub const PAGE: ComponentId = ComponentId::new(101, 3);
}

pub mod friends_chat {
    use crate::ComponentId;

    /// 1109:13, `kind=layer`
    pub const JOIN_BUTTON: ComponentId = ComponentId::new(1109, 13);
}

pub mod furniture_creation {
    use crate::ComponentId;

    /// 1306:6, `kind=layer`
    pub const OPTION_1: ComponentId = ComponentId::new(1306, 6);
    /// 1306:13, `kind=layer`
    pub const OPTION_2: ComponentId = ComponentId::new(1306, 13);
    /// 1306:20, `kind=layer`
    pub const OPTION_3: ComponentId = ComponentId::new(1306, 20);
    /// 1306:27, `kind=layer`
    pub const OPTION_4: ComponentId = ComponentId::new(1306, 27);
    /// 1306:34, `kind=layer`
    pub const OPTION_5: ComponentId = ComponentId::new(1306, 34);
    /// 1306:41, `kind=layer`
    pub const OPTION_6: ComponentId = ComponentId::new(1306, 41);
    /// 1306:48, `kind=layer`
    pub const OPTION_7: ComponentId = ComponentId::new(1306, 48);
}

pub mod game_window {
    use crate::ComponentId;

    /// 1477:17, `kind=rectangle`
    pub const ACTION_BAR_DISCARD_BACKGROUND: ComponentId = ComponentId::new(1477, 17);
    /// 1477:18, `kind=layer`
    pub const ACTION_BAR_DISCARD_SCENE: ComponentId = ComponentId::new(1477, 18);
    /// 1477:75, `kind=layer`
    pub const ACTION_BAR_QUATERNARY_SLOT: ComponentId = ComponentId::new(1477, 75);
    /// 1477:80, `kind=layer`
    pub const ACTION_BAR_QUINARY_SLOT: ComponentId = ComponentId::new(1477, 80);
    /// 1477:65, `kind=layer`
    pub const ACTION_BAR_SECONDARY_SLOT: ComponentId = ComponentId::new(1477, 65);
    /// 1477:60, `kind=layer`
    pub const ACTION_BAR_SLOT: ComponentId = ComponentId::new(1477, 60);
    /// 1477:70, `kind=layer`
    pub const ACTION_BAR_TERTIARY_SLOT: ComponentId = ComponentId::new(1477, 70);
    /// 1477:104, `kind=layer`
    pub const BACKPACK_SLOT: ComponentId = ComponentId::new(1477, 104);
    /// 1477:637, `kind=layer`
    pub const BANK_SLOT: ComponentId = ComponentId::new(1477, 637);
    /// 1477:32, `kind=layer`
    pub const CAMERA_KEY_LAYER: ComponentId = ComponentId::new(1477, 32);
    /// 1477:668, `kind=layer`
    pub const CENTRAL_LARGE_SLOT: ComponentId = ComponentId::new(1477, 668);
    /// 1477:677, `kind=layer`
    pub const CENTRAL_SLOT: ComponentId = ComponentId::new(1477, 677);
    /// 1477:115, `kind=layer`
    pub const CHAT_PANEL_1_SLOT: ComponentId = ComponentId::new(1477, 115);
    /// 1477:126, `kind=layer`
    pub const CHAT_PANEL_2_SLOT: ComponentId = ComponentId::new(1477, 126);
    /// 1477:136, `kind=layer`
    pub const CHAT_PANEL_3_SLOT: ComponentId = ComponentId::new(1477, 136);
    /// 1477:146, `kind=layer`
    pub const CHAT_PANEL_4_SLOT: ComponentId = ComponentId::new(1477, 146);
    /// 1477:156, `kind=layer`
    pub const CHAT_PANEL_5_SLOT: ComponentId = ComponentId::new(1477, 156);
    /// 1477:166, `kind=layer`
    pub const CHAT_PANEL_6_SLOT: ComponentId = ComponentId::new(1477, 166);
    /// 1477:176, `kind=layer`
    pub const CHAT_PANEL_8_SLOT: ComponentId = ComponentId::new(1477, 176);
    /// 1477:394, `kind=layer`
    pub const CLAN_CHAT_SLOT: ComponentId = ComponentId::new(1477, 394);
    /// 1477:610, `kind=layer`
    pub const CLOCK_SLOT: ComponentId = ComponentId::new(1477, 610);
    /// 1477:86, `kind=layer`
    pub const COMPASS_SLOT: ComponentId = ComponentId::new(1477, 86);
    /// 1477:318, `kind=layer`
    pub const DEFENSIVE_SLOT: ComponentId = ComponentId::new(1477, 318);
    /// 1477:690, `kind=layer`
    pub const DIALOGUE_SLOT: ComponentId = ComponentId::new(1477, 690);
    /// 1477:828, `kind=layer`
    pub const DROPDOWN_LIST: ComponentId = ComponentId::new(1477, 828);
    /// 1477:829, `kind=layer`
    pub const DROPDOWN_LIST_OPTIONS: ComponentId = ComponentId::new(1477, 829);
    /// 1477:93, `kind=layer`
    pub const EMOTES_SLOT: ComponentId = ComponentId::new(1477, 93);
    /// 1477:812, `kind=layer`
    pub const EXPERIENCE_DROPS_SLOT: ComponentId = ComponentId::new(1477, 812);
    /// 1477:383, `kind=layer`
    pub const FRIENDS_CHAT_SETTINGS_SLOT: ComponentId = ComponentId::new(1477, 383);
    /// 1477:427, `kind=layer`
    pub const FRIENDS_CHAT_SLOT: ComponentId = ComponentId::new(1477, 427);
    /// 1477:621, `kind=layer`
    pub const GRAVE_TIMER_SLOT: ComponentId = ComponentId::new(1477, 621);
    /// 1477:55, `kind=layer`
    pub const LAYOUT_LOCK_BUTTON: ComponentId = ComponentId::new(1477, 55);
    /// 1477:34, `kind=layer`
    pub const LEVELUP_SLOT: ComponentId = ComponentId::new(1477, 34);
    /// 1477:263, `kind=layer`
    pub const MAGIC_SLOT: ComponentId = ComponentId::new(1477, 263);
    /// 1477:219, `kind=layer`
    pub const MELEE_SLOT: ComponentId = ComponentId::new(1477, 219);
    /// 1477:85, `kind=layer`
    pub const MINIMAP_SLOT: ComponentId = ComponentId::new(1477, 85);
    /// 1477:659, `kind=layer`
    pub const MODAL_CLOSE_BUTTON: ComponentId = ComponentId::new(1477, 659);
    /// 1477:657, `kind=layer`
    pub const MODAL_FRAME_SLOT: ComponentId = ComponentId::new(1477, 657);
    /// 1477:656, `kind=layer`
    pub const MODAL_TAB_LABELS: ComponentId = ComponentId::new(1477, 656);
    /// 1477:650, `kind=layer`
    pub const MODAL_WINDOW: ComponentId = ComponentId::new(1477, 650);
    /// 1477:4, `kind=layer`
    pub const OPTIONS_BUTTON: ComponentId = ComponentId::new(1477, 4);
    /// 1477:734, `kind=layer`
    pub const OPTIONS_MENU_LAYER: ComponentId = ComponentId::new(1477, 734);
    /// 1477:738, `kind=layer`
    pub const OPTIONS_MENU_SLOT: ComponentId = ComponentId::new(1477, 738);
    /// 1477:208, `kind=layer`
    pub const PRAYER_SLOT: ComponentId = ComponentId::new(1477, 208);
    /// 1477:492, `kind=layer`
    pub const QUEST_LIST_SLOT: ComponentId = ComponentId::new(1477, 492);
    /// 1477:252, `kind=layer`
    pub const RANGED_SLOT: ComponentId = ComponentId::new(1477, 252);
    /// 1477:676, `kind=layer`
    pub const SLAYER_COUNTER_SLOT: ComponentId = ComponentId::new(1477, 676);
    /// 1477:567, `kind=layer`
    pub const STATUS_BUFFS_SLOT: ComponentId = ComponentId::new(1477, 567);
    /// 1477:563, `kind=layer`
    pub const STATUS_DEBUFFS_SLOT: ComponentId = ComponentId::new(1477, 563);
    /// 1477:590, `kind=layer`
    pub const WILDERNESS_HUD_SLOT: ComponentId = ComponentId::new(1477, 590);
    /// 1477:54, `kind=layer`
    pub const WINDOW_BUTTONS_SLOT: ComponentId = ComponentId::new(1477, 54);
    /// 1477:23, `kind=layer`
    pub const WORLD_MAP_CONTROLS_SLOT: ComponentId = ComponentId::new(1477, 23);
    /// 1477:19, `kind=layer`
    pub const WORLD_VIEW_LAYER: ComponentId = ComponentId::new(1477, 19);
    /// 1477:22, `kind=layer`
    pub const WORLD_VIEW_SLOT: ComponentId = ComponentId::new(1477, 22);
    /// 1477:186, `kind=layer`
    pub const WORN_EQUIPMENT_SLOT: ComponentId = ComponentId::new(1477, 186);
}

pub mod gameplay_settings {
    use crate::ComponentId;

    /// 365:11, `kind=layer`
    pub const CATEGORIES: ComponentId = ComponentId::new(365, 11);
    /// 365:16, `kind=layer`
    pub const OPTIONS: ComponentId = ComponentId::new(365, 16);
    /// 365:15, `kind=layer`
    pub const OPTIONS_FRAME: ComponentId = ComponentId::new(365, 15);
    /// 365:17, `kind=layer`
    pub const SLIDER_VALUES: ComponentId = ComponentId::new(365, 17);
}

pub mod glider_map {
    use crate::ComponentId;

    /// 138:34, `kind=layer`
    pub const CLOSE_BUTTON: ComponentId = ComponentId::new(138, 34);
    /// 138:96, `kind=layer`
    pub const DYLANDRA_BUTTON: ComponentId = ComponentId::new(138, 96);
    /// 138:64, `kind=layer`
    pub const GANDIUS_BUTTON: ComponentId = ComponentId::new(138, 64);
    /// 138:104, `kind=layer`
    pub const KAI_UNDRI_BUTTON: ComponentId = ComponentId::new(138, 104);
    /// 138:88, `kind=layer`
    pub const KAR_HEWO_BUTTON: ComponentId = ComponentId::new(138, 88);
    /// 138:80, `kind=layer`
    pub const LEMANTO_ANDRA_BUTTON: ComponentId = ComponentId::new(138, 80);
    /// 138:56, `kind=layer`
    pub const LEMANTOLLY_UNDRI_BUTTON: ComponentId = ComponentId::new(138, 56);
    /// 138:48, `kind=layer`
    pub const PRIW_GNOMO_ANDRALO_BUTTON: ComponentId = ComponentId::new(138, 48);
    /// 138:72, `kind=layer`
    pub const SINDARPOS_BUTTON: ComponentId = ComponentId::new(138, 72);
    /// 138:40, `kind=layer`
    pub const TA_QUIR_PRIW_BUTTON: ComponentId = ComponentId::new(138, 40);
}

pub mod graphics_change_confirm {
    use crate::ComponentId;

    /// 883:23, `kind=layer`
    pub const NO_BUTTON: ComponentId = ComponentId::new(883, 23);
    /// 883:14, `kind=layer`
    pub const YES_BUTTON: ComponentId = ComponentId::new(883, 14);
}

pub mod graphics_settings_loader {
    use crate::ComponentId;

    /// 1426:0, `kind=layer`
    pub const CONTENT_SLOT: ComponentId = ComponentId::new(1426, 0);
}

pub mod graphics_settings_panel {
    use crate::ComponentId;

    /// 1513:80, `kind=layer`
    pub const AUTO_SETUP_BUTTON: ComponentId = ComponentId::new(1513, 80);
    /// 1513:72, `kind=layer`
    pub const BRIGHTNESS_TRACK_LEFT: ComponentId = ComponentId::new(1513, 72);
    /// 1513:73, `kind=layer`
    pub const BRIGHTNESS_TRACK_RIGHT: ComponentId = ComponentId::new(1513, 73);
    /// 1513:155, `kind=layer`
    pub const CONTROL_LIST: ComponentId = ComponentId::new(1513, 155);
    /// 1513:120, `kind=layer`
    pub const CUSTOM_PRESET_BUTTON: ComponentId = ComponentId::new(1513, 120);
    /// 1513:123, `kind=text`
    pub const CUSTOM_PRESET_LABEL: ComponentId = ComponentId::new(1513, 123);
    /// 1513:138, `kind=layer`
    pub const FULLSCREEN_BUTTON: ComponentId = ComponentId::new(1513, 138);
    /// 1513:112, `kind=layer`
    pub const HIGH_PRESET_BUTTON: ComponentId = ComponentId::new(1513, 112);
    /// 1513:96, `kind=layer`
    pub const LOW_PRESET_BUTTON: ComponentId = ComponentId::new(1513, 96);
    /// 1513:104, `kind=layer`
    pub const MEDIUM_PRESET_BUTTON: ComponentId = ComponentId::new(1513, 104);
    /// 1513:88, `kind=layer`
    pub const MIN_PRESET_BUTTON: ComponentId = ComponentId::new(1513, 88);
    /// 1513:91, `kind=text`
    pub const MIN_PRESET_LABEL: ComponentId = ComponentId::new(1513, 91);
    /// 1513:22, `kind=layer`
    pub const RESOLUTION_DROPDOWN: ComponentId = ComponentId::new(1513, 22);
    /// 1513:128, `kind=layer`
    pub const WINDOWED_BUTTON: ComponentId = ComponentId::new(1513, 128);
}

pub mod grave_recovery {
    use crate::ComponentId;

    /// 636:8, `kind=layer`
    pub const ITEM_SLOTS: ComponentId = ComponentId::new(636, 8);
    /// 636:11, `kind=layer`
    pub const RECLAIM_ALL: ComponentId = ComponentId::new(636, 11);
}

pub mod hero_loadout_backpack {
    use crate::ComponentId;

    /// 1474:8, `kind=layer`
    pub const SLOTS: ComponentId = ComponentId::new(1474, 8);
}

pub mod hero_loadout_stats {
    use crate::ComponentId;

    /// 1463:201, `kind=layer`
    pub const ABILITIES_TAB: ComponentId = ComponentId::new(1463, 201);
    /// 1463:212, `kind=text`
    pub const ABILITY_DAMAGE: ComponentId = ComponentId::new(1463, 212);
    /// 1463:195, `kind=text`
    pub const ARMOUR: ComponentId = ComponentId::new(1463, 195);
    /// 1463:24, `kind=text`
    pub const HEALTH: ComponentId = ComponentId::new(1463, 24);
    /// 1463:50, `kind=text`
    pub const MAIN_HAND_ACCURACY: ComponentId = ComponentId::new(1463, 50);
    /// 1463:45, `kind=text`
    pub const MAIN_HAND_DAMAGE: ComponentId = ComponentId::new(1463, 45);
    /// 1463:38, `kind=layer`
    pub const MAIN_HAND_DETAILS: ComponentId = ComponentId::new(1463, 38);
    /// 1463:166, `kind=layer`
    pub const MAIN_HAND_TAB: ComponentId = ComponentId::new(1463, 166);
    /// 1463:72, `kind=text`
    pub const OFF_HAND_ACCURACY: ComponentId = ComponentId::new(1463, 72);
    /// 1463:67, `kind=text`
    pub const OFF_HAND_DAMAGE: ComponentId = ComponentId::new(1463, 67);
    /// 1463:60, `kind=layer`
    pub const OFF_HAND_DETAILS: ComponentId = ComponentId::new(1463, 60);
    /// 1463:174, `kind=layer`
    pub const OFF_HAND_TAB: ComponentId = ComponentId::new(1463, 174);
    /// 1463:175, `kind=layer`
    pub const OFF_HAND_UNAVAILABLE: ComponentId = ComponentId::new(1463, 175);
    /// 1463:21, `kind=text`
    pub const PLAYER_NAME: ComponentId = ComponentId::new(1463, 21);
    /// 1463:28, `kind=text`
    pub const PRAYER: ComponentId = ComponentId::new(1463, 28);
    /// 1463:159, `kind=text`
    pub const PVM_REDUCTION: ComponentId = ComponentId::new(1463, 159);
    /// 1463:161, `kind=text`
    pub const PVP_REDUCTION: ComponentId = ComponentId::new(1463, 161);
}

pub mod hero_loadout_worn {
    use crate::ComponentId;

    /// 1462:31, `kind=layer`
    pub const SLOTS: ComponentId = ComponentId::new(1462, 31);
    /// 1462:40, `kind=layer`
    pub const STATS_BUTTON: ComponentId = ComponentId::new(1462, 40);
}

pub mod hero_window {
    use crate::ComponentId;

    /// 1448:3, `kind=layer`
    pub const BACKPACK_PANE: ComponentId = ComponentId::new(1448, 3);
    /// 1448:11, `kind=layer`
    pub const FIFTH_PANE: ComponentId = ComponentId::new(1448, 11);
    /// 1448:9, `kind=layer`
    pub const FOURTH_PANE: ComponentId = ComponentId::new(1448, 9);
    /// 1448:1, `kind=layer`
    pub const LOADING_COVER: ComponentId = ComponentId::new(1448, 1);
    /// 1448:5, `kind=layer`
    pub const STATS_PANE: ComponentId = ComponentId::new(1448, 5);
    /// 1448:7, `kind=layer`
    pub const WORN_PANE: ComponentId = ComponentId::new(1448, 7);
}

pub mod house_settings {
    use crate::ComponentId;

    /// 1665:11, `kind=layer`
    pub const BUILD_MODE: ComponentId = ComponentId::new(1665, 11);
    /// 1665:17, `kind=layer`
    pub const LEAVE_HOUSE: ComponentId = ComponentId::new(1665, 17);
}

pub mod journal_scroll {
    use crate::ComponentId;

    /// 868:55, `kind=text`
    pub const LINE_46: ComponentId = ComponentId::new(868, 55);
}

pub mod legacy_combat {
    use crate::ComponentId;

    /// 1503:5, `kind=layer`
    pub const AGGRESSIVE_STANCE: ComponentId = ComponentId::new(1503, 5);
    /// 1503:6, `kind=layer`
    pub const BALANCED_STANCE: ComponentId = ComponentId::new(1503, 6);
    /// 1503:1, `kind=layer`
    pub const COMPACT_AGGRESSIVE_STANCE: ComponentId = ComponentId::new(1503, 1);
    /// 1503:2, `kind=layer`
    pub const COMPACT_BALANCED_STANCE: ComponentId = ComponentId::new(1503, 2);
    /// 1503:3, `kind=layer`
    pub const COMPACT_DEFENSIVE_STANCE: ComponentId = ComponentId::new(1503, 3);
    /// 1503:45, `kind=layer`
    pub const DEFENCE_TRAINING: ComponentId = ComponentId::new(1503, 45);
    /// 1503:7, `kind=layer`
    pub const DEFENSIVE_STANCE: ComponentId = ComponentId::new(1503, 7);
    /// 1503:37, `kind=layer`
    pub const PRIMARY_TRAINING: ComponentId = ComponentId::new(1503, 37);
    /// 1503:51, `kind=graphic`
    pub const RETALIATION_IMAGE: ComponentId = ComponentId::new(1503, 51);
    /// 1503:50, `kind=layer`
    pub const RETALIATION_TOGGLE: ComponentId = ComponentId::new(1503, 50);
    /// 1503:13, `kind=layer`
    pub const SPECIAL_ATTACK: ComponentId = ComponentId::new(1503, 13);
    /// 1503:41, `kind=layer`
    pub const STRENGTH_TRAINING: ComponentId = ComponentId::new(1503, 41);
}

pub mod legacy_life {
    use crate::ComponentId;

    /// 1504:3, `kind=layer`
    pub const VALUE_ROOT: ComponentId = ComponentId::new(1504, 3);
}

pub mod legacy_resource_frame {
    use crate::ComponentId;

    /// 1920:3, `kind=layer`
    pub const LIFE_SLOT: ComponentId = ComponentId::new(1920, 3);
    /// 1920:4, `kind=layer`
    pub const PRAYER_SLOT: ComponentId = ComponentId::new(1920, 4);
    /// 1920:5, `kind=layer`
    pub const SUMMONING_SLOT: ComponentId = ComponentId::new(1920, 5);
}

pub mod lobby_window {
    use crate::ComponentId;

    /// 906:111, `kind=layer`
    pub const CLAN_CHAT_SLOT: ComponentId = ComponentId::new(906, 111);
    /// 906:110, `kind=layer`
    pub const FRIENDS_CHAT_SLOT: ComponentId = ComponentId::new(906, 110);
    /// 906:109, `kind=layer`
    pub const FRIENDS_SLOT: ComponentId = ComponentId::new(906, 109);
    /// 906:112, `kind=layer`
    pub const OPTIONS_SLOT: ComponentId = ComponentId::new(906, 112);
    /// 906:107, `kind=layer`
    pub const PLAYER_INFO_SLOT: ComponentId = ComponentId::new(906, 107);
    /// 906:236, `kind=layer`
    pub const POPUP_LAYER: ComponentId = ComponentId::new(906, 236);
    /// 906:298, `kind=layer`
    pub const REPORT_ABUSE_DETAILS_SLOT: ComponentId = ComponentId::new(906, 298);
    /// 906:280, `kind=layer`
    pub const REPORT_ABUSE_SLOT: ComponentId = ComponentId::new(906, 280);
    /// 906:307, `kind=layer`
    pub const REPORT_IGNORE_SLOT: ComponentId = ComponentId::new(906, 307);
    /// 906:10, `kind=graphic`
    pub const TIMER_BACKDROP: ComponentId = ComponentId::new(906, 10);
    /// 906:108, `kind=layer`
    pub const WORLD_SELECT_SLOT: ComponentId = ComponentId::new(906, 108);
}

pub mod lodestone_network {
    use crate::ComponentId;

    /// 1092:11, `kind=graphic`
    pub const AL_KHARID_BUTTON: ComponentId = ComponentId::new(1092, 11);
    /// 1092:12, `kind=graphic`
    pub const ARDOUGNE_BUTTON: ComponentId = ComponentId::new(1092, 12);
    /// 1092:33, `kind=graphic`
    pub const ASHDALE_BUTTON: ComponentId = ComponentId::new(1092, 33);
    /// 1092:9, `kind=graphic`
    pub const BANDIT_CAMP_BUTTON: ComponentId = ComponentId::new(1092, 9);
    /// 1092:13, `kind=graphic`
    pub const BURTHORPE_BUTTON: ComponentId = ComponentId::new(1092, 13);
    /// 1092:26, `kind=graphic`
    pub const CANIFIS_BUTTON: ComponentId = ComponentId::new(1092, 26);
    /// 1092:14, `kind=graphic`
    pub const CATHERBY_BUTTON: ComponentId = ComponentId::new(1092, 14);
    /// 1092:15, `kind=graphic`
    pub const DRAYNOR_BUTTON: ComponentId = ComponentId::new(1092, 15);
    /// 1092:27, `kind=graphic`
    pub const EAGLES_PEAK_BUTTON: ComponentId = ComponentId::new(1092, 27);
    /// 1092:16, `kind=graphic`
    pub const EDGEVILLE_BUTTON: ComponentId = ComponentId::new(1092, 16);
    /// 1092:17, `kind=graphic`
    pub const FALADOR_BUTTON: ComponentId = ComponentId::new(1092, 17);
    /// 1092:28, `kind=graphic`
    pub const FREMENNIK_PROVINCE_BUTTON: ComponentId = ComponentId::new(1092, 28);
    /// 1092:29, `kind=graphic`
    pub const KARAMJA_BUTTON: ComponentId = ComponentId::new(1092, 29);
    /// 1092:18, `kind=graphic`
    pub const LUMBRIDGE_BUTTON: ComponentId = ComponentId::new(1092, 18);
    /// 1092:10, `kind=graphic`
    pub const LUNAR_ISLE_BUTTON: ComponentId = ComponentId::new(1092, 10);
    /// 1092:23, `kind=graphic`
    pub const MENAPHOS_BUTTON: ComponentId = ComponentId::new(1092, 23);
    /// 1092:30, `kind=graphic`
    pub const OOGLOG_BUTTON: ComponentId = ComponentId::new(1092, 30);
    /// 1092:19, `kind=graphic`
    pub const PORT_SARIM_BUTTON: ComponentId = ComponentId::new(1092, 19);
    /// 1092:34, `kind=graphic`
    pub const PRIFDDINAS_BUTTON: ComponentId = ComponentId::new(1092, 34);
    /// 1092:59, `kind=layer`
    pub const QUICK_TELEPORT_TOGGLE: ComponentId = ComponentId::new(1092, 59);
    /// 1092:20, `kind=graphic`
    pub const SEERS_VILLAGE_BUTTON: ComponentId = ComponentId::new(1092, 20);
    /// 1092:21, `kind=graphic`
    pub const TAVERLEY_BUTTON: ComponentId = ComponentId::new(1092, 21);
    /// 1092:31, `kind=graphic`
    pub const TIRANNWN_BUTTON: ComponentId = ComponentId::new(1092, 31);
    /// 1092:22, `kind=graphic`
    pub const VARROCK_BUTTON: ComponentId = ComponentId::new(1092, 22);
    /// 1092:32, `kind=graphic`
    pub const WILDERNESS_VOLCANO_BUTTON: ComponentId = ComponentId::new(1092, 32);
    /// 1092:25, `kind=graphic`
    pub const YANILLE_BUTTON: ComponentId = ComponentId::new(1092, 25);
}

pub mod loot_claim_window {
    use crate::ComponentId;

    /// 168:9, `kind=layer`
    pub const ABANDON_ALL: ComponentId = ComponentId::new(168, 9);
    /// 168:27, `kind=layer`
    pub const BANK_ALL: ComponentId = ComponentId::new(168, 27);
    /// 168:36, `kind=layer`
    pub const CLOSE: ComponentId = ComponentId::new(168, 36);
    /// 168:34, `kind=layer`
    pub const ITEM_AREA: ComponentId = ComponentId::new(168, 34);
    /// 168:18, `kind=layer`
    pub const TAKE_ALL: ComponentId = ComponentId::new(168, 18);
}

pub mod magic_book {
    use crate::ComponentId;

    /// 1459:1, `kind=layer`
    pub const ACTIONS: ComponentId = ComponentId::new(1459, 1);
    /// 1459:0, `kind=layer`
    pub const SPELL_BUTTONS: ComponentId = ComponentId::new(1459, 0);
}

pub mod make_x {
    use crate::ComponentId;

    /// 1370:32, `kind=layer`
    pub const CLOSE_BUTTON: ComponentId = ComponentId::new(1370, 32);
    /// 1370:30, `kind=layer`
    pub const MAKE_BUTTON: ComponentId = ComponentId::new(1370, 30);
    /// 1370:3, `kind=layer`
    pub const PRODUCT_LIST_SLOT: ComponentId = ComponentId::new(1370, 3);
}

pub mod make_x_products {
    use crate::ComponentId;

    /// 1371:22, `kind=layer`
    pub const LIST: ComponentId = ComponentId::new(1371, 22);
    /// 1371:19, `kind=layer`
    pub const QUANTITY_SLIDER: ComponentId = ComponentId::new(1371, 19);
}

pub mod melee_book {
    use crate::ComponentId;

    /// 1450:3, `kind=layer`
    pub const ABILITIES: ComponentId = ComponentId::new(1450, 3);
    /// 1450:0, `kind=layer`
    pub const TABS: ComponentId = ComponentId::new(1450, 0);
}

pub mod memory_conversion {
    use crate::ComponentId;

    /// 131:8, `kind=layer`
    pub const CLOSE_BUTTON: ComponentId = ComponentId::new(131, 8);
    /// 131:10, `kind=layer`
    pub const ENERGY_BUTTON: ComponentId = ComponentId::new(131, 10);
    /// 131:16, `kind=layer`
    pub const ENHANCED_BUTTON: ComponentId = ComponentId::new(131, 16);
    /// 131:13, `kind=layer`
    pub const EXPERIENCE_BUTTON: ComponentId = ComponentId::new(131, 13);
}

pub mod message_box {
    use crate::ComponentId;

    /// 1186:8, `kind=layer`
    pub const CONTINUE_BUTTON: ComponentId = ComponentId::new(1186, 8);
}

pub mod metal_window {
    use crate::ComponentId;

    /// 37:163, `kind=layer`
    pub const BEGIN_PROJECT: ComponentId = ComponentId::new(37, 163);
    /// 37:167, `kind=layer`
    pub const DEPOSIT_ALL: ComponentId = ComponentId::new(37, 167);
    /// 37:103, `kind=layer`
    pub const ITEMS_LIST: ComponentId = ComponentId::new(37, 103);
    /// 37:52, `kind=layer`
    pub const STOCK_LIST: ComponentId = ComponentId::new(37, 52);
}

pub mod minimap {
    use crate::ComponentId;

    /// 1465:18, `kind=graphic`
    pub const HOME_TELEPORT_BUTTON: ComponentId = ComponentId::new(1465, 18);
    /// 1465:6, `kind=layer`
    pub const LEGACY_RESOURCES_SLOT: ComponentId = ComponentId::new(1465, 6);
    /// 1465:11, `kind=graphic`
    pub const RUN_BUTTON: ComponentId = ComponentId::new(1465, 11);
    /// 1465:16, `kind=text`
    pub const RUN_ENERGY_TEXT: ComponentId = ComponentId::new(1465, 16);
    /// 1465:15, `kind=graphic`
    pub const RUN_ORB: ComponentId = ComponentId::new(1465, 15);
    /// 1465:9, `kind=graphic`
    pub const WORLD_MAP_BUTTON: ComponentId = ComponentId::new(1465, 9);
}

pub mod npc_chat {
    use crate::ComponentId;

    /// 1184:15, `kind=layer`
    pub const CONTINUE_BUTTON: ComponentId = ComponentId::new(1184, 15);
    /// 1184:10, `kind=text`
    pub const TEXT: ComponentId = ComponentId::new(1184, 10);
}

pub mod options_menu {
    use crate::ComponentId;

    /// 1433:14, `kind=layer`
    pub const SETTINGS_BUTTON: ComponentId = ComponentId::new(1433, 14);
    /// 1433:34, `kind=layer`
    pub const VIEW_CONTROLS_BUTTON: ComponentId = ComponentId::new(1433, 34);
}

pub mod player_chat {
    use crate::ComponentId;

    /// 1191:15, `kind=layer`
    pub const CONTINUE_BUTTON: ComponentId = ComponentId::new(1191, 15);
}

pub mod powers_prayer_book {
    use crate::ComponentId;

    /// 1457:15, `kind=layer`
    pub const PRAYER_BUTTONS: ComponentId = ComponentId::new(1457, 15);
}

pub mod prayer_book {
    use crate::ComponentId;

    /// 1458:39, `kind=layer`
    pub const PRAYER_BUTTONS: ComponentId = ComponentId::new(1458, 39);
}

pub mod price_checker {
    use crate::ComponentId;

    /// 1666:6, `kind=layer`
    pub const COIN_WALLET: ComponentId = ComponentId::new(1666, 6);
}

pub mod quest_complete_scroll {
    use crate::ComponentId;

    /// 1244:21, `kind=layer`
    pub const CONTINUE_BUTTON: ComponentId = ComponentId::new(1244, 21);
    /// 1244:26, `kind=model`
    pub const ITEM_MODEL: ComponentId = ComponentId::new(1244, 26);
    /// 1244:29, `kind=text`
    pub const POINTS: ComponentId = ComponentId::new(1244, 29);
    /// 1244:27, `kind=text`
    pub const TITLE: ComponentId = ComponentId::new(1244, 27);
}

pub mod quest_journal_window {
    use crate::ComponentId;

    /// 1500:404, `kind=layer`
    pub const ACCEPT_BUTTON: ComponentId = ComponentId::new(1500, 404);
    /// 1500:401, `kind=layer`
    pub const DECLINE_BUTTON: ComponentId = ComponentId::new(1500, 401);
    /// 1500:22, `kind=text`
    pub const FIRST_LINE: ComponentId = ComponentId::new(1500, 22);
    /// 1500:1, `kind=layer`
    pub const JOURNAL_PANE: ComponentId = ComponentId::new(1500, 1);
    /// 1500:323, `kind=layer`
    pub const NOTHING_SELECTED: ComponentId = ComponentId::new(1500, 323);
    /// 1500:394, `kind=layer`
    pub const OFFER_BUTTONS: ComponentId = ComponentId::new(1500, 394);
    /// 1500:13, `kind=layer`
    pub const OVERVIEW_BUTTON: ComponentId = ComponentId::new(1500, 13);
    /// 1500:326, `kind=layer`
    pub const OVERVIEW_PANE: ComponentId = ComponentId::new(1500, 326);
    /// 1500:18, `kind=text`
    pub const TITLE: ComponentId = ComponentId::new(1500, 18);
    /// 1500:405, `kind=layer`
    pub const VIEW_BUTTONS: ComponentId = ComponentId::new(1500, 405);
    /// 1500:419, `kind=layer`
    pub const VIEW_JOURNAL_BUTTON: ComponentId = ComponentId::new(1500, 419);
}

pub mod quest_list_window {
    use crate::ComponentId;

    /// 1783:18, `kind=text`
    pub const POINTS: ComponentId = ComponentId::new(1783, 18);
    /// 1783:7, `kind=layer`
    pub const ROWS: ComponentId = ComponentId::new(1783, 7);
}

pub mod ranged_book {
    use crate::ComponentId;

    /// 1456:1, `kind=layer`
    pub const ABILITIES: ComponentId = ComponentId::new(1456, 1);
}

pub mod room_creation {
    use crate::ComponentId;

    /// 402:98, `kind=layer`
    pub const BUILD_DINING_ROOM: ComponentId = ComponentId::new(402, 98);
    /// 402:81, `kind=layer`
    pub const BUILD_GARDEN: ComponentId = ComponentId::new(402, 81);
    /// 402:90, `kind=layer`
    pub const BUILD_KITCHEN: ComponentId = ComponentId::new(402, 90);
    /// 402:72, `kind=layer`
    pub const BUILD_PARLOUR: ComponentId = ComponentId::new(402, 72);
    /// 402:77, `kind=layer`
    pub const BUILD_WORKSHOP: ComponentId = ComponentId::new(402, 77);
}

pub mod shop {
    use crate::ComponentId;

    /// 1265:79, `kind=layer`
    pub const AMOUNT_PLUS_FIVE: ComponentId = ComponentId::new(1265, 79);
    /// 1265:41, `kind=layer`
    pub const BUY_TAB: ComponentId = ComponentId::new(1265, 41);
    /// 1265:217, `kind=layer`
    pub const CLOSE_BUTTON: ComponentId = ComponentId::new(1265, 217);
    /// 1265:144, `kind=layer`
    pub const CONFIRM_BUTTON: ComponentId = ComponentId::new(1265, 144);
    /// 1265:32, `kind=layer`
    pub const SELL_TAB: ComponentId = ComponentId::new(1265, 32);
    /// 1265:20, `kind=layer`
    pub const STOCK_ROWS: ComponentId = ComponentId::new(1265, 20);
}

pub mod skill_choice {
    use crate::ComponentId;

    /// 1263:13, `kind=layer`
    pub const CONFIRM: ComponentId = ComponentId::new(1263, 13);
    /// 1263:34, `kind=layer`
    pub const PRAYER: ComponentId = ComponentId::new(1263, 34);
}

pub mod slayer_counter {
    use crate::ComponentId;

    /// 1639:10, `kind=text`
    pub const COUNT: ComponentId = ComponentId::new(1639, 10);
    /// 1639:20, `kind=text`
    pub const STREAK: ComponentId = ComponentId::new(1639, 20);
    /// 1639:11, `kind=text`
    pub const TARGET: ComponentId = ComponentId::new(1639, 11);
}

pub mod slayer_rewards {
    use crate::ComponentId;

    /// 1308:555, `kind=layer`
    pub const BLOCK_TASK: ComponentId = ComponentId::new(1308, 555);
    /// 1308:562, `kind=layer`
    pub const BLOCK_TASK_BUY: ComponentId = ComponentId::new(1308, 562);
    /// 1308:45, `kind=layer`
    pub const BROAD_ARROWS: ComponentId = ComponentId::new(1308, 45);
    /// 1308:57, `kind=layer`
    pub const BROAD_ARROWS_BUY: ComponentId = ComponentId::new(1308, 57);
    /// 1308:48, `kind=model`
    pub const BROAD_ARROWS_MODEL: ComponentId = ComponentId::new(1308, 48);
    /// 1308:62, `kind=layer`
    pub const BROAD_BOLTS: ComponentId = ComponentId::new(1308, 62);
    /// 1308:74, `kind=layer`
    pub const BROAD_BOLTS_BUY: ComponentId = ComponentId::new(1308, 74);
    /// 1308:65, `kind=model`
    pub const BROAD_BOLTS_MODEL: ComponentId = ComponentId::new(1308, 65);
    /// 1308:543, `kind=layer`
    pub const CANCEL_TASK: ComponentId = ComponentId::new(1308, 543);
    /// 1308:549, `kind=layer`
    pub const CANCEL_TASK_BUY: ComponentId = ComponentId::new(1308, 549);
    /// 1308:868, `kind=layer`
    pub const CO_OP_DESERT_SKIN_BUY: ComponentId = ComponentId::new(1308, 868);
    /// 1308:723, `kind=layer`
    pub const CO_OP_FOOD_BUY: ComponentId = ComponentId::new(1308, 723);
    /// 1308:820, `kind=layer`
    pub const CO_OP_FREEZY_BUY: ComponentId = ComponentId::new(1308, 820);
    /// 1308:691, `kind=layer`
    pub const CO_OP_HELM_RECHARGE_BUY: ComponentId = ComponentId::new(1308, 691);
    /// 1308:836, `kind=layer`
    pub const CO_OP_JUNGLE_SKIN_BUY: ComponentId = ComponentId::new(1308, 836);
    /// 1308:756, `kind=layer`
    pub const CO_OP_PORTENTS_BUY: ComponentId = ComponentId::new(1308, 756);
    /// 1308:804, `kind=layer`
    pub const CO_OP_POTIONS_BUY: ComponentId = ComponentId::new(1308, 804);
    /// 1308:740, `kind=layer`
    pub const CO_OP_PROTECTION_BUY: ComponentId = ComponentId::new(1308, 740);
    /// 1308:707, `kind=layer`
    pub const CO_OP_RINGS_RECHARGE_BUY: ComponentId = ComponentId::new(1308, 707);
    /// 1308:884, `kind=layer`
    pub const CO_OP_RUNTSTABLE_BUY: ComponentId = ComponentId::new(1308, 884);
    /// 1308:772, `kind=layer`
    pub const CO_OP_SQUIDGE_BUY: ComponentId = ComponentId::new(1308, 772);
    /// 1308:788, `kind=layer`
    pub const CO_OP_TELEPORTS_BUY: ComponentId = ComponentId::new(1308, 788);
    /// 1308:852, `kind=layer`
    pub const CO_OP_WILDERNESS_SKIN_BUY: ComponentId = ComponentId::new(1308, 852);
    /// 1308:574, `kind=layer`
    pub const EXTEND_TASK_BUY: ComponentId = ComponentId::new(1308, 574);
    /// 1308:144, `kind=layer`
    pub const FEROCIOUS_RING_UPGRADE_BUY: ComponentId = ComponentId::new(1308, 144);
    /// 1308:470, `kind=layer`
    pub const LEARN_BONECRUSHER_BELT_BUY: ComponentId = ComponentId::new(1308, 470);
    /// 1308:370, `kind=layer`
    pub const LEARN_BROAD_BUY: ComponentId = ComponentId::new(1308, 370);
    /// 1308:518, `kind=layer`
    pub const LEARN_CHARMING_IMP_BELT_BUY: ComponentId = ComponentId::new(1308, 518);
    /// 1308:438, `kind=layer`
    pub const LEARN_FUSED_RINGS_BUY: ComponentId = ComponentId::new(1308, 438);
    /// 1308:534, `kind=layer`
    pub const LEARN_GOLD_ACCUMULATOR_BELT_BUY: ComponentId = ComponentId::new(1308, 534);
    /// 1308:410, `kind=layer`
    pub const LEARN_HELMET: ComponentId = ComponentId::new(1308, 410);
    /// 1308:421, `kind=layer`
    pub const LEARN_HELMET_BUY: ComponentId = ComponentId::new(1308, 421);
    /// 1308:486, `kind=layer`
    pub const LEARN_HERBICIDE_BELT_BUY: ComponentId = ComponentId::new(1308, 486);
    /// 1308:405, `kind=layer`
    pub const LEARN_QUICK_KILLS_BUY: ComponentId = ComponentId::new(1308, 405);
    /// 1308:386, `kind=layer`
    pub const LEARN_RINGS_BUY: ComponentId = ComponentId::new(1308, 386);
    /// 1308:502, `kind=layer`
    pub const LEARN_SEEDICIDE_BELT_BUY: ComponentId = ComponentId::new(1308, 502);
    /// 1308:27, `kind=layer`
    pub const LEARN_TAB: ComponentId = ComponentId::new(1308, 27);
    /// 1308:83, `kind=model`
    pub const MAGIC_DART_AIR_MODEL: ComponentId = ComponentId::new(1308, 83);
    /// 1308:82, `kind=model`
    pub const MAGIC_DART_DEATH_MODEL: ComponentId = ComponentId::new(1308, 82);
    /// 1308:92, `kind=layer`
    pub const MAGIC_DART_RUNES_BUY: ComponentId = ComponentId::new(1308, 92);
    /// 1308:586, `kind=layer`
    pub const PREFER_TASK_BUY: ComponentId = ComponentId::new(1308, 586);
    /// 1308:97, `kind=layer`
    pub const RING_OF_SLAYING: ComponentId = ComponentId::new(1308, 97);
    /// 1308:109, `kind=layer`
    pub const RING_OF_SLAYING_BUY: ComponentId = ComponentId::new(1308, 109);
    /// 1308:167, `kind=layer`
    pub const SLAYER_EXPERIENCE: ComponentId = ComponentId::new(1308, 167);
    /// 1308:179, `kind=layer`
    pub const SLAYER_EXPERIENCE_BUY: ComponentId = ComponentId::new(1308, 179);
    /// 1308:598, `kind=graphic`
    pub const UNBLOCK_TASK_1: ComponentId = ComponentId::new(1308, 598);
    /// 1308:603, `kind=graphic`
    pub const UNBLOCK_TASK_2: ComponentId = ComponentId::new(1308, 603);
    /// 1308:608, `kind=graphic`
    pub const UNBLOCK_TASK_3: ComponentId = ComponentId::new(1308, 608);
    /// 1308:613, `kind=graphic`
    pub const UNBLOCK_TASK_4: ComponentId = ComponentId::new(1308, 613);
    /// 1308:618, `kind=graphic`
    pub const UNBLOCK_TASK_5: ComponentId = ComponentId::new(1308, 618);
    /// 1308:623, `kind=graphic`
    pub const UNBLOCK_TASK_6: ComponentId = ComponentId::new(1308, 623);
    /// 1308:628, `kind=graphic`
    pub const UNBLOCK_TASK_7: ComponentId = ComponentId::new(1308, 628);
    /// 1308:633, `kind=graphic`
    pub const UNBLOCK_TASK_8: ComponentId = ComponentId::new(1308, 633);
    /// 1308:274, `kind=layer`
    pub const UNLOCK_AQUANITE_BUY: ComponentId = ComponentId::new(1308, 274);
    /// 1308:322, `kind=layer`
    pub const UNLOCK_GLACOR_BUY: ComponentId = ComponentId::new(1308, 322);
    /// 1308:454, `kind=layer`
    pub const UNLOCK_ICE_STRYKEWYRM_BUY: ComponentId = ComponentId::new(1308, 454);
    /// 1308:290, `kind=layer`
    pub const UNLOCK_MUSPAH_BUY: ComponentId = ComponentId::new(1308, 290);
    /// 1308:354, `kind=layer`
    pub const UNLOCK_NIGHTMARE_BUY: ComponentId = ComponentId::new(1308, 354);
    /// 1308:306, `kind=layer`
    pub const UNLOCK_NIHIL_BUY: ComponentId = ComponentId::new(1308, 306);
    /// 1308:338, `kind=layer`
    pub const UNLOCK_TORMENTED_DEMONS_BUY: ComponentId = ComponentId::new(1308, 338);
    /// 1308:638, `kind=graphic`
    pub const UNPREFER_TASK_1: ComponentId = ComponentId::new(1308, 638);
    /// 1308:643, `kind=graphic`
    pub const UNPREFER_TASK_2: ComponentId = ComponentId::new(1308, 643);
    /// 1308:648, `kind=graphic`
    pub const UNPREFER_TASK_3: ComponentId = ComponentId::new(1308, 648);
    /// 1308:653, `kind=graphic`
    pub const UNPREFER_TASK_4: ComponentId = ComponentId::new(1308, 653);
    /// 1308:658, `kind=graphic`
    pub const UNPREFER_TASK_5: ComponentId = ComponentId::new(1308, 658);
    /// 1308:663, `kind=graphic`
    pub const UNPREFER_TASK_6: ComponentId = ComponentId::new(1308, 663);
    /// 1308:668, `kind=graphic`
    pub const UNPREFER_TASK_7: ComponentId = ComponentId::new(1308, 668);
    /// 1308:673, `kind=graphic`
    pub const UNPREFER_TASK_8: ComponentId = ComponentId::new(1308, 673);
    /// 1308:215, `kind=layer`
    pub const UPGRADE_CORRUPTED_BUY: ComponentId = ComponentId::new(1308, 215);
    /// 1308:197, `kind=layer`
    pub const UPGRADE_MIGHTY_BUY: ComponentId = ComponentId::new(1308, 197);
    /// 1308:127, `kind=layer`
    pub const UPGRADE_REINFORCED_BUY: ComponentId = ComponentId::new(1308, 127);
    /// 1308:162, `kind=layer`
    pub const UPGRADE_STRONG_BUY: ComponentId = ComponentId::new(1308, 162);
    /// 1308:232, `kind=layer`
    pub const USHABTI_BUY: ComponentId = ComponentId::new(1308, 232);
}

pub mod spirit_tree_window {
    use crate::ComponentId;

    /// 1145:31, `kind=layer`
    pub const CLOSE_BUTTON: ComponentId = ComponentId::new(1145, 31);
}

pub mod status_buffs {
    use crate::ComponentId;

    /// 284:12, `kind=layer`
    pub const ICONS: ComponentId = ComponentId::new(284, 12);
}

pub mod status_debuffs {
    use crate::ComponentId;

    /// 291:1, `kind=layer`
    pub const ICONS: ComponentId = ComponentId::new(291, 1);
}

pub mod tool_belt {
    use crate::ComponentId;

    /// 1944:27, `kind=text`
    pub const INFO_TEXT: ComponentId = ComponentId::new(1944, 27);
    /// 1944:7, `kind=layer`
    pub const SLOTS: ComponentId = ComponentId::new(1944, 7);
}

pub mod trade_confirm {
    use crate::ComponentId;

    /// 334:44, `kind=layer`
    pub const ACCEPT: ComponentId = ComponentId::new(334, 44);
    /// 334:49, `kind=layer`
    pub const DECLINE: ComponentId = ComponentId::new(334, 49);
    /// 334:19, `kind=text`
    pub const OFFER_CHANGED: ComponentId = ComponentId::new(334, 19);
}

pub mod trade_offer {
    use crate::ComponentId;

    /// 335:48, `kind=layer`
    pub const ACCEPT: ComponentId = ComponentId::new(335, 48);
    /// 335:29, `kind=layer`
    pub const ADD_FROM_POUCH: ComponentId = ComponentId::new(335, 29);
    /// 335:50, `kind=layer`
    pub const DECLINE: ComponentId = ComponentId::new(335, 50);
    /// 335:15, `kind=layer`
    pub const MY_OFFER: ComponentId = ComponentId::new(335, 15);
    /// 335:22, `kind=text`
    pub const MY_OFFER_CHANGED: ComponentId = ComponentId::new(335, 22);
    /// 335:27, `kind=layer`
    pub const OFFER_ALL: ComponentId = ComponentId::new(335, 27);
    /// 335:21, `kind=text`
    pub const STATUS_TEXT: ComponentId = ComponentId::new(335, 21);
    /// 335:18, `kind=layer`
    pub const THEIR_OFFER: ComponentId = ComponentId::new(335, 18);
    /// 335:23, `kind=text`
    pub const THEIR_OFFER_CHANGED: ComponentId = ComponentId::new(335, 23);
}

pub mod trade_side {
    use crate::ComponentId;

    /// 336:0, `kind=layer`
    pub const BACKPACK_GRID: ComponentId = ComponentId::new(336, 0);
}

pub mod wilderness_hud {
    use crate::ComponentId;

    /// 381:2, `kind=text`
    pub const LEVEL_TEXT: ComponentId = ComponentId::new(381, 2);
}

pub mod window_buttons {
    use crate::ComponentId;

    /// 1431:0, `kind=layer`
    pub const ACTIONS: ComponentId = ComponentId::new(1431, 0);
}

pub mod world_map_controls {
    use crate::ComponentId;

    /// 1422:128, `kind=layer`
    pub const CLOSE_BUTTON: ComponentId = ComponentId::new(1422, 128);
}

pub mod worn_equipment {
    use crate::ComponentId;

    /// 1464:1, `kind=layer`
    pub const PLAYER_MODEL: ComponentId = ComponentId::new(1464, 1);
    /// 1464:2, `kind=layer`
    pub const PLAYER_MODEL_DRAG: ComponentId = ComponentId::new(1464, 2);
    /// 1464:15, `kind=layer`
    pub const SLOTS: ComponentId = ComponentId::new(1464, 15);
    /// 1464:24, `kind=layer`
    pub const STATS_BUTTON: ComponentId = ComponentId::new(1464, 24);
}
