// Generated by `npm --prefix server run sym -- gen` from revisions/910/symbols/dbrow.sym. Do not edit: add symbols
// with `npm --prefix server run sym -- add` (docs/symbols.md).

//! The named dbrow ids of revision 910.

use crate::DbRowId;

/// `table=47`
pub const BARROWS_LOOT_HEADING: DbRowId = DbRowId(1577);
/// `table=28`
pub const COIN_WALLET_BUTTON: DbRowId = DbRowId(1015);
