// Generated by `npm --prefix server run sym -- gen` from revisions/910/symbols/dbtable.sym. Do not edit: add symbols
// with `npm --prefix server run sym -- add` (docs/symbols.md).

//! The named dbtable ids of revision 910.
