// Generated by `npm --prefix server run sym -- gen` from revisions/910/symbols/enum.sym. Do not edit: add symbols
// with `npm --prefix server run sym -- add` (docs/symbols.md).

//! The named enum ids of revision 910.

use crate::EnumId;

/// `key=int;value=int`
pub const AMMUNITION_DAMAGE_CAP: EnumId = EnumId(7443);
/// `key=obj;value=dbrow`
pub const ANVIL_METAL_ROWS: EnumId = EnumId(2531);
/// `key=int;value=struct`
pub const ATTACK_ACTIONS: EnumId = EnumId(6734);
/// `key=int;value=dbrow`
pub const BACKPACK_ACTION_ROWS: EnumId = EnumId(5136);
/// `key=int;value=obj`
pub const BELT_PICKAXE_ORDER: EnumId = EnumId(2433);
/// `key=int;value=struct`
pub const CONSTITUTION_ACTIONS: EnumId = EnumId(6737);
/// `key=int;value=obj`
pub const COOKING_BREADS: EnumId = EnumId(6800);
/// `key=int;value=obj`
pub const COOKING_CAKES: EnumId = EnumId(6799);
/// `key=int;value=obj`
pub const COOKING_CAVE_POTATO: EnumId = EnumId(6857);
/// `key=int;value=obj`
pub const COOKING_FISH: EnumId = EnumId(6797);
/// `key=int;value=obj`
pub const COOKING_PIES: EnumId = EnumId(6798);
/// `key=int;value=obj`
pub const COOKING_POTATOES: EnumId = EnumId(6802);
/// `key=int;value=obj`
pub const COOKING_SPIT_ROASTS: EnumId = EnumId(6811);
/// `key=int;value=obj`
pub const CRAFTING_GOLD_JEWELLERY: EnumId = EnumId(6985);
/// `key=int;value=obj`
pub const CRAFTING_MOLTEN_GLASS: EnumId = EnumId(6978);
/// `key=int;value=obj`
pub const CRAFTING_SILVER_CASTING: EnumId = EnumId(6984);
/// `key=int;value=obj`
pub const CRAFTING_SPINNING: EnumId = EnumId(7046);
/// `key=int;value=obj`
pub const CRAFTING_TANNING: EnumId = EnumId(6989);
/// `key=int;value=obj`
pub const CRAFTING_TANNING_CANIFIS: EnumId = EnumId(6990);
/// `key=int;value=obj`
pub const CRAFTING_TANNING_ZOMBIE: EnumId = EnumId(9814);
/// `key=int;value=obj`
pub const CRAFTING_WEAVING: EnumId = EnumId(7044);
/// `key=int;value=struct`
pub const DEFENCE_ACTIONS: EnumId = EnumId(6736);
/// `key=int;value=struct`
pub const EMOTE_LIST: EnumId = EnumId(3874);
/// `key=int;value=component`
pub const EXCHANGE_BOX_COLLECT_LAYERS: EnumId = EnumId(1080);
/// `key=int;value=inv`
pub const EXCHANGE_COLLECT_INVS: EnumId = EnumId(1079);
/// `key=int;value=component`
pub const EXCHANGE_MEMBER_SLOT_LOCKS: EnumId = EnumId(1077);
/// `key=int;value=component`
pub const EXCHANGE_OFFER_BOXES: EnumId = EnumId(1073);
/// `key=int;value=string`
pub const FAIRY_RING_DIAL_CODES: EnumId = EnumId(15117);
/// `key=int;value=component`
pub const FAIRY_RING_LOG_BUTTONS: EnumId = EnumId(1467);
/// `key=component;value=string`
pub const FAIRY_RING_LOG_CODES: EnumId = EnumId(1466);
/// `key=int;value=struct`
pub const FISHING_GUIDE: EnumId = EnumId(5461);
/// `key=obj;value=dbrow`
pub const FURNACE_METAL_ROWS: EnumId = EnumId(2530);
/// `key=int;value=struct`
pub const HERO_WINDOW_KINDS: EnumId = EnumId(7699);
/// `key=int;value=int`
pub const LEVEL_EXPERIENCE_THRESHOLDS: EnumId = EnumId(716);
/// `key=coord;value=string`
pub const LODESTONE_NAMES_BY_PLACE: EnumId = EnumId(5726);
/// `key=int;value=struct`
pub const MAGIC_ACTIONS: EnumId = EnumId(6740);
/// `key=int;value=obj`
pub const METAL_BANK_SLOT_ITEMS: EnumId = EnumId(15093);
/// `key=int;value=struct`
pub const MINING_GUIDE: EnumId = EnumId(5456);
/// `key=int;value=midi`
pub const MUSIC_TRACK_FILES: EnumId = EnumId(1351);
/// `key=int;value=string`
pub const MUSIC_TRACK_NAMES: EnumId = EnumId(1345);
/// `key=int;value=struct`
pub const NATIVE_INTERFACE_WINDOWS: EnumId = EnumId(7716);
/// `key=int;value=obj`
pub const ORE_BOX_ORES: EnumId = EnumId(2501);
/// `key=int;value=obj`
pub const ORE_BOX_UPGRADES: EnumId = EnumId(2502);
/// `key=int;value=struct`
pub const PRAYER_ACTIONS: EnumId = EnumId(6739);
/// `key=int;value=struct`
pub const PRAYER_SELECTION_ORDER: EnumId = EnumId(6759);
/// `key=enum;value=int`
pub const PRODUCTION_CATEGORY_SKILL: EnumId = EnumId(13284);
/// `key=enum;value=string`
pub const PRODUCTION_CATEGORY_VERB: EnumId = EnumId(13283);
/// `key=int;value=string`
pub const PRODUCTION_SKILL_NAMES: EnumId = EnumId(13761);
/// `key=int;value=struct`
pub const QUEST_LIST_ENTRIES: EnumId = EnumId(2252);
/// `key=int;value=struct`
pub const RANGED_ACTIONS: EnumId = EnumId(6738);
/// `key=obj;value=int`
pub const SHOP_BUY_PRICES: EnumId = EnumId(733);
/// `key=obj;value=int`
pub const SHOP_BUY_PRICES_MAGIC_BEANS: EnumId = EnumId(3295);
/// `key=obj;value=int`
pub const SHOP_BUY_PRICES_TOKKUL: EnumId = EnumId(731);
/// `key=obj;value=int`
pub const SHOP_FIXED_PRICES: EnumId = EnumId(1441);
/// `key=inv;value=int`
pub const SHOP_GENERAL_STORES: EnumId = EnumId(921);
/// `key=obj;value=int`
pub const SHOP_SELL_PRICES_TOKKUL: EnumId = EnumId(732);
/// `key=stat;value=int`
pub const SKILL_CHOICE_BUTTON_OF_STAT: EnumId = EnumId(1482);
/// `key=int;value=stat`
pub const SKILL_CHOICE_STAT_OF_BUTTON: EnumId = EnumId(681);
/// `key=int;value=enum`
pub const SKILL_GUIDES: EnumId = EnumId(5420);
/// `key=int;value=struct`
pub const SLAYER_CHAELDAR_TASKS: EnumId = EnumId(1557);
/// `key=int;value=struct`
pub const SLAYER_DURADEL_TASKS: EnumId = EnumId(868);
/// `key=int;value=struct`
pub const SLAYER_KURADAL_TASKS: EnumId = EnumId(1559);
/// `key=int;value=struct`
pub const SLAYER_LANIAKEA_TASKS: EnumId = EnumId(15336);
/// `key=int;value=struct`
pub const SLAYER_MANDRITH_TASKS: EnumId = EnumId(13373);
/// `key=int;value=enum`
pub const SLAYER_MASTER_TASKS: EnumId = EnumId(1553);
/// `key=int;value=struct`
pub const SLAYER_MAZCHNA_TASKS: EnumId = EnumId(1555);
/// `key=int;value=struct`
pub const SLAYER_MORVRAN_TASKS: EnumId = EnumId(9248);
/// `key=int;value=struct`
pub const SLAYER_SUMONA_TASKS: EnumId = EnumId(1558);
/// `key=int;value=struct`
pub const SLAYER_TURAEL_TASKS: EnumId = EnumId(1554);
/// `key=int;value=struct`
pub const SLAYER_VANNAKA_TASKS: EnumId = EnumId(1556);
/// `key=int;value=struct`
pub const SMITHING_GUIDE: EnumId = EnumId(5451);
/// `key=int;value=component`
pub const SPIRIT_TREE_BUTTONS: EnumId = EnumId(8839);
/// `key=int;value=string`
pub const SPIRIT_TREE_NAMES: EnumId = EnumId(2535);
/// `key=int;value=coord`
pub const SPIRIT_TREE_PLACES: EnumId = EnumId(2536);
/// `key=stat;value=string`
pub const STAT_NAMES: EnumId = EnumId(680);
/// `key=int;value=struct`
pub const STRENGTH_ACTIONS: EnumId = EnumId(6735);
/// `key=int;value=enum`
pub const TOOL_BELT_LAYOUTS: EnumId = EnumId(13729);
/// `key=int;value=enum`
pub const TWO_HAND_RANGED_DAMAGE_BY_SPEED: EnumId = EnumId(12907);
/// `key=int;value=int`
pub const WEAPON_ACCURACY_TIERS: EnumId = EnumId(7338);
/// `key=int;value=int`
pub const WINDOW_BUTTON_ORDER: EnumId = EnumId(13319);
/// `key=int;value=struct`
pub const WOODCUTTING_GUIDE: EnumId = EnumId(5448);
