// Generated by `npm --prefix server run sym -- gen` from revisions/910/symbols/inv.sym. Do not edit: add symbols
// with `npm --prefix server run sym -- add` (docs/symbols.md).

//! The named inv ids of revision 910.

use crate::InvId;

/// `size=28`
pub const BACKPACK: InvId = InvId(93);
/// `size=1370`
pub const BANK_CONTENTS: InvId = InvId(95);
/// `size=15`
pub const BARROWS_PENDING_REWARDS: InvId = InvId(796);
/// `size=9`
pub const CLUE_REWARD_ITEMS: InvId = InvId(141);
/// `size=1`
pub const COIN_WALLET: InvId = InvId(623);
/// `size=9`
pub const DUEL_STAKE_OFFER: InvId = InvId(134);
/// `size=8`
pub const FURNITURE_CREATION_OPTIONS: InvId = InvId(398);
/// `size=40`
pub const GENERAL_STORE_STOCK: InvId = InvId(4);
/// `size=47`
pub const GRAVE_ITEMS: InvId = InvId(676);
/// `size=33`
pub const METAL_BANK_CONTENTS: InvId = InvId(858);
/// `size=1`
pub const TRADE_LEND_OFFER: InvId = InvId(541);
/// `size=28`
pub const TRADE_OFFER: InvId = InvId(90);
/// `size=1`
pub const TRADE_POUCH_OFFER: InvId = InvId(626);
/// `size=8`
pub const TZHAAR_RUNE_STORE: InvId = InvId(327);
/// `size=19`
pub const WORN_EQUIPMENT: InvId = InvId(94);
