// Generated by `npm --prefix server run sym -- gen` from the symbol kinds. Do not edit: add symbols
// with `npm --prefix server run sym -- add` (docs/symbols.md).

//! The content symbols of revision 910 (docs/symbols.md): one newtype per kind and one
//! module of constants per kind, `obj::LOGS`, `varbit::LODESTONE_LUMBRIDGE_UNLOCKED`,
//! `component::bank_window::DEPOSIT_BACKPACK`. The engine stays data-driven; tests, scenario
//! replays and debug tools name what they use here instead of writing ids.

pub mod component;
pub mod dbrow;
pub mod dbtable;
pub mod enums;
pub mod interface;
pub mod inv;
pub mod loc;
pub mod location;
pub mod npc;
pub mod obj;
pub mod param;
pub mod quest;
pub mod script;
pub mod seq;
pub mod spot;
pub mod structs;
pub mod varbit;
pub mod varc;
pub mod varp;

/// A component id: the interface in the high 16 bits, the component in the low 16.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ComponentId(pub u32);

impl ComponentId {
    /// The component `child` of `interface`.
    #[must_use]
    pub const fn new(interface: u16, child: u16) -> Self {
        Self(((interface as u32) << 16) | child as u32)
    }

    /// The interface the component belongs to.
    #[must_use]
    pub const fn interface(self) -> InterfaceId {
        InterfaceId((self.0 >> 16) as i32)
    }

    /// The component within its interface.
    #[must_use]
    pub const fn child(self) -> i32 {
        (self.0 & 0xffff) as i32
    }

    /// The packed id as the client holds it (`interface << 16 | child`).
    #[must_use]
    pub const fn packed(self) -> i32 {
        self.0 as i32
    }
}

/// A dbrow id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct DbRowId(pub i32);

impl DbRowId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A dbtable id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct DbTableId(pub i32);

impl DbTableId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// An enum id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct EnumId(pub i32);

impl EnumId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// An interface id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct InterfaceId(pub i32);

impl InterfaceId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// An inv id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct InvId(pub i32);

impl InvId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A loc id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct LocId(pub i32);

impl LocId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A tile: level, x and z packed as the client packs a coordinate (`level << 28 | x << 14 | z`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Location(pub u32);

impl Location {
    const COORD_BITS: u32 = 14;
    const COORD_MASK: u32 = (1 << Self::COORD_BITS) - 1;
    const LEVEL_SHIFT: u32 = 2 * Self::COORD_BITS;

    /// The tile at `x`, `z` on `level`.
    #[must_use]
    pub const fn new(level: u32, x: u32, z: u32) -> Self {
        Self((level << Self::LEVEL_SHIFT) | (x << Self::COORD_BITS) | z)
    }

    #[must_use]
    pub const fn level(self) -> i32 {
        (self.0 >> Self::LEVEL_SHIFT) as i32
    }

    #[must_use]
    pub const fn x(self) -> i32 {
        ((self.0 >> Self::COORD_BITS) & Self::COORD_MASK) as i32
    }

    #[must_use]
    pub const fn z(self) -> i32 {
        (self.0 & Self::COORD_MASK) as i32
    }

    /// The packed coordinate as the client holds it.
    #[must_use]
    pub const fn packed(self) -> i32 {
        self.0 as i32
    }
}

/// A npc id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct NpcId(pub i32);

impl NpcId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// An obj id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ObjId(pub i32);

impl ObjId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A param id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ParamId(pub i32);

impl ParamId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A quest id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct QuestId(pub i32);

impl QuestId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A script id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ScriptId(pub i32);

impl ScriptId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A seq id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SeqId(pub i32);

impl SeqId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A spot id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SpotId(pub i32);

impl SpotId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A struct id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct StructId(pub i32);

impl StructId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A varbit id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct VarbitId(pub i32);

impl VarbitId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A varc id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct VarcId(pub i32);

impl VarcId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}

/// A varp id.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct VarpId(pub i32);

impl VarpId {
    /// The id as the client and the cache write it.
    #[must_use]
    pub const fn id(self) -> i32 {
        self.0
    }
}
