// Generated by `npm --prefix server run sym -- gen` from revisions/910/symbols/param.sym. Do not edit: add symbols
// with `npm --prefix server run sym -- add` (docs/symbols.md).

//! The named param ids of revision 910.

use crate::ParamId;

/// `type=int;default=0`
pub const ABILITY_ADRENALINE_GENERATED: ParamId = ParamId(2800);
/// `type=int;default=0`
pub const ABILITY_ADRENALINE_REQUIRED: ParamId = ParamId(2798);
/// `type=int;default=0`
pub const ABILITY_ADRENALINE_TYPE: ParamId = ParamId(2799);
/// `type=enum;default=-1`
pub const ABILITY_ANIMATION_CATEGORY_MAP: ParamId = ParamId(2915);
/// `type=int;default=0`
pub const ABILITY_CHANNELLED: ParamId = ParamId(2801);
/// `type=int;default=0`
pub const ABILITY_EFFECT_DURATION: ParamId = ParamId(3740);
/// `type=graphic;default=-1`
pub const ABILITY_MOBILE_ICON: ParamId = ParamId(8120);
/// `type=int;default=0`
pub const ABILITY_OTHER_DURATION: ParamId = ParamId(2797);
/// `type=int;default=0`
pub const ABILITY_REQUIRES_DUAL_WIELD: ParamId = ParamId(2811);
/// `type=int;default=0`
pub const ABILITY_REQUIRES_SHIELD: ParamId = ParamId(2813);
/// `type=int;default=0`
pub const ABILITY_REQUIRES_TWO_HANDS: ParamId = ParamId(2812);
/// `type=int;default=0`
pub const ACCOMPLISHMENT_CAPE: ParamId = ParamId(258);
/// `type=int;default=0`
pub const ACCOMPLISHMENT_CAPE_TRIMMED: ParamId = ParamId(259);
/// `type=int;default=0`
pub const ACTIVE_PRAYER_DRAIN: ParamId = ParamId(2945);
/// `type=int;default=0`
pub const ALCHEMY_FORBIDDEN: ParamId = ParamId(689);
/// `type=obj;default=-1`
pub const ALCHEMY_RESULT_ITEM: ParamId = ParamId(1342);
/// `type=int;default=0`
pub const ALCHEMY_VALUE_OVERRIDE: ParamId = ParamId(6598);
/// `type=int;default=0`
pub const ALCHEMY_VALUE_WARNING_EXEMPT: ParamId = ParamId(7408);
/// `type=boolean;default=0`
pub const ALCHEMY_WARNING_REQUIRED: ParamId = ParamId(1339);
/// `type=int;default=0`
pub const ALL_STYLE_AFFINITY: ParamId = ParamId(2869);
/// `type=category;default=-1`
pub const AMMUNITION_CATEGORY: ParamId = ParamId(21);
/// `type=int;default=-1`
pub const ANACHRONIA_AGILITY_SECTION: ParamId = ParamId(7901);
/// `type=int;default=0`
pub const ARMOUR_VALUE: ParamId = ParamId(2870);
/// `type=int;default=4`
pub const ATTACK_SPEED: ParamId = ParamId(14);
/// `type=enum;default=-1`
pub const BELT_CATEGORY_ITEMS: ParamId = ParamId(6979);
/// `type=obj;default=-1`
pub const BELT_SLOT_OBJ: ParamId = ParamId(6980);
/// `type=int;default=0`
pub const BELT_SLOT_REMOVABLE: ParamId = ParamId(7765);
/// `type=string;default=Obtained automatically.`
pub const BELT_SLOT_UNLOCK_INFO: ParamId = ParamId(6983);
/// `type=string;default=To upgrade, select the 'Add to toolbelt' menu option on the upgrade item from your backpack.`
pub const BELT_SLOT_UPGRADE_INFO: ParamId = ParamId(6984);
/// `type=boolean;default=0`
pub const BELT_SLOT_UPGRADEABLE: ParamId = ParamId(6981);
/// `type=string;default=This is an upgradeable toolbelt item.`
pub const BELT_SLOT_UPGRADEABLE_INFO: ParamId = ParamId(6985);
/// `type=obj;default=-1`
pub const CHARGE_FORM_1: ParamId = ParamId(591);
/// `type=obj;default=-1`
pub const CHARGE_FORM_2: ParamId = ParamId(590);
/// `type=obj;default=-1`
pub const CHARGE_FORM_3: ParamId = ParamId(589);
/// `type=obj;default=-1`
pub const CHARGE_FORM_4: ParamId = ParamId(588);
/// `type=obj;default=-1`
pub const CHARGE_FORM_5: ParamId = ParamId(535);
/// `type=obj;default=-1`
pub const CHARGE_FORM_6: ParamId = ParamId(534);
/// `type=obj;default=-1`
pub const CHARGE_FORM_7: ParamId = ParamId(533);
/// `type=obj;default=-1`
pub const CHARGE_FORM_8: ParamId = ParamId(532);
/// `type=obj;default=229`
pub const CHARGE_FORM_SPENT: ParamId = ParamId(592);
/// `type=struct;default=-1`
pub const CHARGE_FORMS: ParamId = ParamId(2281);
/// `type=string;default=`
pub const CHARGE_FORMS_NAME: ParamId = ParamId(2524);
/// `type=coord;default=-1`
pub const CLUE_DIG_TILE: ParamId = ParamId(4681);
/// `type=obj;default=-1`
pub const CLUE_KEY: ParamId = ParamId(4685);
/// `type=int;default=0`
pub const CLUE_NEEDS_SEXTANT: ParamId = ParamId(4687);
/// `type=npc;default=-1`
pub const CLUE_NPC: ParamId = ParamId(4683);
/// `type=category;default=-1`
pub const CLUE_NPC_CATEGORY: ParamId = ParamId(4684);
/// `type=enum;default=-1`
pub const CLUE_SCAN_AREA: ParamId = ParamId(235);
/// `type=obj;default=-1`
pub const CLUE_SCROLL_BOX: ParamId = ParamId(4686);
/// `type=coord;default=-1`
pub const CLUE_SEARCH_TILE: ParamId = ParamId(4682);
/// `type=int;default=0`
pub const COMBAT_ACTION_CODE: ParamId = ParamId(2793);
/// `type=int;default=0`
pub const COMBAT_ACTION_COOLDOWN: ParamId = ParamId(2796);
/// `type=int;default=0`
pub const COMBAT_ACTION_LEVEL: ParamId = ParamId(2807);
/// `type=int;default=0`
pub const COMBAT_ACTION_MEMBERS: ParamId = ParamId(2809);
/// `type=int;default=0`
pub const COMBAT_ACTION_SKILL_SELECTOR: ParamId = ParamId(2806);
/// `type=int;default=0`
pub const CONSTRUCTION_LEVEL: ParamId = ParamId(23);
/// `type=obj;default=-1`
pub const CONSTRUCTION_MATERIAL_1: ParamId = ParamId(211);
/// `type=int;default=0`
pub const CONSTRUCTION_MATERIAL_1_COUNT: ParamId = ParamId(212);
/// `type=obj;default=-1`
pub const CONSTRUCTION_MATERIAL_2: ParamId = ParamId(213);
/// `type=int;default=0`
pub const CONSTRUCTION_MATERIAL_2_COUNT: ParamId = ParamId(214);
/// `type=obj;default=-1`
pub const CONSTRUCTION_MATERIAL_3: ParamId = ParamId(215);
/// `type=int;default=0`
pub const CONSTRUCTION_MATERIAL_3_COUNT: ParamId = ParamId(216);
/// `type=obj;default=-1`
pub const CONSTRUCTION_MATERIAL_4: ParamId = ParamId(217);
/// `type=int;default=0`
pub const CONSTRUCTION_MATERIAL_4_COUNT: ParamId = ParamId(218);
/// `type=obj;default=-1`
pub const CONSTRUCTION_MATERIAL_5: ParamId = ParamId(219);
/// `type=int;default=0`
pub const CONSTRUCTION_MATERIAL_5_COUNT: ParamId = ParamId(220);
/// `type=obj;default=-1`
pub const CONSTRUCTION_MATERIAL_6: ParamId = ParamId(221);
/// `type=int;default=0`
pub const CONSTRUCTION_MATERIAL_6_COUNT: ParamId = ParamId(222);
/// `type=int;default=0`
pub const DEATH_PROTECTION_POLICY: ParamId = ParamId(1397);
/// `type=int;default=-1`
pub const DEATH_RECLAIM_FIXED_COST: ParamId = ParamId(5089);
/// `type=int;default=-1`
pub const DEATH_SACRIFICE_FIXED_VALUE: ParamId = ParamId(5090);
/// `type=string;default=" "`
pub const DESTROY_RECLAIM_TEXT: ParamId = ParamId(5417);
/// `type=string;default=`
pub const EMOTE_NAME: ParamId = ParamId(1419);
/// `type=int;default=0`
pub const EQUIP_REQUIREMENT_LEVEL: ParamId = ParamId(750);
/// `type=stat;default=-1`
pub const EQUIP_REQUIREMENT_STAT: ParamId = ParamId(749);
/// `type=int;default=-1`
pub const EQUIPMENT_QUEST_REQUIREMENT: ParamId = ParamId(743);
/// `type=int;default=0`
pub const EXCHANGE_CATEGORY: ParamId = ParamId(2195);
/// `type=int;default=0`
pub const FOOD_CONSTITUTION_LEVEL: ParamId = ParamId(2951);
/// `type=int;default=500`
pub const GRAVE_DURATION_TICKS: ParamId = ParamId(356);
/// `type=string;default=`
pub const GUIDE_ROW_DESCRIPTION: ParamId = ParamId(2211);
/// `type=int;default=0`
pub const GUIDE_ROW_GROUP: ParamId = ParamId(2220);
/// `type=int;default=0`
pub const GUIDE_ROW_LEVEL: ParamId = ParamId(2212);
/// `type=boolean;default=0`
pub const GUIDE_ROW_MEMBERS: ParamId = ParamId(2217);
/// `type=obj;default=-1`
pub const GUIDE_ROW_OBJ: ParamId = ParamId(2213);
/// `type=string;default=`
pub const GUIDE_ROW_TITLE: ParamId = ParamId(2210);
/// `type=overlayinterface;default=-1`
pub const HERO_TAB_INTERFACE_1: ParamId = ParamId(3456);
/// `type=overlayinterface;default=-1`
pub const HERO_TAB_INTERFACE_2: ParamId = ParamId(3461);
/// `type=overlayinterface;default=-1`
pub const HERO_TAB_INTERFACE_3: ParamId = ParamId(3466);
/// `type=overlayinterface;default=-1`
pub const HERO_TAB_INTERFACE_4: ParamId = ParamId(3471);
/// `type=overlayinterface;default=-1`
pub const HERO_TAB_INTERFACE_5: ParamId = ParamId(3476);
/// `type=struct;default=-1`
pub const HERO_WINDOW_FIFTH_TAB: ParamId = ParamId(3452);
/// `type=struct;default=-1`
pub const HERO_WINDOW_FIRST_TAB: ParamId = ParamId(3448);
/// `type=struct;default=-1`
pub const HERO_WINDOW_FOURTH_TAB: ParamId = ParamId(3451);
/// `type=overlayinterface;default=-1`
pub const HERO_WINDOW_FRAME: ParamId = ParamId(3444);
/// `type=struct;default=-1`
pub const HERO_WINDOW_SECOND_TAB: ParamId = ParamId(3449);
/// `type=struct;default=-1`
pub const HERO_WINDOW_SIXTH_TAB: ParamId = ParamId(3453);
/// `type=struct;default=-1`
pub const HERO_WINDOW_THIRD_TAB: ParamId = ParamId(3450);
/// `type=int;default=0`
pub const IS_ALL_STYLE_ARMOUR: ParamId = ParamId(2824);
/// `type=int;default=0`
pub const IS_MAGIC_WEAPON: ParamId = ParamId(2827);
/// `type=int;default=0`
pub const IS_MELEE_ARMOUR: ParamId = ParamId(2821);
/// `type=int;default=0`
pub const IS_MELEE_WEAPON: ParamId = ParamId(2825);
/// `type=int;default=0`
pub const IS_RANGED_WEAPON: ParamId = ParamId(2826);
/// `type=obj;default=-1`
pub const ITEM_AUGMENTED_FORM: ParamId = ParamId(5551);
/// `type=int;default=0`
pub const ITEM_CHARGE_CAPACITY: ParamId = ParamId(3385);
/// `type=obj;default=-1`
pub const ITEM_CHARGE_PRIMARY_MATERIAL: ParamId = ParamId(4548);
/// `type=obj;default=-1`
pub const ITEM_CHARGE_RELATED_ITEM: ParamId = ParamId(3382);
/// `type=int;default=0`
pub const ITEM_FULL_REPAIR_COST: ParamId = ParamId(3383);
/// `type=int;default=0`
pub const ITEM_PRAYER_BONUS: ParamId = ParamId(2946);
/// `type=struct;default=-1`
pub const ITEM_SET_DEFINITION: ParamId = ParamId(3203);
/// `type=int;default=0`
pub const ITEM_SET_REQUIRED_PIECES: ParamId = ParamId(5818);
/// `type=int;default=0`
pub const LIFE_BONUS: ParamId = ParamId(1326);
/// `type=int;default=0`
pub const MAGIC_ACCURACY: ParamId = ParamId(3);
/// `type=int;default=0`
pub const MAGIC_AFFINITY: ParamId = ParamId(2868);
/// `type=int;default=0`
pub const MAKE_X_DEFAULT_QUANTITY: ParamId = ParamId(3379);
/// `type=coord;default=-1`
pub const MAP_LINK_COORD: ParamId = ParamId(4148);
/// `type=int;default=0`
pub const MASTER_CAPE: ParamId = ParamId(4244);
/// `type=int;default=0`
pub const MELEE_AFFINITY: ParamId = ParamId(2866);
/// `type=int;default=45`
pub const NPC_AFFINITY_RESISTED_STYLE: ParamId = ParamId(2852);
/// `type=int;default=55`
pub const NPC_AFFINITY_SAME_STYLE: ParamId = ParamId(2851);
/// `type=int;default=90`
pub const NPC_AFFINITY_SPECIFIC_WEAKNESS: ParamId = ParamId(2849);
/// `type=int;default=65`
pub const NPC_AFFINITY_VULNERABLE_STYLE: ParamId = ParamId(2850);
/// `type=int;default=0`
pub const NPC_ARMOUR: ParamId = ParamId(2865);
/// `type=coord;default=0`
pub const NPC_HOME_TILE: ParamId = ParamId(3336);
/// `type=int;default=-1`
pub const NPC_KILL_EXPERIENCE_TENTHS: ParamId = ParamId(2893);
/// `type=int;default=0`
pub const NPC_MAGIC_MAX_HIT_TENTHS: ParamId = ParamId(965);
/// `type=int;default=0`
pub const NPC_MELEE_ACCURACY: ParamId = ParamId(29);
/// `type=int;default=1`
pub const NPC_PRIMARY_DAMAGE_STYLE: ParamId = ParamId(26);
/// `type=int;default=7`
pub const NPC_SPECIFIC_WEAKNESS: ParamId = ParamId(2848);
/// `type=struct;default=-1`
pub const NPC_WEAPON_CATEGORY_REF: ParamId = ParamId(2816);
/// `type=struct;default=-1`
pub const PRAYER_TIER_GROUP: ParamId = ParamId(2962);
/// `type=spotanim;default=-1`
pub const PROJECTILE_EFFECT: ParamId = ParamId(2940);
/// `type=string;default=`
pub const QUEST_EXPERIENCE_REWARD_TEXT: ParamId = ParamId(7818);
/// `type=string;default=`
pub const QUEST_HOW_TO_START: ParamId = ParamId(7814);
/// `type=string;default=`
pub const QUEST_ITEM_REWARD_TEXT: ParamId = ParamId(7823);
/// `type=quest;default=-1`
pub const QUEST_OF_ENTRY: ParamId = ParamId(1403);
/// `type=int;default=0`
pub const RANGED_ACCURACY: ParamId = ParamId(4);
/// `type=int;default=0`
pub const RANGED_AFFINITY: ParamId = ParamId(2867);
/// `type=int;default=0`
pub const RANGED_DAMAGE: ParamId = ParamId(643);
/// `type=int;default=0`
pub const RECIPE_BANK_SLOT_1: ParamId = ParamId(5456);
/// `type=boolean;default=1`
pub const RECIPE_COUNT_FIXED_1: ParamId = ParamId(2686);
/// `type=obj;default=-1`
pub const RECIPE_ITEM_1: ParamId = ParamId(2655);
/// `type=struct;default=-1`
pub const RECIPE_ITEM_CHOICES_1: ParamId = ParamId(2675);
/// `type=int;default=0`
pub const RECIPE_ITEM_COUNT_1: ParamId = ParamId(2665);
/// `type=int;default=0`
pub const RECIPE_LEVEL_1: ParamId = ParamId(2645);
/// `type=obj;default=-1`
pub const RECIPE_REAL_PRODUCT: ParamId = ParamId(2989);
/// `type=int;default=0`
pub const RECIPE_SKILL_1: ParamId = ParamId(2640);
/// `type=obj;default=-1`
pub const RECIPE_TOOL_1: ParamId = ParamId(2650);
/// `type=struct;default=-1`
pub const RECIPE_TOOL_CHOICES_1: ParamId = ParamId(2990);
/// `type=boolean;default=1`
pub const RECIPE_XP_PER_CRAFT: ParamId = ParamId(3037);
/// `type=int;default=0`
pub const RECIPE_XP_SKILL: ParamId = ParamId(2696);
/// `type=int;default=0`
pub const RECIPE_XP_TENTHS: ParamId = ParamId(2697);
/// `type=int;default=1`
pub const RECIPE_YIELD: ParamId = ParamId(2653);
/// `type=coord;default=-1`
pub const ROOM_ARRIVAL: ParamId = ParamId(3342);
/// `type=npc;default=-1`
pub const ROOM_BOSS: ParamId = ParamId(3343);
/// `type=int;default=0`
pub const ROOM_FEE: ParamId = ParamId(3344);
/// `type=struct;default=-1`
pub const ROOM_HARD_VARIANT: ParamId = ParamId(3345);
/// `type=int;default=100`
pub const ROOM_LEGACY_MEMBER_LIMIT: ParamId = ParamId(5311);
/// `type=int;default=0`
pub const ROOM_LENGTH: ParamId = ParamId(3339);
/// `type=int;default=0`
pub const ROOM_LEVELS: ParamId = ParamId(3340);
/// `type=int;default=100`
pub const ROOM_MEMBER_LIMIT: ParamId = ParamId(3387);
/// `type=coord;default=-1`
pub const ROOM_ORIGIN: ParamId = ParamId(3337);
/// `type=int;default=0`
pub const ROOM_WIDTH: ParamId = ParamId(3338);
/// `type=obj;default=-1`
pub const SAPLING_SEED: ParamId = ParamId(4222);
/// `type=int;default=0`
pub const SECONDARY_EQUIP_LEVEL: ParamId = ParamId(752);
/// `type=stat;default=-1`
pub const SECONDARY_EQUIP_STAT: ParamId = ParamId(751);
/// `type=int;default=0`
pub const SETTINGS_MAXIMUM: ParamId = ParamId(7520);
/// `type=int;default=0`
pub const SETTINGS_MINIMUM: ParamId = ParamId(7519);
/// `type=int;default=0`
pub const SLAYER_HELMET_FAMILY: ParamId = ParamId(4076);
/// `type=int;default=0`
pub const SLAYER_HELMET_FUSED: ParamId = ParamId(4077);
/// `type=obj;default=-1`
pub const SLAYER_HELMET_FUSED_VERSION: ParamId = ParamId(4074);
/// `type=int;default=0`
pub const SLAYER_TASK_CATEGORY: ParamId = ParamId(460);
/// `type=npc;default=-1`
pub const SLAYER_TASK_EXAMPLE_NPC: ParamId = ParamId(659);
/// `type=string;default=`
pub const SLAYER_TASK_NAME: ParamId = ParamId(463);
/// `type=int;default=0`
pub const SMITHING_PROGRESS_TARGET: ParamId = ParamId(7801);
/// `type=int;default=0`
pub const SPELL_AIR_RUNES: ParamId = ParamId(2898);
/// `type=int;default=0`
pub const SPELL_ARMADYL_RUNES: ParamId = ParamId(2912);
/// `type=int;default=0`
pub const SPELL_ASTRAL_RUNES: ParamId = ParamId(2908);
/// `type=spotanim;default=-1`
pub const SPELL_ATTACK_SPOT: ParamId = ParamId(2920);
/// `type=int;default=0`
pub const SPELL_AUTOCAST: ParamId = ParamId(2874);
/// `type=int;default=0`
pub const SPELL_BASE_DAMAGE_FINE: ParamId = ParamId(2877);
/// `type=int;default=0`
pub const SPELL_BASE_XP_TENTHS: ParamId = ParamId(2891);
/// `type=int;default=0`
pub const SPELL_BLOOD_RUNES: ParamId = ParamId(2906);
/// `type=int;default=0`
pub const SPELL_BODY_RUNES: ParamId = ParamId(2903);
/// `type=int;default=0`
pub const SPELL_CHAOS_RUNES: ParamId = ParamId(2904);
/// `type=int;default=0`
pub const SPELL_COSMIC_RUNES: ParamId = ParamId(2910);
/// `type=int;default=0`
pub const SPELL_DAMAGE_CAP_LEVEL: ParamId = ParamId(2879);
/// `type=int;default=0`
pub const SPELL_DAMAGE_PER_LEVEL_FINE: ParamId = ParamId(2878);
/// `type=int;default=0`
pub const SPELL_DEATH_RUNES: ParamId = ParamId(2905);
/// `type=coord;default=-1`
pub const SPELL_DESTINATION: ParamId = ParamId(2941);
/// `type=int;default=0`
pub const SPELL_EARTH_RUNES: ParamId = ParamId(2899);
/// `type=int;default=0`
pub const SPELL_FIRE_RUNES: ParamId = ParamId(2901);
/// `type=spotanim;default=-1`
pub const SPELL_IMPACT_SPOT: ParamId = ParamId(2933);
/// `type=int;default=-1`
pub const SPELL_KIND: ParamId = ParamId(2880);
/// `type=int;default=0`
pub const SPELL_LAW_RUNES: ParamId = ParamId(2911);
/// `type=int;default=0`
pub const SPELL_MIND_RUNES: ParamId = ParamId(2902);
/// `type=string;default=`
pub const SPELL_NAME: ParamId = ParamId(2794);
/// `type=int;default=0`
pub const SPELL_NATURE_RUNES: ParamId = ParamId(2909);
/// `type=int;default=0`
pub const SPELL_SOUL_RUNES: ParamId = ParamId(2907);
/// `type=seq;default=-1`
pub const SPELL_STAFF_SEQUENCE: ParamId = ParamId(2919);
/// `type=int;default=0`
pub const SPELL_TARGET_CAST: ParamId = ParamId(2875);
/// `type=int;default=0`
pub const SPELL_WATER_RUNES: ParamId = ParamId(2900);
/// `type=int;default=0`
pub const SPELLBOOK: ParamId = ParamId(2871);
/// `type=graphic;default=-1`
pub const STATUS_DEFINITION_GRAPHIC: ParamId = ParamId(2802);
/// `type=int;default=0`
pub const STATUS_DISPLAY_CATEGORY: ParamId = ParamId(8114);
/// `type=boolean;default=0`
pub const STATUS_DISPLAY_CUSTOM_TEXT: ParamId = ParamId(8113);
/// `type=boolean;default=0`
pub const STATUS_DISPLAY_END_TIME: ParamId = ParamId(8112);
/// `type=boolean;default=0`
pub const STATUS_DISPLAY_ICON_OVERRIDE: ParamId = ParamId(8118);
/// `type=boolean;default=0`
pub const STATUS_DISPLAY_ITEM_OVERRIDE: ParamId = ParamId(8117);
/// `type=int;default=0`
pub const STATUS_DISPLAY_KIND: ParamId = ParamId(8109);
/// `type=int;default=50`
pub const STATUS_DISPLAY_PRIORITY: ParamId = ParamId(8115);
/// `type=boolean;default=0`
pub const STATUS_DISPLAY_SCRIPTED_TOOLTIP: ParamId = ParamId(8119);
/// `type=boolean;default=0`
pub const STATUS_DISPLAY_STACK_PERCENT: ParamId = ParamId(8111);
/// `type=boolean;default=0`
pub const STATUS_DISPLAY_STACKS: ParamId = ParamId(8110);
/// `type=boolean;default=0`
pub const STATUS_DISPLAY_TOOLTIP_OVERRIDE: ParamId = ParamId(8116);
/// `type=boolean;default=0`
pub const STATUS_ENTRY_ACTIVE_VISIBLE: ParamId = ParamId(8107);
/// `type=struct;default=-1`
pub const STATUS_ENTRY_DEFINITION: ParamId = ParamId(8106);
/// `type=int;default=10`
pub const STATUS_ENTRY_PRIORITY: ParamId = ParamId(8108);
/// `type=component;default=-1`
pub const STATUS_LIST_HEAD: ParamId = ParamId(8100);
/// `type=component;default=-1`
pub const STATUS_LIST_NEXT: ParamId = ParamId(8105);
/// `type=int;default=0`
pub const SUPPLIES_AIR_RUNES: ParamId = ParamId(972);
/// `type=int;default=0`
pub const SUPPLIES_EARTH_RUNES: ParamId = ParamId(974);
/// `type=int;default=0`
pub const SUPPLIES_FIRE_RUNES: ParamId = ParamId(975);
/// `type=int;default=0`
pub const SUPPLIES_WATER_RUNES: ParamId = ParamId(973);
/// `type=int;default=0`
pub const USE_LEVEL: ParamId = ParamId(771);
/// `type=stat;default=-1`
pub const USE_STAT: ParamId = ParamId(770);
/// `type=int;default=0`
pub const WEAPON_ACCURACY: ParamId = ParamId(3267);
/// `type=seq;default=-1`
pub const WEAPON_ATTACK_SEQUENCE: ParamId = ParamId(2914);
/// `type=int;default=-1`
pub const WEAPON_CATEGORY_CODE: ParamId = ParamId(2853);
/// `type=struct;default=-1`
pub const WEAPON_CATEGORY_REF: ParamId = ParamId(686);
/// `type=int;default=0`
pub const WEAPON_DAMAGE: ParamId = ParamId(641);
/// `type=int;default=0`
pub const WEAPON_SPECIAL_AVAILABLE: ParamId = ParamId(4329);
/// `type=obj;default=-1`
pub const WEAPON_SPECIAL_BASE: ParamId = ParamId(4338);
/// `type=string;default=This weapon has a special attack.`
pub const WEAPON_SPECIAL_DESCRIPTION: ParamId = ParamId(4334);
/// `type=int;default=500`
pub const WEAPON_SPECIAL_ENERGY_COST: ParamId = ParamId(4332);
/// `type=string;default=`
pub const WEAPON_SPECIAL_NAME: ParamId = ParamId(4333);
/// `type=bas;default=1426`
pub const WIELD_STANCE: ParamId = ParamId(644);
/// `type=int;default=-1`
pub const WINDOW_TAB_DESTINATION: ParamId = ParamId(3536);
/// `type=string;default=`
pub const WORN_OPTION_1: ParamId = ParamId(528);
/// `type=string;default=`
pub const WORN_OPTION_2: ParamId = ParamId(529);
/// `type=string;default=`
pub const WORN_OPTION_3: ParamId = ParamId(530);
/// `type=string;default=`
pub const WORN_OPTION_4: ParamId = ParamId(531);
/// `type=string;default=`
pub const WORN_OPTION_5: ParamId = ParamId(1211);
/// `type=string;default=`
pub const WORN_OPTION_6: ParamId = ParamId(6712);
/// `type=string;default=`
pub const WORN_OPTION_7: ParamId = ParamId(6713);
/// `type=string;default=`
pub const WORN_OPTION_8: ParamId = ParamId(6714);
/// `type=int;default=0`
pub const XP_REWARD_ITEM: ParamId = ParamId(59);
/// `type=int;default=0`
pub const XP_REWARD_LEVEL: ParamId = ParamId(124);
/// `type=stat;default=-1`
pub const XP_REWARD_SKILL: ParamId = ParamId(4242);
/// `type=int;default=0`
pub const XP_REWARD_TENTHS: ParamId = ParamId(58);
