// Generated by `npm --prefix server run sym -- gen` from revisions/910/symbols/quest.sym. Do not edit: add symbols
// with `npm --prefix server run sym -- add` (docs/symbols.md).

//! The named quest ids of revision 910.

use crate::QuestId;

/// `name=Cabin Fever`
pub const CABIN_FEVER_QUEST: QuestId = QuestId(296);
/// `name=Cook's Assistant`
pub const COOKS_ASSISTANT_QUEST: QuestId = QuestId(257);
/// `name=A Fairy Tale II - Cure a Queen`
pub const FAIRY_TALE_CURE_A_QUEEN: QuestId = QuestId(309);
/// `name=A Fairy Tale I - Growing Pains`
pub const FAIRY_TALE_GROWING_PAINS: QuestId = QuestId(297);
/// `name=A Fairy Tale III - Battle at Ork's Rift`
pub const FAIRY_TALE_ORKS_RIFT: QuestId = QuestId(337);
/// `name=Family Crest`
pub const FAMILY_CREST: QuestId = QuestId(116);
/// `name=Rune Mysteries`
pub const RUNE_MYSTERIES: QuestId = QuestId(358);
/// `name=Sheep Shearer (miniquest)`
pub const SHEEP_SHEARER_MINIQUEST: QuestId = QuestId(173);
/// `name=The Grand Tree`
pub const THE_GRAND_TREE_QUEST: QuestId = QuestId(269);
/// `name=The Restless Ghost`
pub const THE_RESTLESS_GHOST: QuestId = QuestId(27);
/// `name=Tree Gnome Village`
pub const TREE_GNOME_VILLAGE_QUEST: QuestId = QuestId(267);
