// Generated by `npm --prefix server run sym -- gen` from revisions/910/symbols/spot.sym. Do not edit: add symbols
// with `npm --prefix server run sym -- add` (docs/symbols.md).

//! The named spot ids of revision 910.

use crate::SpotId;

/// `model=28249;seq=11990`
pub const ARMADYL_GODSWORD_SPECIAL: SpotId = SpotId(2113);
/// `model=28211;seq=11992`
pub const BANDOS_GODSWORD_SPECIAL: SpotId = SpotId(2114);
/// `model=3092;seq=668`
pub const CONFUSE_CAST: SpotId = SpotId(102);
/// `model=44811;seq=10965`
pub const DRAGON_CLAWS_SPECIAL: SpotId = SpotId(1950);
/// `model=78980;seq=18531`
pub const DRAGON_CLAWS_TARGET: SpotId = SpotId(3527);
/// `model=3478;seq=1063`
pub const DRAGON_DAGGER_SPECIAL: SpotId = SpotId(252);
/// `model=3479;seq=1061`
pub const DRAGON_MACE_SPECIAL: SpotId = SpotId(251);
/// `model=57445;seq=3253`
pub const FAIRY_RING_ARRIVE: SpotId = SpotId(2671);
/// `model=57445;seq=3252`
pub const FAIRY_RING_DEPART: SpotId = SpotId(2670);
/// `model=71927;seq=22617`
pub const GIANT_MOLE_BURROW: SpotId = SpotId(4565);
/// `model=71927;seq=22616`
pub const GIANT_MOLE_EMERGE: SpotId = SpotId(4564);
/// `model=93390;seq=22624`
pub const GIANT_MOLE_ENRAGE: SpotId = SpotId(4563);
/// `model=93389;seq=22628`
pub const GIANT_MOLE_FALLING_ROCKS: SpotId = SpotId(4566);
/// `model=93391;seq=22623`
pub const GIANT_MOLE_STOMP: SpotId = SpotId(4562);
/// `model=93371;seq=22629`
pub const GIANT_MOLE_TREMOR: SpotId = SpotId(4569);
/// `model=5415;seq=1668`
pub const GRANITE_MAUL_SPECIAL: SpotId = SpotId(340);
/// `model=1202;seq=115`
pub const HOME_TELEPORT_CAST_1: SpotId = SpotId(800);
/// `model=1202;seq=116`
pub const HOME_TELEPORT_CAST_2: SpotId = SpotId(801);
/// `model=1202;seq=117`
pub const HOME_TELEPORT_CAST_3: SpotId = SpotId(802);
/// `model=1202;seq=118`
pub const HOME_TELEPORT_CAST_4: SpotId = SpotId(803);
/// `model=1202;seq=137`
pub const HOME_TELEPORT_CAST_5: SpotId = SpotId(804);
/// `model=76656;seq=17794`
pub const KBD_FIRE_CAST: SpotId = SpotId(3441);
/// `model=77898;seq=17794`
pub const KBD_FIRE_FLIGHT: SpotId = SpotId(3442);
/// `model=77898;seq=17794`
pub const KBD_FIRE_IMPACT: SpotId = SpotId(3443);
/// `model=77901;seq=17790`
pub const KBD_ICE_CAST: SpotId = SpotId(3438);
/// `model=77901;seq=17787`
pub const KBD_ICE_FLIGHT: SpotId = SpotId(3439);
/// `model=77901;seq=17791`
pub const KBD_ICE_IMPACT: SpotId = SpotId(3440);
/// `model=77900;seq=17792`
pub const KBD_POISON_CAST: SpotId = SpotId(3435);
/// `model=77900;seq=17787`
pub const KBD_POISON_FLIGHT: SpotId = SpotId(3436);
/// `model=77900;seq=17793`
pub const KBD_POISON_IMPACT: SpotId = SpotId(3437);
/// `model=77899;seq=17788`
pub const KBD_SHOCK_CAST: SpotId = SpotId(3432);
/// `model=77899;seq=17787`
pub const KBD_SHOCK_FLIGHT: SpotId = SpotId(3433);
/// `model=77899;seq=17789`
pub const KBD_SHOCK_IMPACT: SpotId = SpotId(3434);
/// `model=68741;seq=16389`
pub const LODESTONE_ARRIVE: SpotId = SpotId(3018);
/// `model=68741;seq=16390`
pub const LODESTONE_DEPART: SpotId = SpotId(3017);
/// `model=74211;seq=32534`
pub const ROCKERTUNITY_LARGE_ROCK: SpotId = SpotId(7165);
/// `model=74210;seq=32534`
pub const ROCKERTUNITY_SMALL_ROCK: SpotId = SpotId(7164);
/// `model=28195;seq=11994`
pub const SARADOMIN_GODSWORD_SPECIAL: SpotId = SpotId(2109);
/// `model=32718;seq=8942`
pub const STANDARD_TELEPORT_ARRIVAL: SpotId = SpotId(1577);
/// `model=32718;seq=8940`
pub const STANDARD_TELEPORT_DEPARTURE: SpotId = SpotId(1576);
/// `model=3070;seq=1054`
pub const THIEVING_STUN: SpotId = SpotId(245);
/// `model=2908;seq=1375`
pub const UNDERGROWTH_BANNER: SpotId = SpotId(155);
/// `model=48116;seq=7069`
pub const ZAMORAK_GODSWORD_SPECIAL: SpotId = SpotId(1221);
/// `model=48114;seq=3483`
pub const ZAMORAK_GODSWORD_TARGET: SpotId = SpotId(2104);
