// Generated by `npm --prefix server run sym -- gen` from revisions/910/symbols/varbit.sym. Do not edit: add symbols
// with `npm --prefix server run sym -- add` (docs/symbols.md).

//! The named varbit ids of revision 910.

use crate::VarbitId;

/// `varp=3148;bits=18-29`
pub const ABYSS_OBSTACLE_RING: VarbitId = VarbitId(16267);
/// `varp=5860;bits=0-3`
pub const ACTION_BAR_DISPLAY_2: VarbitId = VarbitId(29138);
/// `varp=5860;bits=4-7`
pub const ACTION_BAR_DISPLAY_3: VarbitId = VarbitId(29139);
/// `varp=5860;bits=8-11`
pub const ACTION_BAR_DISPLAY_4: VarbitId = VarbitId(29140);
/// `varp=5860;bits=12-15`
pub const ACTION_BAR_DISPLAY_5: VarbitId = VarbitId(29141);
/// `varp=682;bits=29-31`
pub const ACTION_BAR_EXTRA_ENTITLEMENT: VarbitId = VarbitId(27893);
/// `varp=739;bits=4-16`
pub const ACTION_BAR_FIRST_ACTION: VarbitId = VarbitId(1748);
/// `varp=739;bits=0-3`
pub const ACTION_BAR_FIRST_TYPE: VarbitId = VarbitId(1747);
/// `varp=2852;bits=0-7`
pub const ACTION_BAR_KEY_1: VarbitId = VarbitId(18882);
/// `varp=682;bits=4-4`
pub const ACTION_BAR_LOCKED: VarbitId = VarbitId(1892);
/// `varp=2859;bits=0-1`
pub const ACTION_BAR_MODIFIER_1: VarbitId = VarbitId(18908);
/// `varp=740;bits=4-16`
pub const ACTION_BAR_SECOND_ACTION: VarbitId = VarbitId(1750);
/// `varp=740;bits=0-3`
pub const ACTION_BAR_SECOND_TYPE: VarbitId = VarbitId(1749);
/// `varp=741;bits=4-16`
pub const ACTION_BAR_THIRD_ACTION: VarbitId = VarbitId(1752);
/// `varp=741;bits=0-3`
pub const ACTION_BAR_THIRD_TYPE: VarbitId = VarbitId(1751);
/// `varp=3272;bits=0-0`
pub const ACTIVE_PRAYER_DEFENCE: VarbitId = VarbitId(16739);
/// `varp=3272;bits=5-5`
pub const ACTIVE_PRAYER_KEEP_ITEM: VarbitId = VarbitId(16744);
/// `varp=3272;bits=13-13`
pub const ACTIVE_PRAYER_MAGIC_ACCURACY: VarbitId = VarbitId(16752);
/// `varp=3272;bits=15-15`
pub const ACTIVE_PRAYER_MAGIC_DAMAGE: VarbitId = VarbitId(16754);
/// `varp=3272;bits=6-6`
pub const ACTIVE_PRAYER_MAGIC_GUARD: VarbitId = VarbitId(16745);
/// `varp=3272;bits=2-2`
pub const ACTIVE_PRAYER_MELEE_ACCURACY: VarbitId = VarbitId(16741);
/// `varp=3272;bits=1-1`
pub const ACTIVE_PRAYER_MELEE_DAMAGE: VarbitId = VarbitId(16740);
/// `varp=3272;bits=8-8`
pub const ACTIVE_PRAYER_MELEE_GUARD: VarbitId = VarbitId(16747);
/// `varp=3272;bits=12-12`
pub const ACTIVE_PRAYER_RANGED_ACCURACY: VarbitId = VarbitId(16751);
/// `varp=3272;bits=14-14`
pub const ACTIVE_PRAYER_RANGED_DAMAGE: VarbitId = VarbitId(16753);
/// `varp=3272;bits=7-7`
pub const ACTIVE_PRAYER_RANGED_GUARD: VarbitId = VarbitId(16746);
/// `varp=4;bits=0-1`
pub const ACTIVE_SPELLBOOK: VarbitId = VarbitId(0);
/// `varp=1584;bits=9-9`
pub const AGILITY_PYRAMID_TOP_TAKEN: VarbitId = VarbitId(4955);
/// `varp=1103;bits=1-1`
pub const AMMO_MOULD_ON_BELT: VarbitId = VarbitId(2989);
/// `varp=1102;bits=2-2`
pub const AMULET_MOULD_ON_BELT: VarbitId = VarbitId(2970);
/// `varp=0;bits=1-16`
pub const AUTOCAST_ACTION: VarbitId = VarbitId(43);
/// `varp=0;bits=0-0`
pub const AUTOCAST_ENABLED: VarbitId = VarbitId(42);
/// `varp=607;bits=0-1`
pub const BARBARIAN_BAREHANDED_FISHING: VarbitId = VarbitId(1616);
/// `varp=1103;bits=15-15`
pub const BARBARIAN_ROD_ON_BELT: VarbitId = VarbitId(3003);
/// `varp=1513;bits=0-0`
pub const BARROWS_AHRIM_DEFEATED: VarbitId = VarbitId(4554);
/// `varp=1513;bits=1-1`
pub const BARROWS_DHAROK_DEFEATED: VarbitId = VarbitId(4555);
/// `varp=1513;bits=2-2`
pub const BARROWS_GUTHAN_DEFEATED: VarbitId = VarbitId(4556);
/// `varp=1513;bits=3-3`
pub const BARROWS_KARIL_DEFEATED: VarbitId = VarbitId(4557);
/// `varp=1513;bits=16-16`
pub const BARROWS_REWARD_OPENED: VarbitId = VarbitId(4561);
/// `varp=1513;bits=4-4`
pub const BARROWS_TORAG_DEFEATED: VarbitId = VarbitId(4558);
/// `varp=1513;bits=17-31`
pub const BARROWS_TOTAL_KILLS: VarbitId = VarbitId(4562);
/// `varp=1513;bits=5-5`
pub const BARROWS_VERAC_DEFEATED: VarbitId = VarbitId(4559);
/// `varp=5863;bits=4-4`
pub const BEER_GLASS_DESTROY: VarbitId = VarbitId(1727);
/// `varp=5699;bits=6-7`
pub const BELT_EXPLOSIVE_SHAKER_TIER: VarbitId = VarbitId(28225);
/// `varp=1102;bits=24-27`
pub const BELT_HATCHET_TIER: VarbitId = VarbitId(18522);
/// `varp=1103;bits=24-26`
pub const BELT_MACHETE_TIER: VarbitId = VarbitId(4935);
/// `varp=7903;bits=2-9`
pub const BELT_PICKAXE_INDEX: VarbitId = VarbitId(43044);
/// `varp=1103;bits=13-13`
pub const BIG_FISHING_NET_ON_BELT: VarbitId = VarbitId(3001);
/// `varp=674;bits=4-5`
pub const BLOODWOOD_CHAOS_TEMPLE_STATE: VarbitId = VarbitId(1703);
/// `varp=1103;bits=2-2`
pub const BOLT_MOULD_ON_BELT: VarbitId = VarbitId(2990);
/// `varp=5699;bits=8-8`
pub const BONECRUSHER_ON_BELT: VarbitId = VarbitId(28226);
/// `varp=1103;bits=3-3`
pub const BRACELET_MOULD_ON_BELT: VarbitId = VarbitId(2991);
/// `varp=2868;bits=8-15`
pub const CAMERA_DOWN_KEY: VarbitId = VarbitId(18959);
/// `varp=2868;bits=16-23`
pub const CAMERA_LEFT_KEY: VarbitId = VarbitId(18960);
/// `varp=2868;bits=24-31`
pub const CAMERA_RIGHT_KEY: VarbitId = VarbitId(18961);
/// `varp=2868;bits=0-7`
pub const CAMERA_UP_KEY: VarbitId = VarbitId(18958);
/// `varp=1042;bits=0-7`
pub const CANOE_STATION_LUMBRIDGE_STATE: VarbitId = VarbitId(2121);
/// `varp=16;bits=8-15`
pub const CATHERBY_FLOWER_PATCH_STATE: VarbitId = VarbitId(73);
/// `varp=11;bits=24-31`
pub const CATHERBY_FRUIT_TREE_PATCH_STATE: VarbitId = VarbitId(51);
/// `varp=1103;bits=18-18`
pub const CHAIN_LINK_MOULD_ON_BELT: VarbitId = VarbitId(3006);
/// `varp=5987;bits=8-8`
pub const CHARGE_PACK_ON_BELT: VarbitId = VarbitId(30225);
/// `varp=5699;bits=10-10`
pub const CHARMING_IMP_ON_BELT: VarbitId = VarbitId(28228);
/// `varp=1103;bits=17-17`
pub const CHART_ON_BELT: VarbitId = VarbitId(3005);
/// `varp=1772;bits=2-2`
pub const CHAT_PANEL_1_SHOWS_ASSIST: VarbitId = VarbitId(18799);
/// `varp=1774;bits=26-26`
pub const CHAT_PANEL_1_SHOWS_BROADCASTS: VarbitId = VarbitId(20828);
/// `varp=1772;bits=6-6`
pub const CHAT_PANEL_1_SHOWS_CLAN: VarbitId = VarbitId(18803);
/// `varp=1772;bits=5-5`
pub const CHAT_PANEL_1_SHOWS_FRIENDS_CHAT: VarbitId = VarbitId(18802);
/// `varp=1772;bits=0-0`
pub const CHAT_PANEL_1_SHOWS_GAME: VarbitId = VarbitId(18797);
/// `varp=4739;bits=15-15`
pub const CHAT_PANEL_1_SHOWS_GROUP: VarbitId = VarbitId(24578);
/// `varp=1772;bits=7-7`
pub const CHAT_PANEL_1_SHOWS_GUEST_CLAN: VarbitId = VarbitId(18804);
/// `varp=1772;bits=4-4`
pub const CHAT_PANEL_1_SHOWS_PRIVATE: VarbitId = VarbitId(18801);
/// `varp=1772;bits=3-3`
pub const CHAT_PANEL_1_SHOWS_PUBLIC: VarbitId = VarbitId(18800);
/// `varp=1772;bits=1-1`
pub const CHAT_PANEL_1_SHOWS_TRADE: VarbitId = VarbitId(18798);
/// `varp=1772;bits=17-17`
pub const CHAT_PANEL_2_SHOWS_ASSIST: VarbitId = VarbitId(18814);
/// `varp=1774;bits=27-27`
pub const CHAT_PANEL_2_SHOWS_BROADCASTS: VarbitId = VarbitId(20829);
/// `varp=1772;bits=21-21`
pub const CHAT_PANEL_2_SHOWS_CLAN: VarbitId = VarbitId(18818);
/// `varp=1772;bits=20-20`
pub const CHAT_PANEL_2_SHOWS_FRIENDS_CHAT: VarbitId = VarbitId(18817);
/// `varp=1772;bits=15-15`
pub const CHAT_PANEL_2_SHOWS_GAME: VarbitId = VarbitId(18812);
/// `varp=4739;bits=16-16`
pub const CHAT_PANEL_2_SHOWS_GROUP: VarbitId = VarbitId(24579);
/// `varp=1772;bits=22-22`
pub const CHAT_PANEL_2_SHOWS_GUEST_CLAN: VarbitId = VarbitId(18819);
/// `varp=1772;bits=19-19`
pub const CHAT_PANEL_2_SHOWS_PRIVATE: VarbitId = VarbitId(18816);
/// `varp=1772;bits=18-18`
pub const CHAT_PANEL_2_SHOWS_PUBLIC: VarbitId = VarbitId(18815);
/// `varp=1772;bits=16-16`
pub const CHAT_PANEL_2_SHOWS_TRADE: VarbitId = VarbitId(18813);
/// `varp=1102;bits=3-3`
pub const CHISEL_ON_BELT: VarbitId = VarbitId(2971);
/// `varp=627;bits=10-11`
pub const COMBAT_ABILITY_MODE: VarbitId = VarbitId(21685);
/// `varp=2493;bits=4-4`
pub const COOKS_ASSISTANT_ASKED_MILLER: VarbitId = VarbitId(12208);
/// `varp=2493;bits=3-3`
pub const COOKS_ASSISTANT_DECLINED: VarbitId = VarbitId(12207);
/// `varp=2493;bits=1-1`
pub const COOKS_ASSISTANT_EGG_GIVEN: VarbitId = VarbitId(12205);
/// `varp=2493;bits=0-0`
pub const COOKS_ASSISTANT_FLOUR_GIVEN: VarbitId = VarbitId(12204);
/// `varp=2493;bits=2-2`
pub const COOKS_ASSISTANT_MILK_GIVEN: VarbitId = VarbitId(12206);
/// `varp=1102;bits=9-9`
pub const CRAYFISH_CAGE_ON_BELT: VarbitId = VarbitId(2977);
/// `varp=5699;bits=5-5`
pub const CRYSTAL_CHIME_ON_BELT: VarbitId = VarbitId(28224);
/// `varp=659;bits=1-15`
pub const CURRENT_LIFE_POINTS: VarbitId = VarbitId(1668);
/// `varp=3274;bits=0-14`
pub const CURRENT_PRAYER_POINTS: VarbitId = VarbitId(16736);
/// `varp=5435;bits=27-28`
pub const DEATH_RECLAIM_DANGER_MODE: VarbitId = VarbitId(1675);
/// `varp=5435;bits=25-26`
pub const DEATH_RECLAIM_MODE: VarbitId = VarbitId(28118);
/// `varp=5435;bits=0-7`
pub const DEATH_RECLAIM_PROTECTED_COUNT: VarbitId = VarbitId(28114);
/// `varp=5435;bits=8-15`
pub const DEATH_RECLAIM_SAVED_COUNT: VarbitId = VarbitId(28115);
/// `varp=5435;bits=16-23`
pub const DEATH_RECLAIM_TOTAL_COUNT: VarbitId = VarbitId(28116);
/// `varp=3705;bits=24-27`
pub const DEFENSIVE_BOOK_CATEGORY: VarbitId = VarbitId(36453);
/// `varp=3705;bits=28-31`
pub const DEFENSIVE_BOOK_TAB: VarbitId = VarbitId(36454);
/// `varp=2151;bits=0-14`
pub const DESERT_TREASURE_PROGRESS: VarbitId = VarbitId(9482);
/// `varp=4674;bits=0-15`
pub const EASY_TRAIL_CLUE: VarbitId = VarbitId(23235);
/// `varp=1580;bits=0-3`
pub const EASY_TRAIL_STEPS_LEFT: VarbitId = VarbitId(28015);
/// `varp=4675;bits=16-31`
pub const ELITE_TRAIL_CLUE: VarbitId = VarbitId(23238);
/// `varp=1580;bits=12-15`
pub const ELITE_TRAIL_STEPS_LEFT: VarbitId = VarbitId(28018);
/// `varp=5142;bits=9-16`
pub const ENCOUNTER_COMBAT: VarbitId = VarbitId(27139);
/// `varp=5142;bits=19-19`
pub const ENCOUNTER_HARD: VarbitId = VarbitId(27141);
/// `varp=5142;bits=0-8`
pub const ENCOUNTER_LIMIT: VarbitId = VarbitId(27138);
/// `varp=5142;bits=20-20`
pub const ENCOUNTER_PRACTICE: VarbitId = VarbitId(27142);
/// `varp=5143;bits=0-13`
pub const ENCOUNTER_PROTECTION: VarbitId = VarbitId(27143);
/// `varp=5140;bits=9-16`
pub const ENCOUNTER_SAVED_COMBAT: VarbitId = VarbitId(27146);
/// `varp=5140;bits=0-8`
pub const ENCOUNTER_SAVED_LIMIT: VarbitId = VarbitId(27145);
/// `varp=5141;bits=0-13`
pub const ENCOUNTER_SAVED_PROTECTION: VarbitId = VarbitId(27150);
/// `varp=5140;bits=17-18`
pub const ENCOUNTER_SAVED_SPEED: VarbitId = VarbitId(27147);
/// `varp=5142;bits=17-18`
pub const ENCOUNTER_SPEED: VarbitId = VarbitId(27140);
/// `varp=3709;bits=0-3`
pub const EXCHANGE_WINDOW_TAB: VarbitId = VarbitId(19000);
/// `varp=94;bits=25-25`
pub const EXPERIENCE_COUNTER_HIDDEN: VarbitId = VarbitId(19964);
/// `varp=94;bits=15-15`
pub const EXPERIENCE_DROPS_DISABLED: VarbitId = VarbitId(228);
/// `varp=2478;bits=0-2`
pub const FAIRY_RING_DIAL_1: VarbitId = VarbitId(12072);
/// `varp=2478;bits=3-5`
pub const FAIRY_RING_DIAL_2: VarbitId = VarbitId(12073);
/// `varp=2478;bits=6-8`
pub const FAIRY_RING_DIAL_3: VarbitId = VarbitId(12074);
/// `varp=1102;bits=10-10`
pub const FISHING_ROD_ON_BELT: VarbitId = VarbitId(2978);
/// `varp=1102;bits=11-11`
pub const FLY_FISHING_ROD_ON_BELT: VarbitId = VarbitId(2979);
/// `varp=5699;bits=3-3`
pub const FUNGICIDE_SHAKER_ON_BELT: VarbitId = VarbitId(28222);
/// `varp=8172;bits=0-9`
pub const GAMEPLAY_SETTINGS_CATEGORY: VarbitId = VarbitId(42101);
/// `varp=1103;bits=8-8`
pub const GARDENING_TROWEL_ON_BELT: VarbitId = VarbitId(2996);
/// `varp=3214;bits=18-29`
pub const GIANT_POUCH_ESSENCE: VarbitId = VarbitId(16500);
/// `varp=3215;bits=6-7`
pub const GIANT_POUCH_ESSENCE_KIND: VarbitId = VarbitId(16505);
/// `varp=1103;bits=4-4`
pub const GLASSBLOWING_PIPE_ON_BELT: VarbitId = VarbitId(2992);
/// `varp=5699;bits=19-19`
pub const GOLD_ACCUMULATOR_ON_BELT: VarbitId = VarbitId(38660);
/// `varp=1103;bits=30-30`
pub const GRAPPLING_HOOK_ON_BELT: VarbitId = VarbitId(40075);
/// `varp=7958;bits=9-9`
pub const GREATER_BARGE_UNLOCKED: VarbitId = VarbitId(41438);
/// `varp=6943;bits=30-30`
pub const GREATER_DAZING_SHOT_UNLOCKED: VarbitId = VarbitId(35816);
/// `varp=7958;bits=7-7`
pub const GREATER_FLURRY_UNLOCKED: VarbitId = VarbitId(41436);
/// `varp=7958;bits=8-8`
pub const GREATER_FURY_UNLOCKED: VarbitId = VarbitId(41437);
/// `varp=3017;bits=19-30`
pub const GWD_ARMADYL_KILLS: VarbitId = VarbitId(15163);
/// `varp=3018;bits=0-11`
pub const GWD_BANDOS_KILLS: VarbitId = VarbitId(15165);
/// `varp=3017;bits=7-18`
pub const GWD_SARADOMIN_KILLS: VarbitId = VarbitId(15162);
/// `varp=3018;bits=12-23`
pub const GWD_ZAMORAK_KILLS: VarbitId = VarbitId(15166);
/// `varp=1102;bits=16-16`
pub const HAMMER_ON_BELT: VarbitId = VarbitId(2984);
/// `varp=1581;bits=8-8`
pub const HARD_CLUE_FOE_DEFEATED: VarbitId = VarbitId(28023);
/// `varp=4675;bits=0-15`
pub const HARD_TRAIL_CLUE: VarbitId = VarbitId(23237);
/// `varp=1581;bits=7-7`
pub const HARD_TRAIL_EMOTE_DONE: VarbitId = VarbitId(28022);
/// `varp=1580;bits=8-11`
pub const HARD_TRAIL_STEPS_LEFT: VarbitId = VarbitId(28017);
/// `varp=1102;bits=12-12`
pub const HARPOON_ON_BELT: VarbitId = VarbitId(2980);
/// `varp=1102;bits=17-17`
pub const HATCHET_ON_BELT: VarbitId = VarbitId(2985);
/// `varp=5699;bits=11-11`
pub const HERBICIDE_ON_BELT: VarbitId = VarbitId(28229);
/// `varp=3708;bits=0-8`
pub const HERO_WINDOW_KIND: VarbitId = VarbitId(18994);
/// `varp=1102;bits=4-4`
pub const HOLY_MOULD_ON_BELT: VarbitId = VarbitId(2972);
/// `varp=483;bits=10-10`
pub const HOUSE_BUILD_MODE: VarbitId = VarbitId(1537);
/// `varp=5699;bits=2-2`
pub const ICE_SHAKER_ON_BELT: VarbitId = VarbitId(28221);
/// `varp=2277;bits=14-16`
pub const INCOMITATUS_TREE_STATE: VarbitId = VarbitId(10479);
/// `varp=7903;bits=1-1`
pub const INSECT_REPELLENT_ON_BELT: VarbitId = VarbitId(42126);
/// `varp=2170;bits=22-22`
pub const INSTANCE_FEE_DISCOUNT: VarbitId = VarbitId(22912);
/// `varp=3814;bits=1-1`
pub const INTERFACE_LAYOUT_LOCK: VarbitId = VarbitId(19925);
/// `varp=3814;bits=5-11`
pub const INTERFACE_SKIN: VarbitId = VarbitId(22875);
/// `varp=5987;bits=7-7`
pub const INVENTORS_TOOLS_ON_BELT: VarbitId = VarbitId(30224);
/// `varp=4818;bits=0-0`
pub const IRONMAN_MODE_ACTIVE: VarbitId = VarbitId(20806);
/// `varp=6389;bits=21-21`
pub const KAI_UNDRI_GLIDER_UNLOCKED: VarbitId = VarbitId(33889);
/// `varp=1305;bits=3-3`
pub const KALPHITE_HIVE_SURFACE_ROPE: VarbitId = VarbitId(16280);
/// `varp=1305;bits=4-4`
pub const KALPHITE_QUEEN_ENTRY_ROPE: VarbitId = VarbitId(16281);
/// `varp=1103;bits=29-29`
pub const KEY_RING_ON_BELT: VarbitId = VarbitId(40074);
/// `varp=1102;bits=0-0`
pub const KNIFE_ON_BELT: VarbitId = VarbitId(2968);
/// `varp=3214;bits=9-17`
pub const LARGE_POUCH_ESSENCE: VarbitId = VarbitId(16499);
/// `varp=3215;bits=4-5`
pub const LARGE_POUCH_ESSENCE_KIND: VarbitId = VarbitId(16504);
/// `varp=1207;bits=18-20`
pub const LARUPIA_PIT_STATE: VarbitId = VarbitId(3134);
/// `varp=3680;bits=20-20`
pub const LEGACY_COMBAT_ACTIVE: VarbitId = VarbitId(27168);
/// `varp=689;bits=26-28`
pub const LEGACY_COMBAT_STANCE: VarbitId = VarbitId(1903);
/// `varp=3680;bits=21-21`
pub const LEGACY_INTERFACE_MODE: VarbitId = VarbitId(27169);
/// `varp=3680;bits=10-10`
pub const LEGACY_MAP_ICONS: VarbitId = VarbitId(22874);
/// `varp=3465;bits=8-14`
pub const LEGACY_SELECTED_WINDOW: VarbitId = VarbitId(22877);
/// `varp=1102;bits=13-13`
pub const LOBSTER_POT_ON_BELT: VarbitId = VarbitId(2981);
/// `varp=1103;bits=31-31`
pub const LOCKPICK_ON_BELT: VarbitId = VarbitId(40234);
/// `varp=3;bits=0-0`
pub const LODESTONE_AL_KHARID_UNLOCKED: VarbitId = VarbitId(28);
/// `varp=3;bits=1-1`
pub const LODESTONE_ARDOUGNE_UNLOCKED: VarbitId = VarbitId(29);
/// `varp=3;bits=23-23`
pub const LODESTONE_ASHDALE_UNLOCKED: VarbitId = VarbitId(22430);
/// `varp=3;bits=2-2`
pub const LODESTONE_BURTHORPE_UNLOCKED: VarbitId = VarbitId(30);
/// `varp=3;bits=15-15`
pub const LODESTONE_CANIFIS_UNLOCKED: VarbitId = VarbitId(18523);
/// `varp=3;bits=3-3`
pub const LODESTONE_CATHERBY_UNLOCKED: VarbitId = VarbitId(31);
/// `varp=3;bits=4-4`
pub const LODESTONE_DRAYNOR_UNLOCKED: VarbitId = VarbitId(32);
/// `varp=3;bits=16-16`
pub const LODESTONE_EAGLES_PEAK_UNLOCKED: VarbitId = VarbitId(18524);
/// `varp=3;bits=5-5`
pub const LODESTONE_EDGEVILLE_UNLOCKED: VarbitId = VarbitId(33);
/// `varp=3;bits=6-6`
pub const LODESTONE_FALADOR_UNLOCKED: VarbitId = VarbitId(34);
/// `varp=3;bits=17-17`
pub const LODESTONE_FREMENNIK_PROVINCE_UNLOCKED: VarbitId = VarbitId(18525);
/// `varp=3;bits=18-18`
pub const LODESTONE_KARAMJA_UNLOCKED: VarbitId = VarbitId(18526);
/// `varp=3;bits=7-7`
pub const LODESTONE_LUMBRIDGE_UNLOCKED: VarbitId = VarbitId(35);
/// `varp=7040;bits=0-0`
pub const LODESTONE_MENAPHOS_UNLOCKED: VarbitId = VarbitId(36173);
/// `varp=3;bits=19-19`
pub const LODESTONE_OOGLOG_UNLOCKED: VarbitId = VarbitId(18527);
/// `varp=3;bits=8-8`
pub const LODESTONE_PORT_SARIM_UNLOCKED: VarbitId = VarbitId(36);
/// `varp=3;bits=25-30`
pub const LODESTONE_PREVIOUS_DESTINATION: VarbitId = VarbitId(41);
/// `varp=3;bits=24-24`
pub const LODESTONE_PRIFDDINAS_UNLOCKED: VarbitId = VarbitId(24967);
/// `varp=3;bits=9-9`
pub const LODESTONE_SEERS_VILLAGE_UNLOCKED: VarbitId = VarbitId(37);
/// `varp=3;bits=10-10`
pub const LODESTONE_TAVERLEY_UNLOCKED: VarbitId = VarbitId(38);
/// `varp=3;bits=20-20`
pub const LODESTONE_TIRANNWN_UNLOCKED: VarbitId = VarbitId(18528);
/// `varp=3;bits=11-11`
pub const LODESTONE_VARROCK_UNLOCKED: VarbitId = VarbitId(39);
/// `varp=3;bits=21-21`
pub const LODESTONE_WILDERNESS_VOLCANO_UNLOCKED: VarbitId = VarbitId(18529);
/// `varp=3;bits=12-12`
pub const LODESTONE_YANILLE_UNLOCKED: VarbitId = VarbitId(40);
/// `varp=10;bits=24-31`
pub const LUMBRIDGE_TREE_PATCH_STATE: VarbitId = VarbitId(47);
/// `varp=2253;bits=0-19`
pub const LUNAR_DIPLOMACY_PROGRESS: VarbitId = VarbitId(10236);
/// `varp=1103;bits=14-14`
pub const MACHETE_ON_BELT: VarbitId = VarbitId(3002);
/// `varp=1103;bits=22-22`
pub const MAGIC_SECATEURS_ON_BELT: VarbitId = VarbitId(27430);
/// `varp=627;bits=6-7`
pub const MAGIC_TRAINING_MASK: VarbitId = VarbitId(1908);
/// `varp=1103;bits=23-23`
pub const MAGIC_WATERING_CAN_ON_BELT: VarbitId = VarbitId(27431);
/// `varp=627;bits=28-28`
pub const MANUAL_SPELL_CASTING: VarbitId = VarbitId(22843);
/// `varp=1581;bits=12-12`
pub const MASTER_CLUE_FOE_DEFEATED: VarbitId = VarbitId(39442);
/// `varp=1580;bits=16-19`
pub const MASTER_TRAIL_STEPS_LEFT: VarbitId = VarbitId(39440);
/// `varp=3214;bits=3-8`
pub const MEDIUM_POUCH_ESSENCE: VarbitId = VarbitId(16498);
/// `varp=3215;bits=2-3`
pub const MEDIUM_POUCH_ESSENCE_KIND: VarbitId = VarbitId(16503);
/// `varp=4674;bits=16-31`
pub const MEDIUM_TRAIL_CLUE: VarbitId = VarbitId(23236);
/// `varp=1581;bits=5-5`
pub const MEDIUM_TRAIL_EMOTE_DONE: VarbitId = VarbitId(28020);
/// `varp=1580;bits=4-7`
pub const MEDIUM_TRAIL_STEPS_LEFT: VarbitId = VarbitId(28016);
/// `varp=3705;bits=0-3`
pub const MELEE_BOOK_CATEGORY: VarbitId = VarbitId(18786);
/// `varp=3705;bits=4-7`
pub const MELEE_BOOK_TAB: VarbitId = VarbitId(18787);
/// `varp=627;bits=0-3`
pub const MELEE_TRAINING_MASK: VarbitId = VarbitId(1906);
/// `varp=4265;bits=28-29`
pub const MEMORY_CONVERSION_MODE: VarbitId = VarbitId(40524);
/// `varp=5863;bits=0-0`
pub const MIXING_VIAL_DESTROY: VarbitId = VarbitId(1723);
/// `varp=1102;bits=5-5`
pub const NECKLACE_MOULD_ON_BELT: VarbitId = VarbitId(2973);
/// `varp=1102;bits=6-6`
pub const NEEDLE_ON_BELT: VarbitId = VarbitId(2974);
/// `varp=1103;bits=19-19`
pub const NOOSE_WAND_ON_BELT: VarbitId = VarbitId(3007);
/// `varp=0;bits=17-31`
pub const OFFHAND_AUTOCAST_ACTION: VarbitId = VarbitId(18050);
/// `varp=8315;bits=0-13`
pub const ORE_BOX_ADAMANTITE: VarbitId = VarbitId(43200);
/// `varp=8323;bits=0-13`
pub const ORE_BOX_BANITE: VarbitId = VarbitId(43216);
/// `varp=8312;bits=0-13`
pub const ORE_BOX_COAL: VarbitId = VarbitId(43194);
/// `varp=8309;bits=0-13`
pub const ORE_BOX_COPPER: VarbitId = VarbitId(43188);
/// `varp=8325;bits=0-13`
pub const ORE_BOX_DARK_ANIMICA: VarbitId = VarbitId(43220);
/// `varp=8320;bits=0-13`
pub const ORE_BOX_DRAKOLITH: VarbitId = VarbitId(43210);
/// `varp=8317;bits=0-13`
pub const ORE_BOX_GOLD: VarbitId = VarbitId(43204);
/// `varp=8311;bits=0-13`
pub const ORE_BOX_IRON: VarbitId = VarbitId(43192);
/// `varp=8324;bits=0-13`
pub const ORE_BOX_LIGHT_ANIMICA: VarbitId = VarbitId(43218);
/// `varp=8316;bits=0-13`
pub const ORE_BOX_LUMINITE: VarbitId = VarbitId(43202);
/// `varp=8314;bits=0-13`
pub const ORE_BOX_MITHRIL: VarbitId = VarbitId(43198);
/// `varp=8321;bits=0-13`
pub const ORE_BOX_NECRITE: VarbitId = VarbitId(43212);
/// `varp=8319;bits=0-13`
pub const ORE_BOX_ORICHALCITE: VarbitId = VarbitId(43208);
/// `varp=8322;bits=0-13`
pub const ORE_BOX_PHASMATITE: VarbitId = VarbitId(43214);
/// `varp=8318;bits=0-13`
pub const ORE_BOX_RUNITE: VarbitId = VarbitId(43206);
/// `varp=8313;bits=0-13`
pub const ORE_BOX_SILVER: VarbitId = VarbitId(43196);
/// `varp=8310;bits=0-13`
pub const ORE_BOX_TIN: VarbitId = VarbitId(43190);
/// `varp=5699;bits=12-12`
pub const OUROBOROS_POUCH_ON_BELT: VarbitId = VarbitId(28230);
/// `varp=1103;bits=11-11`
pub const PESTLE_AND_MORTAR_ON_BELT: VarbitId = VarbitId(2999);
/// `varp=1102;bits=15-15`
pub const PICKAXE_ON_BELT: VarbitId = VarbitId(2983);
/// `varp=5863;bits=3-3`
pub const PIE_DISH_DESTROY: VarbitId = VarbitId(1726);
/// `varp=4670;bits=0-8`
pub const PLAGUES_END_PROGRESS: VarbitId = VarbitId(23198);
/// `varp=3708;bits=17-20`
pub const POWERS_WINDOW_TAB: VarbitId = VarbitId(18997);
/// `varp=4772;bits=0-0`
pub const PRIFDDINAS_ACCESS: VarbitId = VarbitId(25043);
/// `varp=4772;bits=6-6`
pub const PRIFDDINAS_SPIRIT_TREE_OPEN: VarbitId = VarbitId(25045);
/// `varp=2160;bits=0-6`
pub const PRISONER_OF_GLOUPHRIE_PROGRESS: VarbitId = VarbitId(9547);
/// `varp=5773;bits=0-0`
pub const QUICK_TELEPORT_BY_DEFAULT: VarbitId = VarbitId(28622);
/// `varp=5773;bits=1-12`
pub const QUICK_TELEPORT_CHARGES: VarbitId = VarbitId(28623);
/// `varp=1103;bits=9-9`
pub const RAKE_ON_BELT: VarbitId = VarbitId(2997);
/// `varp=627;bits=4-5`
pub const RANGED_TRAINING_MASK: VarbitId = VarbitId(1907);
/// `varp=2325;bits=3-3`
pub const RESTLESS_GHOST_AMULET_WORN: VarbitId = VarbitId(10792);
/// `varp=2325;bits=6-6`
pub const RESTLESS_GHOST_BONES_GIVEN: VarbitId = VarbitId(10794);
/// `varp=2325;bits=1-1`
pub const RESTLESS_GHOST_COFFIN_OPENED: VarbitId = VarbitId(10790);
/// `varp=2325;bits=2-2`
pub const RESTLESS_GHOST_SKULL_TAKEN: VarbitId = VarbitId(10791);
/// `varp=2325;bits=0-0`
pub const RESTLESS_GHOST_WARLOCK_SUMMONED: VarbitId = VarbitId(10789);
/// `varp=689;bits=4-8`
pub const REVENGE_STACKS: VarbitId = VarbitId(1898);
/// `varp=5860;bits=31-31`
pub const REVOLUTION_BASIC_DISABLED: VarbitId = VarbitId(38666);
/// `varp=682;bits=23-23`
pub const REVOLUTION_RANGE_ACTIVE: VarbitId = VarbitId(21682);
/// `varp=5860;bits=26-29`
pub const REVOLUTION_SIZE: VarbitId = VarbitId(38639);
/// `varp=7614;bits=0-0`
pub const REVOLUTION_THRESHOLD_DISABLED: VarbitId = VarbitId(38708);
/// `varp=7614;bits=1-1`
pub const REVOLUTION_ULTIMATE_DISABLED: VarbitId = VarbitId(38709);
/// `varp=1102;bits=7-7`
pub const RING_MOULD_ON_BELT: VarbitId = VarbitId(2975);
/// `varp=5699;bits=0-0`
pub const ROCK_HAMMER_ON_BELT: VarbitId = VarbitId(28219);
/// `varp=1103;bits=28-28`
pub const ROD_CLAY_MOULD_ON_BELT: VarbitId = VarbitId(30998);
/// `varp=5699;bits=1-1`
pub const SALT_SHAKER_ON_BELT: VarbitId = VarbitId(28220);
/// `varp=1103;bits=0-0`
pub const SAW_ON_BELT: VarbitId = VarbitId(2988);
/// `varp=5215;bits=0-4`
pub const SCREEN_SIZE_LAYOUT_12: VarbitId = VarbitId(31442);
/// `varp=5352;bits=0-4`
pub const SCREEN_SIZE_LAYOUT_13: VarbitId = VarbitId(31920);
/// `varp=3295;bits=0-4`
pub const SCREEN_SIZE_LAYOUT_6: VarbitId = VarbitId(19035);
/// `varp=3380;bits=0-4`
pub const SCREEN_SIZE_LAYOUT_7: VarbitId = VarbitId(19627);
/// `varp=2912;bits=0-4`
pub const SCREEN_SIZE_LAYOUT_8: VarbitId = VarbitId(19331);
/// `varp=1103;bits=10-10`
pub const SECATEURS_ON_BELT: VarbitId = VarbitId(2998);
/// `varp=1103;bits=7-7`
pub const SEED_DIBBER_ON_BELT: VarbitId = VarbitId(2995);
/// `varp=5699;bits=9-9`
pub const SEEDICIDE_ON_BELT: VarbitId = VarbitId(28227);
/// `varp=682;bits=5-8`
pub const SELECTED_ACTION_BAR: VarbitId = VarbitId(1893);
/// `varp=1103;bits=21-21`
pub const SEXTANT_ON_BELT: VarbitId = VarbitId(685);
/// `varp=1102;bits=1-1`
pub const SHEARS_ON_BELT: VarbitId = VarbitId(2969);
/// `varp=2164;bits=1-1`
pub const SHEEP_SHEARER_SHEARING_EXPLAINED: VarbitId = VarbitId(9581);
/// `varp=2164;bits=2-2`
pub const SHEEP_SHEARER_SPINNING_EXPLAINED: VarbitId = VarbitId(9582);
/// `varp=627;bits=21-27`
pub const SHIELD_REDUCTION: VarbitId = VarbitId(22842);
/// `varp=1103;bits=5-5`
pub const SICKLE_MOULD_ON_BELT: VarbitId = VarbitId(2993);
/// `varp=2094;bits=31-31`
pub const SLAYER_AQUANITE_UNLOCKED: VarbitId = VarbitId(9083);
/// `varp=4772;bits=8-8`
pub const SLAYER_ASSIGNMENT_EXTENDED: VarbitId = VarbitId(25047);
/// `varp=2092;bits=17-22`
pub const SLAYER_ASSIGNMENT_MASTER: VarbitId = VarbitId(9072);
/// `varp=5699;bits=4-4`
pub const SLAYER_BELL_ON_BELT: VarbitId = VarbitId(28223);
/// `varp=2093;bits=15-22`
pub const SLAYER_BLOCKED_TASK_1: VarbitId = VarbitId(9075);
/// `varp=2092;bits=23-30`
pub const SLAYER_BLOCKED_TASK_2: VarbitId = VarbitId(9073);
/// `varp=2093;bits=23-30`
pub const SLAYER_BLOCKED_TASK_3: VarbitId = VarbitId(9076);
/// `varp=2094;bits=0-7`
pub const SLAYER_BLOCKED_TASK_4: VarbitId = VarbitId(9077);
/// `varp=2094;bits=15-22`
pub const SLAYER_BLOCKED_TASK_5: VarbitId = VarbitId(9081);
/// `varp=2094;bits=23-30`
pub const SLAYER_BLOCKED_TASK_6: VarbitId = VarbitId(9082);
/// `varp=4061;bits=11-18`
pub const SLAYER_BLOCKED_TASK_7: VarbitId = VarbitId(22707);
/// `varp=4061;bits=22-29`
pub const SLAYER_BLOCKED_TASK_8: VarbitId = VarbitId(42839);
/// `varp=5699;bits=14-14`
pub const SLAYER_BONECRUSHER_BELT_UNLOCKED: VarbitId = VarbitId(28232);
/// `varp=2091;bits=18-18`
pub const SLAYER_BROAD_FLETCHING_UNLOCKED: VarbitId = VarbitId(9065);
/// `varp=5699;bits=17-17`
pub const SLAYER_CHARMING_IMP_BELT_UNLOCKED: VarbitId = VarbitId(28235);
/// `varp=7012;bits=30-31`
pub const SLAYER_CODEX_INTRODUCTION: VarbitId = VarbitId(36286);
/// `varp=4772;bits=7-7`
pub const SLAYER_FEROCIOUS_MORVRAN_UNLOCKED: VarbitId = VarbitId(25046);
/// `varp=4061;bits=0-0`
pub const SLAYER_FUSED_RINGS_UNLOCKED: VarbitId = VarbitId(21387);
/// `varp=4061;bits=19-19`
pub const SLAYER_GLACOR_UNLOCKED: VarbitId = VarbitId(23277);
/// `varp=5699;bits=20-20`
pub const SLAYER_GOLD_ACCUMULATOR_BELT_UNLOCKED: VarbitId = VarbitId(38661);
/// `varp=4061;bits=21-21`
pub const SLAYER_HELMET_CORRUPTED_PURCHASED: VarbitId = VarbitId(36284);
/// `varp=2091;bits=20-20`
pub const SLAYER_HELMET_CRAFTING_UNLOCKED: VarbitId = VarbitId(9067);
/// `varp=4061;bits=9-9`
pub const SLAYER_HELMET_MIGHTY_PURCHASED: VarbitId = VarbitId(21751);
/// `varp=4061;bits=7-7`
pub const SLAYER_HELMET_REINFORCED_PURCHASED: VarbitId = VarbitId(21749);
/// `varp=4061;bits=8-8`
pub const SLAYER_HELMET_STRONG_PURCHASED: VarbitId = VarbitId(21750);
/// `varp=5699;bits=15-15`
pub const SLAYER_HERBICIDE_BELT_UNLOCKED: VarbitId = VarbitId(28233);
/// `varp=2091;bits=31-31`
pub const SLAYER_ICE_STRYKEWYRM_UNLOCKED: VarbitId = VarbitId(9084);
/// `varp=4469;bits=0-0`
pub const SLAYER_MUSPAH_UNLOCKED: VarbitId = VarbitId(22465);
/// `varp=6640;bits=31-31`
pub const SLAYER_NIGHTMARE_UNLOCKED: VarbitId = VarbitId(34407);
/// `varp=4469;bits=1-1`
pub const SLAYER_NIHIL_UNLOCKED: VarbitId = VarbitId(22466);
/// `varp=4792;bits=0-7`
pub const SLAYER_PREFERRED_TASK_1: VarbitId = VarbitId(24948);
/// `varp=4792;bits=8-15`
pub const SLAYER_PREFERRED_TASK_2: VarbitId = VarbitId(24949);
/// `varp=4792;bits=16-23`
pub const SLAYER_PREFERRED_TASK_3: VarbitId = VarbitId(24950);
/// `varp=4792;bits=24-31`
pub const SLAYER_PREFERRED_TASK_4: VarbitId = VarbitId(24951);
/// `varp=4793;bits=0-7`
pub const SLAYER_PREFERRED_TASK_5: VarbitId = VarbitId(24952);
/// `varp=4793;bits=8-15`
pub const SLAYER_PREFERRED_TASK_6: VarbitId = VarbitId(24953);
/// `varp=4793;bits=16-23`
pub const SLAYER_PREFERRED_TASK_7: VarbitId = VarbitId(24954);
/// `varp=4793;bits=24-31`
pub const SLAYER_PREFERRED_TASK_8: VarbitId = VarbitId(42535);
/// `varp=2093;bits=31-31`
pub const SLAYER_QUICK_KILLS_UNLOCKED: VarbitId = VarbitId(9085);
/// `varp=2092;bits=0-16`
pub const SLAYER_REWARD_POINTS: VarbitId = VarbitId(9071);
/// `varp=2091;bits=19-19`
pub const SLAYER_RING_CRAFTING_UNLOCKED: VarbitId = VarbitId(9066);
/// `varp=5699;bits=16-16`
pub const SLAYER_SEEDICIDE_BELT_UNLOCKED: VarbitId = VarbitId(28234);
/// `varp=2093;bits=0-14`
pub const SLAYER_TASK_STREAK: VarbitId = VarbitId(9074);
/// `varp=4061;bits=20-20`
pub const SLAYER_TORMENTED_DEMONS_UNLOCKED: VarbitId = VarbitId(23278);
/// `varp=3814;bits=0-0`
pub const SLIM_WINDOW_HEADERS: VarbitId = VarbitId(19924);
/// `varp=1102;bits=14-14`
pub const SMALL_FISHING_NET_ON_BELT: VarbitId = VarbitId(2982);
/// `varp=3214;bits=0-2`
pub const SMALL_POUCH_ESSENCE: VarbitId = VarbitId(16497);
/// `varp=3215;bits=0-1`
pub const SMALL_POUCH_ESSENCE_KIND: VarbitId = VarbitId(16502);
/// `varp=1103;bits=12-12`
pub const SPADE_ON_BELT: VarbitId = VarbitId(3000);
/// `varp=15;bits=16-21`
pub const SPIRIT_TREE_PATCH_BRIMHAVEN: VarbitId = VarbitId(68);
/// `varp=15;bits=8-13`
pub const SPIRIT_TREE_PATCH_ETCETERIA: VarbitId = VarbitId(66);
/// `varp=9058;bits=14-19`
pub const SPIRIT_TREE_PATCH_MANOR_FARM: VarbitId = VarbitId(45329);
/// `varp=15;bits=0-5`
pub const SPIRIT_TREE_PATCH_PORT_SARIM: VarbitId = VarbitId(64);
/// `varp=7903;bits=0-0`
pub const STETHOSCOPE_ON_BELT: VarbitId = VarbitId(40235);
/// `varp=627;bits=14-20`
pub const TANK_ARMOUR_REDUCTION: VarbitId = VarbitId(22841);
/// `varp=1102;bits=8-8`
pub const TIARA_MOULD_ON_BELT: VarbitId = VarbitId(2976);
/// `varp=1102;bits=18-18`
pub const TINDERBOX_ON_BELT: VarbitId = VarbitId(2986);
/// `varp=1103;bits=27-27`
pub const TONGS_ON_BELT: VarbitId = VarbitId(28410);
/// `varp=1103;bits=6-6`
pub const UNHOLY_MOULD_ON_BELT: VarbitId = VarbitId(2994);
/// `varp=1103;bits=16-16`
pub const WATCH_ON_BELT: VarbitId = VarbitId(3004);
