//! Oracle snapshot of `ui_component_fields::Fields` (the component scalar
//! fields, declaration order).
//! Test-only, and in client910 because strings use `ui_components_oracle::text`.
use crate::ui_component_fields::Fields;
pub trait FieldsSnapshot {
    fn snapshot(&self, out: &mut Vec<u8>);
}
impl FieldsSnapshot for Fields {
    fn snapshot(&self, out: &mut Vec<u8>) {
        crate::ui_components_oracle::text(out, self.name.as_deref());
        out.extend(self.serverTriggers.to_be_bytes());
        out.extend(self.parentlayer.to_be_bytes());
        out.extend(self.id.to_be_bytes());
        out.extend(self.r#type.to_be_bytes());
        out.extend(self.clientcode.to_be_bytes());
        out.push(self.xmode as u8);
        out.push(self.ymode as u8);
        out.push(self.widthSizeMode as u8);
        out.push(self.heightSizeMode as u8);
        out.extend(self.xpos.to_be_bytes());
        out.extend(self.ypos.to_be_bytes());
        out.extend(self.wsize.to_be_bytes());
        out.extend(self.hsize.to_be_bytes());
        out.extend(self.x.to_be_bytes());
        out.extend(self.y.to_be_bytes());
        out.extend(self.width.to_be_bytes());
        out.extend(self.height.to_be_bytes());
        out.extend(self.aspectwidth.to_be_bytes());
        out.extend(self.aspectheight.to_be_bytes());
        out.extend(self.layer.to_be_bytes());
        out.push(self.hide as u8);
        out.extend(self.targetCursor.to_be_bytes());
        out.extend(self.targetDefaultCursor.to_be_bytes());
        out.extend(self.mouseovercursor.to_be_bytes());
        out.push(self.noclickthrough as u8);
        out.extend(self.scrollx.to_be_bytes());
        out.extend(self.scrolly.to_be_bytes());
        out.extend(self.scrollwidth.to_be_bytes());
        out.extend(self.scrollheight.to_be_bytes());
        out.extend(self.colour.to_be_bytes());
        out.push(self.fill as u8);
        out.extend(self.trans.to_be_bytes());
        out.extend(self.linewid.to_be_bytes());
        out.push(self.linedirection as u8);
        out.extend(self.graphic.to_be_bytes());
        out.extend(self.angle2d.to_be_bytes());
        out.push(self.tiling as u8);
        out.extend(self.outline.to_be_bytes());
        out.extend(self.graphicshadow.to_be_bytes());
        out.push(self.vflip as u8);
        out.push(self.hflip as u8);
        out.push(self.alpha as u8);
        out.push(self.clickmask as u8);
        out.extend(self.modelkind.to_be_bytes());
        out.extend(self.model.to_be_bytes());
        out.extend(self.modelNameHash.to_be_bytes());
        out.push(self.useExtendedModelTransform as u8);
        out.extend(self.modelxof.to_be_bytes());
        out.extend(self.modelyof.to_be_bytes());
        out.extend(self.modelangle_x.to_be_bytes());
        out.extend(self.modelangle_y.to_be_bytes());
        out.extend(self.modelangle_z.to_be_bytes());
        out.extend(self.modelorigin_x.to_be_bytes());
        out.extend(self.modelorigin_y.to_be_bytes());
        out.extend(self.modelorigin_z.to_be_bytes());
        out.extend(self.modelzoom.to_be_bytes());
        out.extend(self.modelobjwidth.to_be_bytes());
        out.extend(self.modelobjheight.to_be_bytes());
        out.push(self.modelorthog as u8);
        out.push(self.disableDepthTest as u8);
        out.extend(self.obj_count_display.to_be_bytes());
        out.extend(self.tint_hue.to_be_bytes());
        out.extend(self.tint_saturation.to_be_bytes());
        out.extend(self.tint_luminence.to_be_bytes());
        out.extend(self.tint_weight.to_be_bytes());
        out.push(self.customlighting as u8);
        out.extend(self.lightExtraA.to_be_bytes());
        out.extend(self.lightExtraB.to_be_bytes());
        out.extend(self.lightExtraC.to_be_bytes());
        out.extend(self.lightDirY.to_be_bytes());
        out.extend(self.lightDirZ.to_be_bytes());
        out.extend(self.lightDirX.to_be_bytes());
        out.extend(self.lightColour.to_be_bytes());
        out.extend(self.lightExtraD.to_be_bytes());
        out.extend(self.textfont.to_be_bytes());
        out.push(self.fontmono as u8);
        crate::ui_components_oracle::text(out, self.text.as_deref());
        out.extend(self.textLineHeight.to_be_bytes());
        out.extend(self.textHAlign.to_be_bytes());
        out.extend(self.textVAlign.to_be_bytes());
        out.push(self.textshadow as u8);
        out.extend(self.maxlines.to_be_bytes());
        out.push(self.textantimacro as u8);
        out.push(self.hasKeybinds as u8);
        crate::ui_components_oracle::text(out, self.opbase.as_deref());
        crate::ui_components_oracle::text(out, self.pausetext.as_deref());
        out.extend(self.targetopcursor.to_be_bytes());
        out.extend(self.dragdeadzone.to_be_bytes());
        out.extend(self.dragdeadtime.to_be_bytes());
        out.extend(self.dragrenderbehaviour.to_be_bytes());
        crate::ui_components_oracle::text(out, self.targetverb.as_deref());
        out.push(self.hashook as u8);
        out.extend(self.invobject.to_be_bytes());
        out.extend(self.invcount.to_be_bytes());
        crate::ui_components_oracle::text(out, self.link.as_deref());
        out.push(self.usePlayerModel as u8);
        out.extend(self.skyboxId.to_be_bytes());
        out.extend(self.skybox_pitch.to_be_bytes());
        out.extend(self.skybox_yaw.to_be_bytes());
        out.extend(self.skybox_view_x.to_be_bytes());
        out.extend(self.skybox_view_y.to_be_bytes());
        out.extend(self.skybox_view_z.to_be_bytes());
        out.extend(self.httpImageId.to_be_bytes());
        out.extend(self.modelanim.to_be_bytes());
        out.push(self.hovered as u8);
        out.push(self.held as u8);
        out.extend(self.lastRedrawCycle.to_be_bytes());
        out.extend(self.lastVarTransmit.to_be_bytes());
        out.extend(self.lastInvTransmit.to_be_bytes());
        out.extend(self.lastStatTransmit.to_be_bytes());
        out.extend(self.lastVarcTransmit.to_be_bytes());
        out.extend(self.lastVarcstrTransmit.to_be_bytes());
        out.extend(self.lastVarclanTransmit.to_be_bytes());
        out.extend(self.topLevelIndex.to_be_bytes());
        out.extend(self.lastDrawCycle.to_be_bytes());
    }
}
