//! The shell's key translation: a winit physical key to the AWT
//! `KeyEvent.VK_*` code the window owner replays into `ui_keyboard`
//! (the keyboard snapshot). Split out of `ui_keyboard` in Phase 3.2 (winit stays in
//! the shell).
/// AWT `KeyEvent.VK_*` for a winit physical key, or 0 when the client has no code.
pub fn awt_keycode(code: winit::keyboard::KeyCode) -> i32 {
    use winit::keyboard::KeyCode as K;
    match code {
        K::KeyA => 65,
        K::KeyB => 66,
        K::KeyC => 67,
        K::KeyD => 68,
        K::KeyE => 69,
        K::KeyF => 70,
        K::KeyG => 71,
        K::KeyH => 72,
        K::KeyI => 73,
        K::KeyJ => 74,
        K::KeyK => 75,
        K::KeyL => 76,
        K::KeyM => 77,
        K::KeyN => 78,
        K::KeyO => 79,
        K::KeyP => 80,
        K::KeyQ => 81,
        K::KeyR => 82,
        K::KeyS => 83,
        K::KeyT => 84,
        K::KeyU => 85,
        K::KeyV => 86,
        K::KeyW => 87,
        K::KeyX => 88,
        K::KeyY => 89,
        K::KeyZ => 90,
        K::Digit0 => 48,
        K::Digit1 => 49,
        K::Digit2 => 50,
        K::Digit3 => 51,
        K::Digit4 => 52,
        K::Digit5 => 53,
        K::Digit6 => 54,
        K::Digit7 => 55,
        K::Digit8 => 56,
        K::Digit9 => 57,
        K::F1 => 112,
        K::F2 => 113,
        K::F3 => 114,
        K::F4 => 115,
        K::F5 => 116,
        K::F6 => 117,
        K::F7 => 118,
        K::F8 => 119,
        K::F9 => 120,
        K::F10 => 121,
        K::F11 => 122,
        K::F12 => 123,
        K::Enter | K::NumpadEnter => 10,
        K::Backspace => 8,
        K::Tab => 9,
        K::Escape => 27,
        K::Space => 32,
        K::PageUp => 33,
        K::PageDown => 34,
        K::End => 35,
        K::Home => 36,
        K::ArrowLeft => 37,
        K::ArrowUp => 38,
        K::ArrowRight => 39,
        K::ArrowDown => 40,
        K::Insert => 155,
        K::Delete => 127,
        K::ShiftLeft | K::ShiftRight => 16,
        K::ControlLeft | K::ControlRight => 17,
        K::AltLeft | K::AltRight => 18,
        K::CapsLock => 20,
        K::Numpad0 => 96,
        K::Numpad1 => 97,
        K::Numpad2 => 98,
        K::Numpad3 => 99,
        K::Numpad4 => 100,
        K::Numpad5 => 101,
        K::Numpad6 => 102,
        K::Numpad7 => 103,
        K::Numpad8 => 104,
        K::Numpad9 => 105,
        K::NumpadMultiply => 106,
        K::NumpadAdd => 107,
        K::NumpadSubtract => 109,
        K::NumpadDecimal => 110,
        K::NumpadDivide => 111,
        K::Comma => 44,
        K::Minus => 45,
        K::Period => 46,
        K::Slash => 47,
        K::Semicolon => 59,
        K::Equal => 61,
        K::BracketLeft => 91,
        K::Backslash => 92,
        K::BracketRight => 93,
        K::Backquote => 192,
        K::Quote => 222,
        K::SuperLeft | K::SuperRight => 157,
        _ => 0,
    }
}
